/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.axon.market.s4hana.client.APIBUSINESSPARTNERASupplierCompanyTypeToCompanyText;
import com.axon.market.s4hana.client.APIBUSINESSPARTNERASupplierCompanyTypeToSupplierDunning;
import com.axon.market.s4hana.client.APIBUSINESSPARTNERASupplierCompanyTypeToSupplierWithHoldingTax;
import com.axon.market.s4hana.client.APIBUSINESSPARTNERASupplierType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERASupplierCompanyType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERASupplierCompanyType {
  @JsonProperty("Supplier")
  private String supplier = null;

  @JsonProperty("CompanyCode")
  private String companyCode = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  @JsonProperty("CompanyCodeName")
  private String companyCodeName = null;

  @JsonProperty("PaymentBlockingReason")
  private String paymentBlockingReason = null;

  @JsonProperty("SupplierIsBlockedForPosting")
  private Boolean supplierIsBlockedForPosting = null;

  @JsonProperty("AccountingClerk")
  private String accountingClerk = null;

  @JsonProperty("AccountingClerkFaxNumber")
  private String accountingClerkFaxNumber = null;

  @JsonProperty("AccountingClerkPhoneNumber")
  private String accountingClerkPhoneNumber = null;

  @JsonProperty("SupplierClerk")
  private String supplierClerk = null;

  @JsonProperty("SupplierClerkURL")
  private String supplierClerkURL = null;

  @JsonProperty("PaymentMethodsList")
  private String paymentMethodsList = null;

  @JsonProperty("PaymentReason")
  private String paymentReason = null;

  @JsonProperty("PaymentTerms")
  private String paymentTerms = null;

  @JsonProperty("ClearCustomerSupplier")
  private Boolean clearCustomerSupplier = null;

  @JsonProperty("IsToBeLocallyProcessed")
  private Boolean isToBeLocallyProcessed = null;

  @JsonProperty("ItemIsToBePaidSeparately")
  private Boolean itemIsToBePaidSeparately = null;

  @JsonProperty("PaymentIsToBeSentByEDI")
  private Boolean paymentIsToBeSentByEDI = null;

  @JsonProperty("HouseBank")
  private String houseBank = null;

  @JsonProperty("CheckPaidDurationInDays")
  private String checkPaidDurationInDays = null;

  @JsonProperty("Currency")
  private String currency = null;

  @JsonProperty("BillOfExchLmtAmtInCoCodeCrcy")
  private String billOfExchLmtAmtInCoCodeCrcy = null;

  @JsonProperty("SupplierClerkIDBySupplier")
  private String supplierClerkIDBySupplier = null;

  @JsonProperty("ReconciliationAccount")
  private String reconciliationAccount = null;

  @JsonProperty("InterestCalculationCode")
  private String interestCalculationCode = null;

  @JsonProperty("InterestCalculationDate")
  private String interestCalculationDate = null;

  @JsonProperty("IntrstCalcFrequencyInMonths")
  private String intrstCalcFrequencyInMonths = null;

  @JsonProperty("SupplierHeadOffice")
  private String supplierHeadOffice = null;

  @JsonProperty("AlternativePayee")
  private String alternativePayee = null;

  @JsonProperty("LayoutSortingRule")
  private String layoutSortingRule = null;

  @JsonProperty("APARToleranceGroup")
  private String apARToleranceGroup = null;

  @JsonProperty("SupplierCertificationDate")
  private String supplierCertificationDate = null;

  @JsonProperty("SupplierAccountNote")
  private String supplierAccountNote = null;

  @JsonProperty("WithholdingTaxCountry")
  private String withholdingTaxCountry = null;

  @JsonProperty("DeletionIndicator")
  private Boolean deletionIndicator = null;

  @JsonProperty("CashPlanningGroup")
  private String cashPlanningGroup = null;

  @JsonProperty("IsToBeCheckedForDuplicates")
  private Boolean isToBeCheckedForDuplicates = null;

  @JsonProperty("MinorityGroup")
  private String minorityGroup = null;

  @JsonProperty("SupplierAccountGroup")
  private String supplierAccountGroup = null;

  @JsonProperty("to_CompanyText")
  private APIBUSINESSPARTNERASupplierCompanyTypeToCompanyText toCompanyText = null;

  @JsonProperty("to_Supplier")
  private APIBUSINESSPARTNERASupplierType toSupplier = null;

  @JsonProperty("to_SupplierDunning")
  private APIBUSINESSPARTNERASupplierCompanyTypeToSupplierDunning toSupplierDunning = null;

  @JsonProperty("to_SupplierWithHoldingTax")
  private APIBUSINESSPARTNERASupplierCompanyTypeToSupplierWithHoldingTax toSupplierWithHoldingTax = null;

  public APIBUSINESSPARTNERASupplierCompanyType supplier(String supplier) {
    this.supplier = supplier;
    return this;
  }

   /**
   * Account Number of Supplier
   * @return supplier
  **/
  public String getSupplier() {
    return supplier;
  }

  public void setSupplier(String supplier) {
    this.supplier = supplier;
  }

  public APIBUSINESSPARTNERASupplierCompanyType companyCode(String companyCode) {
    this.companyCode = companyCode;
    return this;
  }

   /**
   * Get companyCode
   * @return companyCode
  **/
  public String getCompanyCode() {
    return companyCode;
  }

  public void setCompanyCode(String companyCode) {
    this.companyCode = companyCode;
  }

  public APIBUSINESSPARTNERASupplierCompanyType authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Authorization Group
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }

  public APIBUSINESSPARTNERASupplierCompanyType companyCodeName(String companyCodeName) {
    this.companyCodeName = companyCodeName;
    return this;
  }

   /**
   * Name of Company Code or Company
   * @return companyCodeName
  **/
  public String getCompanyCodeName() {
    return companyCodeName;
  }

  public void setCompanyCodeName(String companyCodeName) {
    this.companyCodeName = companyCodeName;
  }

  public APIBUSINESSPARTNERASupplierCompanyType paymentBlockingReason(String paymentBlockingReason) {
    this.paymentBlockingReason = paymentBlockingReason;
    return this;
  }

   /**
   * Block Key for Payment
   * @return paymentBlockingReason
  **/
  public String getPaymentBlockingReason() {
    return paymentBlockingReason;
  }

  public void setPaymentBlockingReason(String paymentBlockingReason) {
    this.paymentBlockingReason = paymentBlockingReason;
  }

  public APIBUSINESSPARTNERASupplierCompanyType supplierIsBlockedForPosting(Boolean supplierIsBlockedForPosting) {
    this.supplierIsBlockedForPosting = supplierIsBlockedForPosting;
    return this;
  }

   /**
   * Posting block for company code
   * @return supplierIsBlockedForPosting
  **/
  public Boolean isSupplierIsBlockedForPosting() {
    return supplierIsBlockedForPosting;
  }

  public void setSupplierIsBlockedForPosting(Boolean supplierIsBlockedForPosting) {
    this.supplierIsBlockedForPosting = supplierIsBlockedForPosting;
  }

  public APIBUSINESSPARTNERASupplierCompanyType accountingClerk(String accountingClerk) {
    this.accountingClerk = accountingClerk;
    return this;
  }

   /**
   * Accounting Clerk Abbreviation
   * @return accountingClerk
  **/
  public String getAccountingClerk() {
    return accountingClerk;
  }

  public void setAccountingClerk(String accountingClerk) {
    this.accountingClerk = accountingClerk;
  }

  public APIBUSINESSPARTNERASupplierCompanyType accountingClerkFaxNumber(String accountingClerkFaxNumber) {
    this.accountingClerkFaxNumber = accountingClerkFaxNumber;
    return this;
  }

   /**
   * Accounting clerk&#x27;s fax number at the customer/vendor
   * @return accountingClerkFaxNumber
  **/
  public String getAccountingClerkFaxNumber() {
    return accountingClerkFaxNumber;
  }

  public void setAccountingClerkFaxNumber(String accountingClerkFaxNumber) {
    this.accountingClerkFaxNumber = accountingClerkFaxNumber;
  }

  public APIBUSINESSPARTNERASupplierCompanyType accountingClerkPhoneNumber(String accountingClerkPhoneNumber) {
    this.accountingClerkPhoneNumber = accountingClerkPhoneNumber;
    return this;
  }

   /**
   * Accounting clerk&#x27;s telephone number at business partner
   * @return accountingClerkPhoneNumber
  **/
  public String getAccountingClerkPhoneNumber() {
    return accountingClerkPhoneNumber;
  }

  public void setAccountingClerkPhoneNumber(String accountingClerkPhoneNumber) {
    this.accountingClerkPhoneNumber = accountingClerkPhoneNumber;
  }

  public APIBUSINESSPARTNERASupplierCompanyType supplierClerk(String supplierClerk) {
    this.supplierClerk = supplierClerk;
    return this;
  }

   /**
   * Get supplierClerk
   * @return supplierClerk
  **/
  public String getSupplierClerk() {
    return supplierClerk;
  }

  public void setSupplierClerk(String supplierClerk) {
    this.supplierClerk = supplierClerk;
  }

  public APIBUSINESSPARTNERASupplierCompanyType supplierClerkURL(String supplierClerkURL) {
    this.supplierClerkURL = supplierClerkURL;
    return this;
  }

   /**
   * Internet address of partner company clerk
   * @return supplierClerkURL
  **/
  public String getSupplierClerkURL() {
    return supplierClerkURL;
  }

  public void setSupplierClerkURL(String supplierClerkURL) {
    this.supplierClerkURL = supplierClerkURL;
  }

  public APIBUSINESSPARTNERASupplierCompanyType paymentMethodsList(String paymentMethodsList) {
    this.paymentMethodsList = paymentMethodsList;
    return this;
  }

   /**
   * List of Respected Payment Methods
   * @return paymentMethodsList
  **/
  public String getPaymentMethodsList() {
    return paymentMethodsList;
  }

  public void setPaymentMethodsList(String paymentMethodsList) {
    this.paymentMethodsList = paymentMethodsList;
  }

  public APIBUSINESSPARTNERASupplierCompanyType paymentReason(String paymentReason) {
    this.paymentReason = paymentReason;
    return this;
  }

   /**
   * Get paymentReason
   * @return paymentReason
  **/
  public String getPaymentReason() {
    return paymentReason;
  }

  public void setPaymentReason(String paymentReason) {
    this.paymentReason = paymentReason;
  }

  public APIBUSINESSPARTNERASupplierCompanyType paymentTerms(String paymentTerms) {
    this.paymentTerms = paymentTerms;
    return this;
  }

   /**
   * Key for Terms of Payment
   * @return paymentTerms
  **/
  public String getPaymentTerms() {
    return paymentTerms;
  }

  public void setPaymentTerms(String paymentTerms) {
    this.paymentTerms = paymentTerms;
  }

  public APIBUSINESSPARTNERASupplierCompanyType clearCustomerSupplier(Boolean clearCustomerSupplier) {
    this.clearCustomerSupplier = clearCustomerSupplier;
    return this;
  }

   /**
   * Indicator: Clearing between customer and vendor?
   * @return clearCustomerSupplier
  **/
  public Boolean isClearCustomerSupplier() {
    return clearCustomerSupplier;
  }

  public void setClearCustomerSupplier(Boolean clearCustomerSupplier) {
    this.clearCustomerSupplier = clearCustomerSupplier;
  }

  public APIBUSINESSPARTNERASupplierCompanyType isToBeLocallyProcessed(Boolean isToBeLocallyProcessed) {
    this.isToBeLocallyProcessed = isToBeLocallyProcessed;
    return this;
  }

   /**
   * Indicator: Local Processing?
   * @return isToBeLocallyProcessed
  **/
  public Boolean isIsToBeLocallyProcessed() {
    return isToBeLocallyProcessed;
  }

  public void setIsToBeLocallyProcessed(Boolean isToBeLocallyProcessed) {
    this.isToBeLocallyProcessed = isToBeLocallyProcessed;
  }

  public APIBUSINESSPARTNERASupplierCompanyType itemIsToBePaidSeparately(Boolean itemIsToBePaidSeparately) {
    this.itemIsToBePaidSeparately = itemIsToBePaidSeparately;
    return this;
  }

   /**
   * Indicator: Pay All Items Separately?
   * @return itemIsToBePaidSeparately
  **/
  public Boolean isItemIsToBePaidSeparately() {
    return itemIsToBePaidSeparately;
  }

  public void setItemIsToBePaidSeparately(Boolean itemIsToBePaidSeparately) {
    this.itemIsToBePaidSeparately = itemIsToBePaidSeparately;
  }

  public APIBUSINESSPARTNERASupplierCompanyType paymentIsToBeSentByEDI(Boolean paymentIsToBeSentByEDI) {
    this.paymentIsToBeSentByEDI = paymentIsToBeSentByEDI;
    return this;
  }

   /**
   * Indicator: Send Payment Advices by EDI
   * @return paymentIsToBeSentByEDI
  **/
  public Boolean isPaymentIsToBeSentByEDI() {
    return paymentIsToBeSentByEDI;
  }

  public void setPaymentIsToBeSentByEDI(Boolean paymentIsToBeSentByEDI) {
    this.paymentIsToBeSentByEDI = paymentIsToBeSentByEDI;
  }

  public APIBUSINESSPARTNERASupplierCompanyType houseBank(String houseBank) {
    this.houseBank = houseBank;
    return this;
  }

   /**
   * Short Key for a House Bank
   * @return houseBank
  **/
  public String getHouseBank() {
    return houseBank;
  }

  public void setHouseBank(String houseBank) {
    this.houseBank = houseBank;
  }

  public APIBUSINESSPARTNERASupplierCompanyType checkPaidDurationInDays(String checkPaidDurationInDays) {
    this.checkPaidDurationInDays = checkPaidDurationInDays;
    return this;
  }

   /**
   * Probable Time Until Check Is Paid
   * @return checkPaidDurationInDays
  **/
  public String getCheckPaidDurationInDays() {
    return checkPaidDurationInDays;
  }

  public void setCheckPaidDurationInDays(String checkPaidDurationInDays) {
    this.checkPaidDurationInDays = checkPaidDurationInDays;
  }

  public APIBUSINESSPARTNERASupplierCompanyType currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency Key
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public APIBUSINESSPARTNERASupplierCompanyType billOfExchLmtAmtInCoCodeCrcy(String billOfExchLmtAmtInCoCodeCrcy) {
    this.billOfExchLmtAmtInCoCodeCrcy = billOfExchLmtAmtInCoCodeCrcy;
    return this;
  }

   /**
   * Bill of Exchange Limit (in Local Currency)
   * @return billOfExchLmtAmtInCoCodeCrcy
  **/
  public String getBillOfExchLmtAmtInCoCodeCrcy() {
    return billOfExchLmtAmtInCoCodeCrcy;
  }

  public void setBillOfExchLmtAmtInCoCodeCrcy(String billOfExchLmtAmtInCoCodeCrcy) {
    this.billOfExchLmtAmtInCoCodeCrcy = billOfExchLmtAmtInCoCodeCrcy;
  }

  public APIBUSINESSPARTNERASupplierCompanyType supplierClerkIDBySupplier(String supplierClerkIDBySupplier) {
    this.supplierClerkIDBySupplier = supplierClerkIDBySupplier;
    return this;
  }

   /**
   * Our account number with the vendor
   * @return supplierClerkIDBySupplier
  **/
  public String getSupplierClerkIDBySupplier() {
    return supplierClerkIDBySupplier;
  }

  public void setSupplierClerkIDBySupplier(String supplierClerkIDBySupplier) {
    this.supplierClerkIDBySupplier = supplierClerkIDBySupplier;
  }

  public APIBUSINESSPARTNERASupplierCompanyType reconciliationAccount(String reconciliationAccount) {
    this.reconciliationAccount = reconciliationAccount;
    return this;
  }

   /**
   * Reconciliation Account in General Ledger
   * @return reconciliationAccount
  **/
  public String getReconciliationAccount() {
    return reconciliationAccount;
  }

  public void setReconciliationAccount(String reconciliationAccount) {
    this.reconciliationAccount = reconciliationAccount;
  }

  public APIBUSINESSPARTNERASupplierCompanyType interestCalculationCode(String interestCalculationCode) {
    this.interestCalculationCode = interestCalculationCode;
    return this;
  }

   /**
   * Get interestCalculationCode
   * @return interestCalculationCode
  **/
  public String getInterestCalculationCode() {
    return interestCalculationCode;
  }

  public void setInterestCalculationCode(String interestCalculationCode) {
    this.interestCalculationCode = interestCalculationCode;
  }

  public APIBUSINESSPARTNERASupplierCompanyType interestCalculationDate(String interestCalculationDate) {
    this.interestCalculationDate = interestCalculationDate;
    return this;
  }

   /**
   * Key Date of Last Interest Calculation
   * @return interestCalculationDate
  **/
  public String getInterestCalculationDate() {
    return interestCalculationDate;
  }

  public void setInterestCalculationDate(String interestCalculationDate) {
    this.interestCalculationDate = interestCalculationDate;
  }

  public APIBUSINESSPARTNERASupplierCompanyType intrstCalcFrequencyInMonths(String intrstCalcFrequencyInMonths) {
    this.intrstCalcFrequencyInMonths = intrstCalcFrequencyInMonths;
    return this;
  }

   /**
   * Interest Calculation Frequency in Months
   * @return intrstCalcFrequencyInMonths
  **/
  public String getIntrstCalcFrequencyInMonths() {
    return intrstCalcFrequencyInMonths;
  }

  public void setIntrstCalcFrequencyInMonths(String intrstCalcFrequencyInMonths) {
    this.intrstCalcFrequencyInMonths = intrstCalcFrequencyInMonths;
  }

  public APIBUSINESSPARTNERASupplierCompanyType supplierHeadOffice(String supplierHeadOffice) {
    this.supplierHeadOffice = supplierHeadOffice;
    return this;
  }

   /**
   * Head Office Account Number
   * @return supplierHeadOffice
  **/
  public String getSupplierHeadOffice() {
    return supplierHeadOffice;
  }

  public void setSupplierHeadOffice(String supplierHeadOffice) {
    this.supplierHeadOffice = supplierHeadOffice;
  }

  public APIBUSINESSPARTNERASupplierCompanyType alternativePayee(String alternativePayee) {
    this.alternativePayee = alternativePayee;
    return this;
  }

   /**
   * Account number of the alternative payee
   * @return alternativePayee
  **/
  public String getAlternativePayee() {
    return alternativePayee;
  }

  public void setAlternativePayee(String alternativePayee) {
    this.alternativePayee = alternativePayee;
  }

  public APIBUSINESSPARTNERASupplierCompanyType layoutSortingRule(String layoutSortingRule) {
    this.layoutSortingRule = layoutSortingRule;
    return this;
  }

   /**
   * Key for Sorting According to Assignment Numbers
   * @return layoutSortingRule
  **/
  public String getLayoutSortingRule() {
    return layoutSortingRule;
  }

  public void setLayoutSortingRule(String layoutSortingRule) {
    this.layoutSortingRule = layoutSortingRule;
  }

  public APIBUSINESSPARTNERASupplierCompanyType apARToleranceGroup(String apARToleranceGroup) {
    this.apARToleranceGroup = apARToleranceGroup;
    return this;
  }

   /**
   * Tolerance Group for Business Partner/G/L Account
   * @return apARToleranceGroup
  **/
  public String getApARToleranceGroup() {
    return apARToleranceGroup;
  }

  public void setApARToleranceGroup(String apARToleranceGroup) {
    this.apARToleranceGroup = apARToleranceGroup;
  }

  public APIBUSINESSPARTNERASupplierCompanyType supplierCertificationDate(String supplierCertificationDate) {
    this.supplierCertificationDate = supplierCertificationDate;
    return this;
  }

   /**
   * Get supplierCertificationDate
   * @return supplierCertificationDate
  **/
  public String getSupplierCertificationDate() {
    return supplierCertificationDate;
  }

  public void setSupplierCertificationDate(String supplierCertificationDate) {
    this.supplierCertificationDate = supplierCertificationDate;
  }

  public APIBUSINESSPARTNERASupplierCompanyType supplierAccountNote(String supplierAccountNote) {
    this.supplierAccountNote = supplierAccountNote;
    return this;
  }

   /**
   * Memo
   * @return supplierAccountNote
  **/
  public String getSupplierAccountNote() {
    return supplierAccountNote;
  }

  public void setSupplierAccountNote(String supplierAccountNote) {
    this.supplierAccountNote = supplierAccountNote;
  }

  public APIBUSINESSPARTNERASupplierCompanyType withholdingTaxCountry(String withholdingTaxCountry) {
    this.withholdingTaxCountry = withholdingTaxCountry;
    return this;
  }

   /**
   * Withholding Tax Country/Region Key
   * @return withholdingTaxCountry
  **/
  public String getWithholdingTaxCountry() {
    return withholdingTaxCountry;
  }

  public void setWithholdingTaxCountry(String withholdingTaxCountry) {
    this.withholdingTaxCountry = withholdingTaxCountry;
  }

  public APIBUSINESSPARTNERASupplierCompanyType deletionIndicator(Boolean deletionIndicator) {
    this.deletionIndicator = deletionIndicator;
    return this;
  }

   /**
   * Deletion Flag for Master Record (Company Code Level)
   * @return deletionIndicator
  **/
  public Boolean isDeletionIndicator() {
    return deletionIndicator;
  }

  public void setDeletionIndicator(Boolean deletionIndicator) {
    this.deletionIndicator = deletionIndicator;
  }

  public APIBUSINESSPARTNERASupplierCompanyType cashPlanningGroup(String cashPlanningGroup) {
    this.cashPlanningGroup = cashPlanningGroup;
    return this;
  }

   /**
   * Get cashPlanningGroup
   * @return cashPlanningGroup
  **/
  public String getCashPlanningGroup() {
    return cashPlanningGroup;
  }

  public void setCashPlanningGroup(String cashPlanningGroup) {
    this.cashPlanningGroup = cashPlanningGroup;
  }

  public APIBUSINESSPARTNERASupplierCompanyType isToBeCheckedForDuplicates(Boolean isToBeCheckedForDuplicates) {
    this.isToBeCheckedForDuplicates = isToBeCheckedForDuplicates;
    return this;
  }

   /**
   * Check Flag for Double Invoices or Credit Memos
   * @return isToBeCheckedForDuplicates
  **/
  public Boolean isIsToBeCheckedForDuplicates() {
    return isToBeCheckedForDuplicates;
  }

  public void setIsToBeCheckedForDuplicates(Boolean isToBeCheckedForDuplicates) {
    this.isToBeCheckedForDuplicates = isToBeCheckedForDuplicates;
  }

  public APIBUSINESSPARTNERASupplierCompanyType minorityGroup(String minorityGroup) {
    this.minorityGroup = minorityGroup;
    return this;
  }

   /**
   * Get minorityGroup
   * @return minorityGroup
  **/
  public String getMinorityGroup() {
    return minorityGroup;
  }

  public void setMinorityGroup(String minorityGroup) {
    this.minorityGroup = minorityGroup;
  }

  public APIBUSINESSPARTNERASupplierCompanyType supplierAccountGroup(String supplierAccountGroup) {
    this.supplierAccountGroup = supplierAccountGroup;
    return this;
  }

   /**
   * Supplier Account Group
   * @return supplierAccountGroup
  **/
  public String getSupplierAccountGroup() {
    return supplierAccountGroup;
  }

  public void setSupplierAccountGroup(String supplierAccountGroup) {
    this.supplierAccountGroup = supplierAccountGroup;
  }

  public APIBUSINESSPARTNERASupplierCompanyType toCompanyText(APIBUSINESSPARTNERASupplierCompanyTypeToCompanyText toCompanyText) {
    this.toCompanyText = toCompanyText;
    return this;
  }

   /**
   * Get toCompanyText
   * @return toCompanyText
  **/
  public APIBUSINESSPARTNERASupplierCompanyTypeToCompanyText getToCompanyText() {
    return toCompanyText;
  }

  public void setToCompanyText(APIBUSINESSPARTNERASupplierCompanyTypeToCompanyText toCompanyText) {
    this.toCompanyText = toCompanyText;
  }

  public APIBUSINESSPARTNERASupplierCompanyType toSupplier(APIBUSINESSPARTNERASupplierType toSupplier) {
    this.toSupplier = toSupplier;
    return this;
  }

   /**
   * Get toSupplier
   * @return toSupplier
  **/
  public APIBUSINESSPARTNERASupplierType getToSupplier() {
    return toSupplier;
  }

  public void setToSupplier(APIBUSINESSPARTNERASupplierType toSupplier) {
    this.toSupplier = toSupplier;
  }

  public APIBUSINESSPARTNERASupplierCompanyType toSupplierDunning(APIBUSINESSPARTNERASupplierCompanyTypeToSupplierDunning toSupplierDunning) {
    this.toSupplierDunning = toSupplierDunning;
    return this;
  }

   /**
   * Get toSupplierDunning
   * @return toSupplierDunning
  **/
  public APIBUSINESSPARTNERASupplierCompanyTypeToSupplierDunning getToSupplierDunning() {
    return toSupplierDunning;
  }

  public void setToSupplierDunning(APIBUSINESSPARTNERASupplierCompanyTypeToSupplierDunning toSupplierDunning) {
    this.toSupplierDunning = toSupplierDunning;
  }

  public APIBUSINESSPARTNERASupplierCompanyType toSupplierWithHoldingTax(APIBUSINESSPARTNERASupplierCompanyTypeToSupplierWithHoldingTax toSupplierWithHoldingTax) {
    this.toSupplierWithHoldingTax = toSupplierWithHoldingTax;
    return this;
  }

   /**
   * Get toSupplierWithHoldingTax
   * @return toSupplierWithHoldingTax
  **/
  public APIBUSINESSPARTNERASupplierCompanyTypeToSupplierWithHoldingTax getToSupplierWithHoldingTax() {
    return toSupplierWithHoldingTax;
  }

  public void setToSupplierWithHoldingTax(APIBUSINESSPARTNERASupplierCompanyTypeToSupplierWithHoldingTax toSupplierWithHoldingTax) {
    this.toSupplierWithHoldingTax = toSupplierWithHoldingTax;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERASupplierCompanyType apIBUSINESSPARTNERASupplierCompanyType = (APIBUSINESSPARTNERASupplierCompanyType) o;
    return Objects.equals(this.supplier, apIBUSINESSPARTNERASupplierCompanyType.supplier) &&
        Objects.equals(this.companyCode, apIBUSINESSPARTNERASupplierCompanyType.companyCode) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERASupplierCompanyType.authorizationGroup) &&
        Objects.equals(this.companyCodeName, apIBUSINESSPARTNERASupplierCompanyType.companyCodeName) &&
        Objects.equals(this.paymentBlockingReason, apIBUSINESSPARTNERASupplierCompanyType.paymentBlockingReason) &&
        Objects.equals(this.supplierIsBlockedForPosting, apIBUSINESSPARTNERASupplierCompanyType.supplierIsBlockedForPosting) &&
        Objects.equals(this.accountingClerk, apIBUSINESSPARTNERASupplierCompanyType.accountingClerk) &&
        Objects.equals(this.accountingClerkFaxNumber, apIBUSINESSPARTNERASupplierCompanyType.accountingClerkFaxNumber) &&
        Objects.equals(this.accountingClerkPhoneNumber, apIBUSINESSPARTNERASupplierCompanyType.accountingClerkPhoneNumber) &&
        Objects.equals(this.supplierClerk, apIBUSINESSPARTNERASupplierCompanyType.supplierClerk) &&
        Objects.equals(this.supplierClerkURL, apIBUSINESSPARTNERASupplierCompanyType.supplierClerkURL) &&
        Objects.equals(this.paymentMethodsList, apIBUSINESSPARTNERASupplierCompanyType.paymentMethodsList) &&
        Objects.equals(this.paymentReason, apIBUSINESSPARTNERASupplierCompanyType.paymentReason) &&
        Objects.equals(this.paymentTerms, apIBUSINESSPARTNERASupplierCompanyType.paymentTerms) &&
        Objects.equals(this.clearCustomerSupplier, apIBUSINESSPARTNERASupplierCompanyType.clearCustomerSupplier) &&
        Objects.equals(this.isToBeLocallyProcessed, apIBUSINESSPARTNERASupplierCompanyType.isToBeLocallyProcessed) &&
        Objects.equals(this.itemIsToBePaidSeparately, apIBUSINESSPARTNERASupplierCompanyType.itemIsToBePaidSeparately) &&
        Objects.equals(this.paymentIsToBeSentByEDI, apIBUSINESSPARTNERASupplierCompanyType.paymentIsToBeSentByEDI) &&
        Objects.equals(this.houseBank, apIBUSINESSPARTNERASupplierCompanyType.houseBank) &&
        Objects.equals(this.checkPaidDurationInDays, apIBUSINESSPARTNERASupplierCompanyType.checkPaidDurationInDays) &&
        Objects.equals(this.currency, apIBUSINESSPARTNERASupplierCompanyType.currency) &&
        Objects.equals(this.billOfExchLmtAmtInCoCodeCrcy, apIBUSINESSPARTNERASupplierCompanyType.billOfExchLmtAmtInCoCodeCrcy) &&
        Objects.equals(this.supplierClerkIDBySupplier, apIBUSINESSPARTNERASupplierCompanyType.supplierClerkIDBySupplier) &&
        Objects.equals(this.reconciliationAccount, apIBUSINESSPARTNERASupplierCompanyType.reconciliationAccount) &&
        Objects.equals(this.interestCalculationCode, apIBUSINESSPARTNERASupplierCompanyType.interestCalculationCode) &&
        Objects.equals(this.interestCalculationDate, apIBUSINESSPARTNERASupplierCompanyType.interestCalculationDate) &&
        Objects.equals(this.intrstCalcFrequencyInMonths, apIBUSINESSPARTNERASupplierCompanyType.intrstCalcFrequencyInMonths) &&
        Objects.equals(this.supplierHeadOffice, apIBUSINESSPARTNERASupplierCompanyType.supplierHeadOffice) &&
        Objects.equals(this.alternativePayee, apIBUSINESSPARTNERASupplierCompanyType.alternativePayee) &&
        Objects.equals(this.layoutSortingRule, apIBUSINESSPARTNERASupplierCompanyType.layoutSortingRule) &&
        Objects.equals(this.apARToleranceGroup, apIBUSINESSPARTNERASupplierCompanyType.apARToleranceGroup) &&
        Objects.equals(this.supplierCertificationDate, apIBUSINESSPARTNERASupplierCompanyType.supplierCertificationDate) &&
        Objects.equals(this.supplierAccountNote, apIBUSINESSPARTNERASupplierCompanyType.supplierAccountNote) &&
        Objects.equals(this.withholdingTaxCountry, apIBUSINESSPARTNERASupplierCompanyType.withholdingTaxCountry) &&
        Objects.equals(this.deletionIndicator, apIBUSINESSPARTNERASupplierCompanyType.deletionIndicator) &&
        Objects.equals(this.cashPlanningGroup, apIBUSINESSPARTNERASupplierCompanyType.cashPlanningGroup) &&
        Objects.equals(this.isToBeCheckedForDuplicates, apIBUSINESSPARTNERASupplierCompanyType.isToBeCheckedForDuplicates) &&
        Objects.equals(this.minorityGroup, apIBUSINESSPARTNERASupplierCompanyType.minorityGroup) &&
        Objects.equals(this.supplierAccountGroup, apIBUSINESSPARTNERASupplierCompanyType.supplierAccountGroup) &&
        Objects.equals(this.toCompanyText, apIBUSINESSPARTNERASupplierCompanyType.toCompanyText) &&
        Objects.equals(this.toSupplier, apIBUSINESSPARTNERASupplierCompanyType.toSupplier) &&
        Objects.equals(this.toSupplierDunning, apIBUSINESSPARTNERASupplierCompanyType.toSupplierDunning) &&
        Objects.equals(this.toSupplierWithHoldingTax, apIBUSINESSPARTNERASupplierCompanyType.toSupplierWithHoldingTax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplier, companyCode, authorizationGroup, companyCodeName, paymentBlockingReason, supplierIsBlockedForPosting, accountingClerk, accountingClerkFaxNumber, accountingClerkPhoneNumber, supplierClerk, supplierClerkURL, paymentMethodsList, paymentReason, paymentTerms, clearCustomerSupplier, isToBeLocallyProcessed, itemIsToBePaidSeparately, paymentIsToBeSentByEDI, houseBank, checkPaidDurationInDays, currency, billOfExchLmtAmtInCoCodeCrcy, supplierClerkIDBySupplier, reconciliationAccount, interestCalculationCode, interestCalculationDate, intrstCalcFrequencyInMonths, supplierHeadOffice, alternativePayee, layoutSortingRule, apARToleranceGroup, supplierCertificationDate, supplierAccountNote, withholdingTaxCountry, deletionIndicator, cashPlanningGroup, isToBeCheckedForDuplicates, minorityGroup, supplierAccountGroup, toCompanyText, toSupplier, toSupplierDunning, toSupplierWithHoldingTax);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERASupplierCompanyType {\n");
    
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("    companyCodeName: ").append(toIndentedString(companyCodeName)).append("\n");
    sb.append("    paymentBlockingReason: ").append(toIndentedString(paymentBlockingReason)).append("\n");
    sb.append("    supplierIsBlockedForPosting: ").append(toIndentedString(supplierIsBlockedForPosting)).append("\n");
    sb.append("    accountingClerk: ").append(toIndentedString(accountingClerk)).append("\n");
    sb.append("    accountingClerkFaxNumber: ").append(toIndentedString(accountingClerkFaxNumber)).append("\n");
    sb.append("    accountingClerkPhoneNumber: ").append(toIndentedString(accountingClerkPhoneNumber)).append("\n");
    sb.append("    supplierClerk: ").append(toIndentedString(supplierClerk)).append("\n");
    sb.append("    supplierClerkURL: ").append(toIndentedString(supplierClerkURL)).append("\n");
    sb.append("    paymentMethodsList: ").append(toIndentedString(paymentMethodsList)).append("\n");
    sb.append("    paymentReason: ").append(toIndentedString(paymentReason)).append("\n");
    sb.append("    paymentTerms: ").append(toIndentedString(paymentTerms)).append("\n");
    sb.append("    clearCustomerSupplier: ").append(toIndentedString(clearCustomerSupplier)).append("\n");
    sb.append("    isToBeLocallyProcessed: ").append(toIndentedString(isToBeLocallyProcessed)).append("\n");
    sb.append("    itemIsToBePaidSeparately: ").append(toIndentedString(itemIsToBePaidSeparately)).append("\n");
    sb.append("    paymentIsToBeSentByEDI: ").append(toIndentedString(paymentIsToBeSentByEDI)).append("\n");
    sb.append("    houseBank: ").append(toIndentedString(houseBank)).append("\n");
    sb.append("    checkPaidDurationInDays: ").append(toIndentedString(checkPaidDurationInDays)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    billOfExchLmtAmtInCoCodeCrcy: ").append(toIndentedString(billOfExchLmtAmtInCoCodeCrcy)).append("\n");
    sb.append("    supplierClerkIDBySupplier: ").append(toIndentedString(supplierClerkIDBySupplier)).append("\n");
    sb.append("    reconciliationAccount: ").append(toIndentedString(reconciliationAccount)).append("\n");
    sb.append("    interestCalculationCode: ").append(toIndentedString(interestCalculationCode)).append("\n");
    sb.append("    interestCalculationDate: ").append(toIndentedString(interestCalculationDate)).append("\n");
    sb.append("    intrstCalcFrequencyInMonths: ").append(toIndentedString(intrstCalcFrequencyInMonths)).append("\n");
    sb.append("    supplierHeadOffice: ").append(toIndentedString(supplierHeadOffice)).append("\n");
    sb.append("    alternativePayee: ").append(toIndentedString(alternativePayee)).append("\n");
    sb.append("    layoutSortingRule: ").append(toIndentedString(layoutSortingRule)).append("\n");
    sb.append("    apARToleranceGroup: ").append(toIndentedString(apARToleranceGroup)).append("\n");
    sb.append("    supplierCertificationDate: ").append(toIndentedString(supplierCertificationDate)).append("\n");
    sb.append("    supplierAccountNote: ").append(toIndentedString(supplierAccountNote)).append("\n");
    sb.append("    withholdingTaxCountry: ").append(toIndentedString(withholdingTaxCountry)).append("\n");
    sb.append("    deletionIndicator: ").append(toIndentedString(deletionIndicator)).append("\n");
    sb.append("    cashPlanningGroup: ").append(toIndentedString(cashPlanningGroup)).append("\n");
    sb.append("    isToBeCheckedForDuplicates: ").append(toIndentedString(isToBeCheckedForDuplicates)).append("\n");
    sb.append("    minorityGroup: ").append(toIndentedString(minorityGroup)).append("\n");
    sb.append("    supplierAccountGroup: ").append(toIndentedString(supplierAccountGroup)).append("\n");
    sb.append("    toCompanyText: ").append(toIndentedString(toCompanyText)).append("\n");
    sb.append("    toSupplier: ").append(toIndentedString(toSupplier)).append("\n");
    sb.append("    toSupplierDunning: ").append(toIndentedString(toSupplierDunning)).append("\n");
    sb.append("    toSupplierWithHoldingTax: ").append(toIndentedString(toSupplierWithHoldingTax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
