/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABPAddressIndependentWebsiteType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABPAddressIndependentWebsiteType {
  @JsonProperty("BusinessPartner")
  private String businessPartner = null;

  @JsonProperty("AddressID")
  private String addressID = null;

  @JsonProperty("Person")
  private String person = null;

  @JsonProperty("OrdinalNumber")
  private String ordinalNumber = null;

  @JsonProperty("IsDefaultURLAddress")
  private Boolean isDefaultURLAddress = null;

  @JsonProperty("URLFieldLength")
  private Integer urLFieldLength = null;

  @JsonProperty("WebsiteURL")
  private String websiteURL = null;

  public APIBUSINESSPARTNERABPAddressIndependentWebsiteType businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartner
  **/
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABPAddressIndependentWebsiteType addressID(String addressID) {
    this.addressID = addressID;
    return this;
  }

   /**
   * Get addressID
   * @return addressID
  **/
  public String getAddressID() {
    return addressID;
  }

  public void setAddressID(String addressID) {
    this.addressID = addressID;
  }

  public APIBUSINESSPARTNERABPAddressIndependentWebsiteType person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public APIBUSINESSPARTNERABPAddressIndependentWebsiteType ordinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
    return this;
  }

   /**
   * Get ordinalNumber
   * @return ordinalNumber
  **/
  public String getOrdinalNumber() {
    return ordinalNumber;
  }

  public void setOrdinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
  }

  public APIBUSINESSPARTNERABPAddressIndependentWebsiteType isDefaultURLAddress(Boolean isDefaultURLAddress) {
    this.isDefaultURLAddress = isDefaultURLAddress;
    return this;
  }

   /**
   * Flag: this address is the default address
   * @return isDefaultURLAddress
  **/
  public Boolean isIsDefaultURLAddress() {
    return isDefaultURLAddress;
  }

  public void setIsDefaultURLAddress(Boolean isDefaultURLAddress) {
    this.isDefaultURLAddress = isDefaultURLAddress;
  }

  public APIBUSINESSPARTNERABPAddressIndependentWebsiteType urLFieldLength(Integer urLFieldLength) {
    this.urLFieldLength = urLFieldLength;
    return this;
  }

   /**
   * Get urLFieldLength
   * @return urLFieldLength
  **/
  public Integer getUrLFieldLength() {
    return urLFieldLength;
  }

  public void setUrLFieldLength(Integer urLFieldLength) {
    this.urLFieldLength = urLFieldLength;
  }

  public APIBUSINESSPARTNERABPAddressIndependentWebsiteType websiteURL(String websiteURL) {
    this.websiteURL = websiteURL;
    return this;
  }

   /**
   * Get websiteURL
   * @return websiteURL
  **/
  public String getWebsiteURL() {
    return websiteURL;
  }

  public void setWebsiteURL(String websiteURL) {
    this.websiteURL = websiteURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABPAddressIndependentWebsiteType apIBUSINESSPARTNERABPAddressIndependentWebsiteType = (APIBUSINESSPARTNERABPAddressIndependentWebsiteType) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABPAddressIndependentWebsiteType.businessPartner) &&
        Objects.equals(this.addressID, apIBUSINESSPARTNERABPAddressIndependentWebsiteType.addressID) &&
        Objects.equals(this.person, apIBUSINESSPARTNERABPAddressIndependentWebsiteType.person) &&
        Objects.equals(this.ordinalNumber, apIBUSINESSPARTNERABPAddressIndependentWebsiteType.ordinalNumber) &&
        Objects.equals(this.isDefaultURLAddress, apIBUSINESSPARTNERABPAddressIndependentWebsiteType.isDefaultURLAddress) &&
        Objects.equals(this.urLFieldLength, apIBUSINESSPARTNERABPAddressIndependentWebsiteType.urLFieldLength) &&
        Objects.equals(this.websiteURL, apIBUSINESSPARTNERABPAddressIndependentWebsiteType.websiteURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, addressID, person, ordinalNumber, isDefaultURLAddress, urLFieldLength, websiteURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABPAddressIndependentWebsiteType {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    addressID: ").append(toIndentedString(addressID)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    ordinalNumber: ").append(toIndentedString(ordinalNumber)).append("\n");
    sb.append("    isDefaultURLAddress: ").append(toIndentedString(isDefaultURLAddress)).append("\n");
    sb.append("    urLFieldLength: ").append(toIndentedString(urLFieldLength)).append("\n");
    sb.append("    websiteURL: ").append(toIndentedString(websiteURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
