/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate {
  @JsonProperty("ValidFrom")
  private String validFrom = null;

  @JsonProperty("ValidTo")
  private String validTo = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  public APIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate validFrom(String validFrom) {
    this.validFrom = validFrom;
    return this;
  }

   /**
   * Validity Start of a BP Role
   * @return validFrom
  **/
  public String getValidFrom() {
    return validFrom;
  }

  public void setValidFrom(String validFrom) {
    this.validFrom = validFrom;
  }

  public APIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate validTo(String validTo) {
    this.validTo = validTo;
    return this;
  }

   /**
   * Validity End of a BP Role
   * @return validTo
  **/
  public String getValidTo() {
    return validTo;
  }

  public void setValidTo(String validTo) {
    this.validTo = validTo;
  }

  public APIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Get authorizationGroup
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate apIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate = (APIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate) o;
    return Objects.equals(this.validFrom, apIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate.validFrom) &&
        Objects.equals(this.validTo, apIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate.validTo) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate.authorizationGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validFrom, validTo, authorizationGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerRoleTypeUpdate {\n");
    
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
