/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate {
  @JsonProperty("BusinessPartnerIsVIP")
  private Boolean businessPartnerIsVIP = null;

  @JsonProperty("TradingPartner")
  private String tradingPartner = null;

  @JsonProperty("FactoryCalendar")
  private String factoryCalendar = null;

  @JsonProperty("BusinessPartnerOfficeCountry")
  private String businessPartnerOfficeCountry = null;

  @JsonProperty("BusinessPartnerOfficeRegion")
  private String businessPartnerOfficeRegion = null;

  @JsonProperty("BPRegisteredOfficeName")
  private String bpRegisteredOfficeName = null;

  @JsonProperty("BPBalanceSheetCurrency")
  private String bpBalanceSheetCurrency = null;

  @JsonProperty("BPLastCptlIncrAmtInBalShtCrcy")
  private String bpLastCptlIncrAmtInBalShtCrcy = null;

  @JsonProperty("BPLastCapitalIncreaseYear")
  private String bpLastCapitalIncreaseYear = null;

  @JsonProperty("BPBalanceSheetDisplayType")
  private String bpBalanceSheetDisplayType = null;

  @JsonProperty("BusinessPartnerCitizenship")
  private String businessPartnerCitizenship = null;

  @JsonProperty("BPMaritalPropertyRegime")
  private String bpMaritalPropertyRegime = null;

  @JsonProperty("BusinessPartnerIncomeCurrency")
  private String businessPartnerIncomeCurrency = null;

  @JsonProperty("BPNumberOfChildren")
  private String bpNumberOfChildren = null;

  @JsonProperty("BPNumberOfHouseholdMembers")
  private String bpNumberOfHouseholdMembers = null;

  @JsonProperty("BPAnnualNetIncAmtInIncomeCrcy")
  private String bpAnnualNetIncAmtInIncomeCrcy = null;

  @JsonProperty("BPMonthlyNetIncAmtInIncomeCrcy")
  private String bpMonthlyNetIncAmtInIncomeCrcy = null;

  @JsonProperty("BPAnnualNetIncomeYear")
  private String bpAnnualNetIncomeYear = null;

  @JsonProperty("BPMonthlyNetIncomeMonth")
  private String bpMonthlyNetIncomeMonth = null;

  @JsonProperty("BPMonthlyNetIncomeYear")
  private String bpMonthlyNetIncomeYear = null;

  @JsonProperty("BPPlaceOfDeathName")
  private String bpPlaceOfDeathName = null;

  @JsonProperty("CustomerIsUnwanted")
  private Boolean customerIsUnwanted = null;

  @JsonProperty("UndesirabilityReason")
  private String undesirabilityReason = null;

  @JsonProperty("UndesirabilityComment")
  private String undesirabilityComment = null;

  @JsonProperty("LastCustomerContactDate")
  private String lastCustomerContactDate = null;

  @JsonProperty("BPGroupingCharacter")
  private String bpGroupingCharacter = null;

  @JsonProperty("BPLetterSalutation")
  private String bpLetterSalutation = null;

  @JsonProperty("BusinessPartnerTargetGroup")
  private String businessPartnerTargetGroup = null;

  @JsonProperty("BusinessPartnerEmployeeGroup")
  private String businessPartnerEmployeeGroup = null;

  @JsonProperty("BusinessPartnerIsEmployee")
  private Boolean businessPartnerIsEmployee = null;

  @JsonProperty("BPTermnBusRelationsBankDate")
  private String bpTermnBusRelationsBankDate = null;

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate businessPartnerIsVIP(Boolean businessPartnerIsVIP) {
    this.businessPartnerIsVIP = businessPartnerIsVIP;
    return this;
  }

   /**
   * Business Partner Is VIP
   * @return businessPartnerIsVIP
  **/
  public Boolean isBusinessPartnerIsVIP() {
    return businessPartnerIsVIP;
  }

  public void setBusinessPartnerIsVIP(Boolean businessPartnerIsVIP) {
    this.businessPartnerIsVIP = businessPartnerIsVIP;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate tradingPartner(String tradingPartner) {
    this.tradingPartner = tradingPartner;
    return this;
  }

   /**
   * Company ID of Trading Partner
   * @return tradingPartner
  **/
  public String getTradingPartner() {
    return tradingPartner;
  }

  public void setTradingPartner(String tradingPartner) {
    this.tradingPartner = tradingPartner;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate factoryCalendar(String factoryCalendar) {
    this.factoryCalendar = factoryCalendar;
    return this;
  }

   /**
   * Get factoryCalendar
   * @return factoryCalendar
  **/
  public String getFactoryCalendar() {
    return factoryCalendar;
  }

  public void setFactoryCalendar(String factoryCalendar) {
    this.factoryCalendar = factoryCalendar;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate businessPartnerOfficeCountry(String businessPartnerOfficeCountry) {
    this.businessPartnerOfficeCountry = businessPartnerOfficeCountry;
    return this;
  }

   /**
   * Country/Region of Registered Office
   * @return businessPartnerOfficeCountry
  **/
  public String getBusinessPartnerOfficeCountry() {
    return businessPartnerOfficeCountry;
  }

  public void setBusinessPartnerOfficeCountry(String businessPartnerOfficeCountry) {
    this.businessPartnerOfficeCountry = businessPartnerOfficeCountry;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate businessPartnerOfficeRegion(String businessPartnerOfficeRegion) {
    this.businessPartnerOfficeRegion = businessPartnerOfficeRegion;
    return this;
  }

   /**
   * Region of Registered Office
   * @return businessPartnerOfficeRegion
  **/
  public String getBusinessPartnerOfficeRegion() {
    return businessPartnerOfficeRegion;
  }

  public void setBusinessPartnerOfficeRegion(String businessPartnerOfficeRegion) {
    this.businessPartnerOfficeRegion = businessPartnerOfficeRegion;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpRegisteredOfficeName(String bpRegisteredOfficeName) {
    this.bpRegisteredOfficeName = bpRegisteredOfficeName;
    return this;
  }

   /**
   * Get bpRegisteredOfficeName
   * @return bpRegisteredOfficeName
  **/
  public String getBpRegisteredOfficeName() {
    return bpRegisteredOfficeName;
  }

  public void setBpRegisteredOfficeName(String bpRegisteredOfficeName) {
    this.bpRegisteredOfficeName = bpRegisteredOfficeName;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpBalanceSheetCurrency(String bpBalanceSheetCurrency) {
    this.bpBalanceSheetCurrency = bpBalanceSheetCurrency;
    return this;
  }

   /**
   * Balance Sheet Currency
   * @return bpBalanceSheetCurrency
  **/
  public String getBpBalanceSheetCurrency() {
    return bpBalanceSheetCurrency;
  }

  public void setBpBalanceSheetCurrency(String bpBalanceSheetCurrency) {
    this.bpBalanceSheetCurrency = bpBalanceSheetCurrency;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpLastCptlIncrAmtInBalShtCrcy(String bpLastCptlIncrAmtInBalShtCrcy) {
    this.bpLastCptlIncrAmtInBalShtCrcy = bpLastCptlIncrAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of last capital increase
   * @return bpLastCptlIncrAmtInBalShtCrcy
  **/
  public String getBpLastCptlIncrAmtInBalShtCrcy() {
    return bpLastCptlIncrAmtInBalShtCrcy;
  }

  public void setBpLastCptlIncrAmtInBalShtCrcy(String bpLastCptlIncrAmtInBalShtCrcy) {
    this.bpLastCptlIncrAmtInBalShtCrcy = bpLastCptlIncrAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpLastCapitalIncreaseYear(String bpLastCapitalIncreaseYear) {
    this.bpLastCapitalIncreaseYear = bpLastCapitalIncreaseYear;
    return this;
  }

   /**
   * Year of Last Capital Increase
   * @return bpLastCapitalIncreaseYear
  **/
  public String getBpLastCapitalIncreaseYear() {
    return bpLastCapitalIncreaseYear;
  }

  public void setBpLastCapitalIncreaseYear(String bpLastCapitalIncreaseYear) {
    this.bpLastCapitalIncreaseYear = bpLastCapitalIncreaseYear;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpBalanceSheetDisplayType(String bpBalanceSheetDisplayType) {
    this.bpBalanceSheetDisplayType = bpBalanceSheetDisplayType;
    return this;
  }

   /**
   * Balance Sheet Display
   * @return bpBalanceSheetDisplayType
  **/
  public String getBpBalanceSheetDisplayType() {
    return bpBalanceSheetDisplayType;
  }

  public void setBpBalanceSheetDisplayType(String bpBalanceSheetDisplayType) {
    this.bpBalanceSheetDisplayType = bpBalanceSheetDisplayType;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate businessPartnerCitizenship(String businessPartnerCitizenship) {
    this.businessPartnerCitizenship = businessPartnerCitizenship;
    return this;
  }

   /**
   * Get businessPartnerCitizenship
   * @return businessPartnerCitizenship
  **/
  public String getBusinessPartnerCitizenship() {
    return businessPartnerCitizenship;
  }

  public void setBusinessPartnerCitizenship(String businessPartnerCitizenship) {
    this.businessPartnerCitizenship = businessPartnerCitizenship;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpMaritalPropertyRegime(String bpMaritalPropertyRegime) {
    this.bpMaritalPropertyRegime = bpMaritalPropertyRegime;
    return this;
  }

   /**
   * Marital property regime
   * @return bpMaritalPropertyRegime
  **/
  public String getBpMaritalPropertyRegime() {
    return bpMaritalPropertyRegime;
  }

  public void setBpMaritalPropertyRegime(String bpMaritalPropertyRegime) {
    this.bpMaritalPropertyRegime = bpMaritalPropertyRegime;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate businessPartnerIncomeCurrency(String businessPartnerIncomeCurrency) {
    this.businessPartnerIncomeCurrency = businessPartnerIncomeCurrency;
    return this;
  }

   /**
   * Currency of Net Income
   * @return businessPartnerIncomeCurrency
  **/
  public String getBusinessPartnerIncomeCurrency() {
    return businessPartnerIncomeCurrency;
  }

  public void setBusinessPartnerIncomeCurrency(String businessPartnerIncomeCurrency) {
    this.businessPartnerIncomeCurrency = businessPartnerIncomeCurrency;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpNumberOfChildren(String bpNumberOfChildren) {
    this.bpNumberOfChildren = bpNumberOfChildren;
    return this;
  }

   /**
   * Number of Children Belonging to the Business Partner
   * @return bpNumberOfChildren
  **/
  public String getBpNumberOfChildren() {
    return bpNumberOfChildren;
  }

  public void setBpNumberOfChildren(String bpNumberOfChildren) {
    this.bpNumberOfChildren = bpNumberOfChildren;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpNumberOfHouseholdMembers(String bpNumberOfHouseholdMembers) {
    this.bpNumberOfHouseholdMembers = bpNumberOfHouseholdMembers;
    return this;
  }

   /**
   * Number of People Living in the Household
   * @return bpNumberOfHouseholdMembers
  **/
  public String getBpNumberOfHouseholdMembers() {
    return bpNumberOfHouseholdMembers;
  }

  public void setBpNumberOfHouseholdMembers(String bpNumberOfHouseholdMembers) {
    this.bpNumberOfHouseholdMembers = bpNumberOfHouseholdMembers;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpAnnualNetIncAmtInIncomeCrcy(String bpAnnualNetIncAmtInIncomeCrcy) {
    this.bpAnnualNetIncAmtInIncomeCrcy = bpAnnualNetIncAmtInIncomeCrcy;
    return this;
  }

   /**
   * Get bpAnnualNetIncAmtInIncomeCrcy
   * @return bpAnnualNetIncAmtInIncomeCrcy
  **/
  public String getBpAnnualNetIncAmtInIncomeCrcy() {
    return bpAnnualNetIncAmtInIncomeCrcy;
  }

  public void setBpAnnualNetIncAmtInIncomeCrcy(String bpAnnualNetIncAmtInIncomeCrcy) {
    this.bpAnnualNetIncAmtInIncomeCrcy = bpAnnualNetIncAmtInIncomeCrcy;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpMonthlyNetIncAmtInIncomeCrcy(String bpMonthlyNetIncAmtInIncomeCrcy) {
    this.bpMonthlyNetIncAmtInIncomeCrcy = bpMonthlyNetIncAmtInIncomeCrcy;
    return this;
  }

   /**
   * Monthly Net Income of Business Partner
   * @return bpMonthlyNetIncAmtInIncomeCrcy
  **/
  public String getBpMonthlyNetIncAmtInIncomeCrcy() {
    return bpMonthlyNetIncAmtInIncomeCrcy;
  }

  public void setBpMonthlyNetIncAmtInIncomeCrcy(String bpMonthlyNetIncAmtInIncomeCrcy) {
    this.bpMonthlyNetIncAmtInIncomeCrcy = bpMonthlyNetIncAmtInIncomeCrcy;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpAnnualNetIncomeYear(String bpAnnualNetIncomeYear) {
    this.bpAnnualNetIncomeYear = bpAnnualNetIncomeYear;
    return this;
  }

   /**
   * Year of Net Annual Income
   * @return bpAnnualNetIncomeYear
  **/
  public String getBpAnnualNetIncomeYear() {
    return bpAnnualNetIncomeYear;
  }

  public void setBpAnnualNetIncomeYear(String bpAnnualNetIncomeYear) {
    this.bpAnnualNetIncomeYear = bpAnnualNetIncomeYear;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpMonthlyNetIncomeMonth(String bpMonthlyNetIncomeMonth) {
    this.bpMonthlyNetIncomeMonth = bpMonthlyNetIncomeMonth;
    return this;
  }

   /**
   * Calendar Month of Monthly Net Income
   * @return bpMonthlyNetIncomeMonth
  **/
  public String getBpMonthlyNetIncomeMonth() {
    return bpMonthlyNetIncomeMonth;
  }

  public void setBpMonthlyNetIncomeMonth(String bpMonthlyNetIncomeMonth) {
    this.bpMonthlyNetIncomeMonth = bpMonthlyNetIncomeMonth;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpMonthlyNetIncomeYear(String bpMonthlyNetIncomeYear) {
    this.bpMonthlyNetIncomeYear = bpMonthlyNetIncomeYear;
    return this;
  }

   /**
   * Year of Monthly Net Income
   * @return bpMonthlyNetIncomeYear
  **/
  public String getBpMonthlyNetIncomeYear() {
    return bpMonthlyNetIncomeYear;
  }

  public void setBpMonthlyNetIncomeYear(String bpMonthlyNetIncomeYear) {
    this.bpMonthlyNetIncomeYear = bpMonthlyNetIncomeYear;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpPlaceOfDeathName(String bpPlaceOfDeathName) {
    this.bpPlaceOfDeathName = bpPlaceOfDeathName;
    return this;
  }

   /**
   * Name of Place of Death of Natural Person
   * @return bpPlaceOfDeathName
  **/
  public String getBpPlaceOfDeathName() {
    return bpPlaceOfDeathName;
  }

  public void setBpPlaceOfDeathName(String bpPlaceOfDeathName) {
    this.bpPlaceOfDeathName = bpPlaceOfDeathName;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate customerIsUnwanted(Boolean customerIsUnwanted) {
    this.customerIsUnwanted = customerIsUnwanted;
    return this;
  }

   /**
   * Get customerIsUnwanted
   * @return customerIsUnwanted
  **/
  public Boolean isCustomerIsUnwanted() {
    return customerIsUnwanted;
  }

  public void setCustomerIsUnwanted(Boolean customerIsUnwanted) {
    this.customerIsUnwanted = customerIsUnwanted;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate undesirabilityReason(String undesirabilityReason) {
    this.undesirabilityReason = undesirabilityReason;
    return this;
  }

   /**
   * Reason for Undesirability
   * @return undesirabilityReason
  **/
  public String getUndesirabilityReason() {
    return undesirabilityReason;
  }

  public void setUndesirabilityReason(String undesirabilityReason) {
    this.undesirabilityReason = undesirabilityReason;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate undesirabilityComment(String undesirabilityComment) {
    this.undesirabilityComment = undesirabilityComment;
    return this;
  }

   /**
   * Comment on Undesirability
   * @return undesirabilityComment
  **/
  public String getUndesirabilityComment() {
    return undesirabilityComment;
  }

  public void setUndesirabilityComment(String undesirabilityComment) {
    this.undesirabilityComment = undesirabilityComment;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate lastCustomerContactDate(String lastCustomerContactDate) {
    this.lastCustomerContactDate = lastCustomerContactDate;
    return this;
  }

   /**
   * Date of Last Customer Contact
   * @return lastCustomerContactDate
  **/
  public String getLastCustomerContactDate() {
    return lastCustomerContactDate;
  }

  public void setLastCustomerContactDate(String lastCustomerContactDate) {
    this.lastCustomerContactDate = lastCustomerContactDate;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpGroupingCharacter(String bpGroupingCharacter) {
    this.bpGroupingCharacter = bpGroupingCharacter;
    return this;
  }

   /**
   * Grouping Character
   * @return bpGroupingCharacter
  **/
  public String getBpGroupingCharacter() {
    return bpGroupingCharacter;
  }

  public void setBpGroupingCharacter(String bpGroupingCharacter) {
    this.bpGroupingCharacter = bpGroupingCharacter;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpLetterSalutation(String bpLetterSalutation) {
    this.bpLetterSalutation = bpLetterSalutation;
    return this;
  }

   /**
   * Get bpLetterSalutation
   * @return bpLetterSalutation
  **/
  public String getBpLetterSalutation() {
    return bpLetterSalutation;
  }

  public void setBpLetterSalutation(String bpLetterSalutation) {
    this.bpLetterSalutation = bpLetterSalutation;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate businessPartnerTargetGroup(String businessPartnerTargetGroup) {
    this.businessPartnerTargetGroup = businessPartnerTargetGroup;
    return this;
  }

   /**
   * Get businessPartnerTargetGroup
   * @return businessPartnerTargetGroup
  **/
  public String getBusinessPartnerTargetGroup() {
    return businessPartnerTargetGroup;
  }

  public void setBusinessPartnerTargetGroup(String businessPartnerTargetGroup) {
    this.businessPartnerTargetGroup = businessPartnerTargetGroup;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate businessPartnerEmployeeGroup(String businessPartnerEmployeeGroup) {
    this.businessPartnerEmployeeGroup = businessPartnerEmployeeGroup;
    return this;
  }

   /**
   * Get businessPartnerEmployeeGroup
   * @return businessPartnerEmployeeGroup
  **/
  public String getBusinessPartnerEmployeeGroup() {
    return businessPartnerEmployeeGroup;
  }

  public void setBusinessPartnerEmployeeGroup(String businessPartnerEmployeeGroup) {
    this.businessPartnerEmployeeGroup = businessPartnerEmployeeGroup;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate businessPartnerIsEmployee(Boolean businessPartnerIsEmployee) {
    this.businessPartnerIsEmployee = businessPartnerIsEmployee;
    return this;
  }

   /**
   * Get businessPartnerIsEmployee
   * @return businessPartnerIsEmployee
  **/
  public Boolean isBusinessPartnerIsEmployee() {
    return businessPartnerIsEmployee;
  }

  public void setBusinessPartnerIsEmployee(Boolean businessPartnerIsEmployee) {
    this.businessPartnerIsEmployee = businessPartnerIsEmployee;
  }

  public APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate bpTermnBusRelationsBankDate(String bpTermnBusRelationsBankDate) {
    this.bpTermnBusRelationsBankDate = bpTermnBusRelationsBankDate;
    return this;
  }

   /**
   * Termination Date for Business Relations with the Bank
   * @return bpTermnBusRelationsBankDate
  **/
  public String getBpTermnBusRelationsBankDate() {
    return bpTermnBusRelationsBankDate;
  }

  public void setBpTermnBusRelationsBankDate(String bpTermnBusRelationsBankDate) {
    this.bpTermnBusRelationsBankDate = bpTermnBusRelationsBankDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate = (APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate) o;
    return Objects.equals(this.businessPartnerIsVIP, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.businessPartnerIsVIP) &&
        Objects.equals(this.tradingPartner, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.tradingPartner) &&
        Objects.equals(this.factoryCalendar, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.factoryCalendar) &&
        Objects.equals(this.businessPartnerOfficeCountry, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.businessPartnerOfficeCountry) &&
        Objects.equals(this.businessPartnerOfficeRegion, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.businessPartnerOfficeRegion) &&
        Objects.equals(this.bpRegisteredOfficeName, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpRegisteredOfficeName) &&
        Objects.equals(this.bpBalanceSheetCurrency, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpBalanceSheetCurrency) &&
        Objects.equals(this.bpLastCptlIncrAmtInBalShtCrcy, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpLastCptlIncrAmtInBalShtCrcy) &&
        Objects.equals(this.bpLastCapitalIncreaseYear, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpLastCapitalIncreaseYear) &&
        Objects.equals(this.bpBalanceSheetDisplayType, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpBalanceSheetDisplayType) &&
        Objects.equals(this.businessPartnerCitizenship, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.businessPartnerCitizenship) &&
        Objects.equals(this.bpMaritalPropertyRegime, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpMaritalPropertyRegime) &&
        Objects.equals(this.businessPartnerIncomeCurrency, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.businessPartnerIncomeCurrency) &&
        Objects.equals(this.bpNumberOfChildren, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpNumberOfChildren) &&
        Objects.equals(this.bpNumberOfHouseholdMembers, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpNumberOfHouseholdMembers) &&
        Objects.equals(this.bpAnnualNetIncAmtInIncomeCrcy, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpAnnualNetIncAmtInIncomeCrcy) &&
        Objects.equals(this.bpMonthlyNetIncAmtInIncomeCrcy, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpMonthlyNetIncAmtInIncomeCrcy) &&
        Objects.equals(this.bpAnnualNetIncomeYear, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpAnnualNetIncomeYear) &&
        Objects.equals(this.bpMonthlyNetIncomeMonth, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpMonthlyNetIncomeMonth) &&
        Objects.equals(this.bpMonthlyNetIncomeYear, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpMonthlyNetIncomeYear) &&
        Objects.equals(this.bpPlaceOfDeathName, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpPlaceOfDeathName) &&
        Objects.equals(this.customerIsUnwanted, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.customerIsUnwanted) &&
        Objects.equals(this.undesirabilityReason, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.undesirabilityReason) &&
        Objects.equals(this.undesirabilityComment, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.undesirabilityComment) &&
        Objects.equals(this.lastCustomerContactDate, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.lastCustomerContactDate) &&
        Objects.equals(this.bpGroupingCharacter, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpGroupingCharacter) &&
        Objects.equals(this.bpLetterSalutation, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpLetterSalutation) &&
        Objects.equals(this.businessPartnerTargetGroup, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.businessPartnerTargetGroup) &&
        Objects.equals(this.businessPartnerEmployeeGroup, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.businessPartnerEmployeeGroup) &&
        Objects.equals(this.businessPartnerIsEmployee, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.businessPartnerIsEmployee) &&
        Objects.equals(this.bpTermnBusRelationsBankDate, apIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate.bpTermnBusRelationsBankDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartnerIsVIP, tradingPartner, factoryCalendar, businessPartnerOfficeCountry, businessPartnerOfficeRegion, bpRegisteredOfficeName, bpBalanceSheetCurrency, bpLastCptlIncrAmtInBalShtCrcy, bpLastCapitalIncreaseYear, bpBalanceSheetDisplayType, businessPartnerCitizenship, bpMaritalPropertyRegime, businessPartnerIncomeCurrency, bpNumberOfChildren, bpNumberOfHouseholdMembers, bpAnnualNetIncAmtInIncomeCrcy, bpMonthlyNetIncAmtInIncomeCrcy, bpAnnualNetIncomeYear, bpMonthlyNetIncomeMonth, bpMonthlyNetIncomeYear, bpPlaceOfDeathName, customerIsUnwanted, undesirabilityReason, undesirabilityComment, lastCustomerContactDate, bpGroupingCharacter, bpLetterSalutation, businessPartnerTargetGroup, businessPartnerEmployeeGroup, businessPartnerIsEmployee, bpTermnBusRelationsBankDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABPFinancialServicesExtnTypeUpdate {\n");
    
    sb.append("    businessPartnerIsVIP: ").append(toIndentedString(businessPartnerIsVIP)).append("\n");
    sb.append("    tradingPartner: ").append(toIndentedString(tradingPartner)).append("\n");
    sb.append("    factoryCalendar: ").append(toIndentedString(factoryCalendar)).append("\n");
    sb.append("    businessPartnerOfficeCountry: ").append(toIndentedString(businessPartnerOfficeCountry)).append("\n");
    sb.append("    businessPartnerOfficeRegion: ").append(toIndentedString(businessPartnerOfficeRegion)).append("\n");
    sb.append("    bpRegisteredOfficeName: ").append(toIndentedString(bpRegisteredOfficeName)).append("\n");
    sb.append("    bpBalanceSheetCurrency: ").append(toIndentedString(bpBalanceSheetCurrency)).append("\n");
    sb.append("    bpLastCptlIncrAmtInBalShtCrcy: ").append(toIndentedString(bpLastCptlIncrAmtInBalShtCrcy)).append("\n");
    sb.append("    bpLastCapitalIncreaseYear: ").append(toIndentedString(bpLastCapitalIncreaseYear)).append("\n");
    sb.append("    bpBalanceSheetDisplayType: ").append(toIndentedString(bpBalanceSheetDisplayType)).append("\n");
    sb.append("    businessPartnerCitizenship: ").append(toIndentedString(businessPartnerCitizenship)).append("\n");
    sb.append("    bpMaritalPropertyRegime: ").append(toIndentedString(bpMaritalPropertyRegime)).append("\n");
    sb.append("    businessPartnerIncomeCurrency: ").append(toIndentedString(businessPartnerIncomeCurrency)).append("\n");
    sb.append("    bpNumberOfChildren: ").append(toIndentedString(bpNumberOfChildren)).append("\n");
    sb.append("    bpNumberOfHouseholdMembers: ").append(toIndentedString(bpNumberOfHouseholdMembers)).append("\n");
    sb.append("    bpAnnualNetIncAmtInIncomeCrcy: ").append(toIndentedString(bpAnnualNetIncAmtInIncomeCrcy)).append("\n");
    sb.append("    bpMonthlyNetIncAmtInIncomeCrcy: ").append(toIndentedString(bpMonthlyNetIncAmtInIncomeCrcy)).append("\n");
    sb.append("    bpAnnualNetIncomeYear: ").append(toIndentedString(bpAnnualNetIncomeYear)).append("\n");
    sb.append("    bpMonthlyNetIncomeMonth: ").append(toIndentedString(bpMonthlyNetIncomeMonth)).append("\n");
    sb.append("    bpMonthlyNetIncomeYear: ").append(toIndentedString(bpMonthlyNetIncomeYear)).append("\n");
    sb.append("    bpPlaceOfDeathName: ").append(toIndentedString(bpPlaceOfDeathName)).append("\n");
    sb.append("    customerIsUnwanted: ").append(toIndentedString(customerIsUnwanted)).append("\n");
    sb.append("    undesirabilityReason: ").append(toIndentedString(undesirabilityReason)).append("\n");
    sb.append("    undesirabilityComment: ").append(toIndentedString(undesirabilityComment)).append("\n");
    sb.append("    lastCustomerContactDate: ").append(toIndentedString(lastCustomerContactDate)).append("\n");
    sb.append("    bpGroupingCharacter: ").append(toIndentedString(bpGroupingCharacter)).append("\n");
    sb.append("    bpLetterSalutation: ").append(toIndentedString(bpLetterSalutation)).append("\n");
    sb.append("    businessPartnerTargetGroup: ").append(toIndentedString(businessPartnerTargetGroup)).append("\n");
    sb.append("    businessPartnerEmployeeGroup: ").append(toIndentedString(businessPartnerEmployeeGroup)).append("\n");
    sb.append("    businessPartnerIsEmployee: ").append(toIndentedString(businessPartnerIsEmployee)).append("\n");
    sb.append("    bpTermnBusRelationsBankDate: ").append(toIndentedString(bpTermnBusRelationsBankDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
