/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.UUID;
/**
 * APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate {
  @JsonProperty("AutomaticEvaluatedRcptSettlmt")
  private Boolean automaticEvaluatedRcptSettlmt = null;

  @JsonProperty("CalculationSchemaGroupCode")
  private String calculationSchemaGroupCode = null;

  @JsonProperty("DeletionIndicator")
  private Boolean deletionIndicator = null;

  @JsonProperty("EvaldReceiptSettlementIsActive")
  private Boolean evaldReceiptSettlementIsActive = null;

  @JsonProperty("IncotermsClassification")
  private String incotermsClassification = null;

  @JsonProperty("IncotermsTransferLocation")
  private String incotermsTransferLocation = null;

  @JsonProperty("IncotermsVersion")
  private String incotermsVersion = null;

  @JsonProperty("IncotermsLocation1")
  private String incotermsLocation1 = null;

  @JsonProperty("IncotermsLocation2")
  private String incotermsLocation2 = null;

  @JsonProperty("IncotermsSupChnLoc1AddlUUID")
  private UUID incotermsSupChnLoc1AddlUUID = null;

  @JsonProperty("IncotermsSupChnLoc2AddlUUID")
  private UUID incotermsSupChnLoc2AddlUUID = null;

  @JsonProperty("IncotermsSupChnDvtgLocAddlUUID")
  private UUID incotermsSupChnDvtgLocAddlUUID = null;

  @JsonProperty("IntrastatCrsBorderTrMode")
  private String intrastatCrsBorderTrMode = null;

  @JsonProperty("InvoiceIsGoodsReceiptBased")
  private Boolean invoiceIsGoodsReceiptBased = null;

  @JsonProperty("InvoiceIsMMServiceEntryBased")
  private Boolean invoiceIsMMServiceEntryBased = null;

  @JsonProperty("MaterialPlannedDeliveryDurn")
  private String materialPlannedDeliveryDurn = null;

  @JsonProperty("MinimumOrderAmount")
  private String minimumOrderAmount = null;

  @JsonProperty("PaymentTerms")
  private String paymentTerms = null;

  @JsonProperty("PlanningCycle")
  private String planningCycle = null;

  @JsonProperty("PricingDateControl")
  private String pricingDateControl = null;

  @JsonProperty("ProdStockAndSlsDataTransfPrfl")
  private String prodStockAndSlsDataTransfPrfl = null;

  @JsonProperty("ProductUnitGroup")
  private String productUnitGroup = null;

  @JsonProperty("PurOrdAutoGenerationIsAllowed")
  private Boolean purOrdAutoGenerationIsAllowed = null;

  @JsonProperty("PurchaseOrderCurrency")
  private String purchaseOrderCurrency = null;

  @JsonProperty("PurchasingGroup")
  private String purchasingGroup = null;

  @JsonProperty("PurchasingIsBlockedForSupplier")
  private Boolean purchasingIsBlockedForSupplier = null;

  @JsonProperty("RoundingProfile")
  private String roundingProfile = null;

  @JsonProperty("ShippingCondition")
  private String shippingCondition = null;

  @JsonProperty("SuplrDiscountInKindIsGranted")
  private Boolean suplrDiscountInKindIsGranted = null;

  @JsonProperty("SuplrInvcRevalIsAllowed")
  private Boolean suplrInvcRevalIsAllowed = null;

  @JsonProperty("SuplrIsRlvtForSettlmtMgmt")
  private Boolean suplrIsRlvtForSettlmtMgmt = null;

  @JsonProperty("SuplrPurgOrgIsRlvtForPriceDetn")
  private Boolean suplrPurgOrgIsRlvtForPriceDetn = null;

  @JsonProperty("SupplierABCClassificationCode")
  private String supplierABCClassificationCode = null;

  @JsonProperty("SupplierAccountNumber")
  private String supplierAccountNumber = null;

  @JsonProperty("SupplierIsReturnsSupplier")
  private Boolean supplierIsReturnsSupplier = null;

  @JsonProperty("SupplierPhoneNumber")
  private String supplierPhoneNumber = null;

  @JsonProperty("SupplierRespSalesPersonName")
  private String supplierRespSalesPersonName = null;

  @JsonProperty("SupplierConfirmationControlKey")
  private String supplierConfirmationControlKey = null;

  @JsonProperty("IsOrderAcknRqd")
  private Boolean isOrderAcknRqd = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  @JsonProperty("SupplierAccountGroup")
  private String supplierAccountGroup = null;

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate automaticEvaluatedRcptSettlmt(Boolean automaticEvaluatedRcptSettlmt) {
    this.automaticEvaluatedRcptSettlmt = automaticEvaluatedRcptSettlmt;
    return this;
  }

   /**
   * Automatic evaluated receipt settlement for return items
   * @return automaticEvaluatedRcptSettlmt
  **/
  public Boolean isAutomaticEvaluatedRcptSettlmt() {
    return automaticEvaluatedRcptSettlmt;
  }

  public void setAutomaticEvaluatedRcptSettlmt(Boolean automaticEvaluatedRcptSettlmt) {
    this.automaticEvaluatedRcptSettlmt = automaticEvaluatedRcptSettlmt;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate calculationSchemaGroupCode(String calculationSchemaGroupCode) {
    this.calculationSchemaGroupCode = calculationSchemaGroupCode;
    return this;
  }

   /**
   * Group for Calculation Schema (Supplier)
   * @return calculationSchemaGroupCode
  **/
  public String getCalculationSchemaGroupCode() {
    return calculationSchemaGroupCode;
  }

  public void setCalculationSchemaGroupCode(String calculationSchemaGroupCode) {
    this.calculationSchemaGroupCode = calculationSchemaGroupCode;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate deletionIndicator(Boolean deletionIndicator) {
    this.deletionIndicator = deletionIndicator;
    return this;
  }

   /**
   * Deletion Indicator for Supplier at Purchasing Level
   * @return deletionIndicator
  **/
  public Boolean isDeletionIndicator() {
    return deletionIndicator;
  }

  public void setDeletionIndicator(Boolean deletionIndicator) {
    this.deletionIndicator = deletionIndicator;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate evaldReceiptSettlementIsActive(Boolean evaldReceiptSettlementIsActive) {
    this.evaldReceiptSettlementIsActive = evaldReceiptSettlementIsActive;
    return this;
  }

   /**
   * Evaluated Receipt Settlement (ERS)
   * @return evaldReceiptSettlementIsActive
  **/
  public Boolean isEvaldReceiptSettlementIsActive() {
    return evaldReceiptSettlementIsActive;
  }

  public void setEvaldReceiptSettlementIsActive(Boolean evaldReceiptSettlementIsActive) {
    this.evaldReceiptSettlementIsActive = evaldReceiptSettlementIsActive;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate incotermsClassification(String incotermsClassification) {
    this.incotermsClassification = incotermsClassification;
    return this;
  }

   /**
   * Incoterms (Part 1)
   * @return incotermsClassification
  **/
  public String getIncotermsClassification() {
    return incotermsClassification;
  }

  public void setIncotermsClassification(String incotermsClassification) {
    this.incotermsClassification = incotermsClassification;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate incotermsTransferLocation(String incotermsTransferLocation) {
    this.incotermsTransferLocation = incotermsTransferLocation;
    return this;
  }

   /**
   * Get incotermsTransferLocation
   * @return incotermsTransferLocation
  **/
  public String getIncotermsTransferLocation() {
    return incotermsTransferLocation;
  }

  public void setIncotermsTransferLocation(String incotermsTransferLocation) {
    this.incotermsTransferLocation = incotermsTransferLocation;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate incotermsVersion(String incotermsVersion) {
    this.incotermsVersion = incotermsVersion;
    return this;
  }

   /**
   * Get incotermsVersion
   * @return incotermsVersion
  **/
  public String getIncotermsVersion() {
    return incotermsVersion;
  }

  public void setIncotermsVersion(String incotermsVersion) {
    this.incotermsVersion = incotermsVersion;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate incotermsLocation1(String incotermsLocation1) {
    this.incotermsLocation1 = incotermsLocation1;
    return this;
  }

   /**
   * Get incotermsLocation1
   * @return incotermsLocation1
  **/
  public String getIncotermsLocation1() {
    return incotermsLocation1;
  }

  public void setIncotermsLocation1(String incotermsLocation1) {
    this.incotermsLocation1 = incotermsLocation1;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate incotermsLocation2(String incotermsLocation2) {
    this.incotermsLocation2 = incotermsLocation2;
    return this;
  }

   /**
   * Get incotermsLocation2
   * @return incotermsLocation2
  **/
  public String getIncotermsLocation2() {
    return incotermsLocation2;
  }

  public void setIncotermsLocation2(String incotermsLocation2) {
    this.incotermsLocation2 = incotermsLocation2;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate incotermsSupChnLoc1AddlUUID(UUID incotermsSupChnLoc1AddlUUID) {
    this.incotermsSupChnLoc1AddlUUID = incotermsSupChnLoc1AddlUUID;
    return this;
  }

   /**
   * Get incotermsSupChnLoc1AddlUUID
   * @return incotermsSupChnLoc1AddlUUID
  **/
  public UUID getIncotermsSupChnLoc1AddlUUID() {
    return incotermsSupChnLoc1AddlUUID;
  }

  public void setIncotermsSupChnLoc1AddlUUID(UUID incotermsSupChnLoc1AddlUUID) {
    this.incotermsSupChnLoc1AddlUUID = incotermsSupChnLoc1AddlUUID;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate incotermsSupChnLoc2AddlUUID(UUID incotermsSupChnLoc2AddlUUID) {
    this.incotermsSupChnLoc2AddlUUID = incotermsSupChnLoc2AddlUUID;
    return this;
  }

   /**
   * Get incotermsSupChnLoc2AddlUUID
   * @return incotermsSupChnLoc2AddlUUID
  **/
  public UUID getIncotermsSupChnLoc2AddlUUID() {
    return incotermsSupChnLoc2AddlUUID;
  }

  public void setIncotermsSupChnLoc2AddlUUID(UUID incotermsSupChnLoc2AddlUUID) {
    this.incotermsSupChnLoc2AddlUUID = incotermsSupChnLoc2AddlUUID;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate incotermsSupChnDvtgLocAddlUUID(UUID incotermsSupChnDvtgLocAddlUUID) {
    this.incotermsSupChnDvtgLocAddlUUID = incotermsSupChnDvtgLocAddlUUID;
    return this;
  }

   /**
   * Get incotermsSupChnDvtgLocAddlUUID
   * @return incotermsSupChnDvtgLocAddlUUID
  **/
  public UUID getIncotermsSupChnDvtgLocAddlUUID() {
    return incotermsSupChnDvtgLocAddlUUID;
  }

  public void setIncotermsSupChnDvtgLocAddlUUID(UUID incotermsSupChnDvtgLocAddlUUID) {
    this.incotermsSupChnDvtgLocAddlUUID = incotermsSupChnDvtgLocAddlUUID;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate intrastatCrsBorderTrMode(String intrastatCrsBorderTrMode) {
    this.intrastatCrsBorderTrMode = intrastatCrsBorderTrMode;
    return this;
  }

   /**
   * Mode of Transport at the Border (Intrastat)
   * @return intrastatCrsBorderTrMode
  **/
  public String getIntrastatCrsBorderTrMode() {
    return intrastatCrsBorderTrMode;
  }

  public void setIntrastatCrsBorderTrMode(String intrastatCrsBorderTrMode) {
    this.intrastatCrsBorderTrMode = intrastatCrsBorderTrMode;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate invoiceIsGoodsReceiptBased(Boolean invoiceIsGoodsReceiptBased) {
    this.invoiceIsGoodsReceiptBased = invoiceIsGoodsReceiptBased;
    return this;
  }

   /**
   * Indicator: GR-Based Invoice Verification
   * @return invoiceIsGoodsReceiptBased
  **/
  public Boolean isInvoiceIsGoodsReceiptBased() {
    return invoiceIsGoodsReceiptBased;
  }

  public void setInvoiceIsGoodsReceiptBased(Boolean invoiceIsGoodsReceiptBased) {
    this.invoiceIsGoodsReceiptBased = invoiceIsGoodsReceiptBased;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate invoiceIsMMServiceEntryBased(Boolean invoiceIsMMServiceEntryBased) {
    this.invoiceIsMMServiceEntryBased = invoiceIsMMServiceEntryBased;
    return this;
  }

   /**
   * Indicator for Service-Based Invoice Verification
   * @return invoiceIsMMServiceEntryBased
  **/
  public Boolean isInvoiceIsMMServiceEntryBased() {
    return invoiceIsMMServiceEntryBased;
  }

  public void setInvoiceIsMMServiceEntryBased(Boolean invoiceIsMMServiceEntryBased) {
    this.invoiceIsMMServiceEntryBased = invoiceIsMMServiceEntryBased;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate materialPlannedDeliveryDurn(String materialPlannedDeliveryDurn) {
    this.materialPlannedDeliveryDurn = materialPlannedDeliveryDurn;
    return this;
  }

   /**
   * Planned Delivery Time in Days
   * @return materialPlannedDeliveryDurn
  **/
  public String getMaterialPlannedDeliveryDurn() {
    return materialPlannedDeliveryDurn;
  }

  public void setMaterialPlannedDeliveryDurn(String materialPlannedDeliveryDurn) {
    this.materialPlannedDeliveryDurn = materialPlannedDeliveryDurn;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate minimumOrderAmount(String minimumOrderAmount) {
    this.minimumOrderAmount = minimumOrderAmount;
    return this;
  }

   /**
   * Get minimumOrderAmount
   * @return minimumOrderAmount
  **/
  public String getMinimumOrderAmount() {
    return minimumOrderAmount;
  }

  public void setMinimumOrderAmount(String minimumOrderAmount) {
    this.minimumOrderAmount = minimumOrderAmount;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate paymentTerms(String paymentTerms) {
    this.paymentTerms = paymentTerms;
    return this;
  }

   /**
   * Key for Terms of Payment
   * @return paymentTerms
  **/
  public String getPaymentTerms() {
    return paymentTerms;
  }

  public void setPaymentTerms(String paymentTerms) {
    this.paymentTerms = paymentTerms;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate planningCycle(String planningCycle) {
    this.planningCycle = planningCycle;
    return this;
  }

   /**
   * Get planningCycle
   * @return planningCycle
  **/
  public String getPlanningCycle() {
    return planningCycle;
  }

  public void setPlanningCycle(String planningCycle) {
    this.planningCycle = planningCycle;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate pricingDateControl(String pricingDateControl) {
    this.pricingDateControl = pricingDateControl;
    return this;
  }

   /**
   * Price Determination (Pricing) Date Control
   * @return pricingDateControl
  **/
  public String getPricingDateControl() {
    return pricingDateControl;
  }

  public void setPricingDateControl(String pricingDateControl) {
    this.pricingDateControl = pricingDateControl;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate prodStockAndSlsDataTransfPrfl(String prodStockAndSlsDataTransfPrfl) {
    this.prodStockAndSlsDataTransfPrfl = prodStockAndSlsDataTransfPrfl;
    return this;
  }

   /**
   * Profile for transferring material data via IDoc PROACT
   * @return prodStockAndSlsDataTransfPrfl
  **/
  public String getProdStockAndSlsDataTransfPrfl() {
    return prodStockAndSlsDataTransfPrfl;
  }

  public void setProdStockAndSlsDataTransfPrfl(String prodStockAndSlsDataTransfPrfl) {
    this.prodStockAndSlsDataTransfPrfl = prodStockAndSlsDataTransfPrfl;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate productUnitGroup(String productUnitGroup) {
    this.productUnitGroup = productUnitGroup;
    return this;
  }

   /**
   * Unit of Measure Group
   * @return productUnitGroup
  **/
  public String getProductUnitGroup() {
    return productUnitGroup;
  }

  public void setProductUnitGroup(String productUnitGroup) {
    this.productUnitGroup = productUnitGroup;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate purOrdAutoGenerationIsAllowed(Boolean purOrdAutoGenerationIsAllowed) {
    this.purOrdAutoGenerationIsAllowed = purOrdAutoGenerationIsAllowed;
    return this;
  }

   /**
   * Automatic Generation of Purchase Order Allowed
   * @return purOrdAutoGenerationIsAllowed
  **/
  public Boolean isPurOrdAutoGenerationIsAllowed() {
    return purOrdAutoGenerationIsAllowed;
  }

  public void setPurOrdAutoGenerationIsAllowed(Boolean purOrdAutoGenerationIsAllowed) {
    this.purOrdAutoGenerationIsAllowed = purOrdAutoGenerationIsAllowed;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate purchaseOrderCurrency(String purchaseOrderCurrency) {
    this.purchaseOrderCurrency = purchaseOrderCurrency;
    return this;
  }

   /**
   * Purchase order currency
   * @return purchaseOrderCurrency
  **/
  public String getPurchaseOrderCurrency() {
    return purchaseOrderCurrency;
  }

  public void setPurchaseOrderCurrency(String purchaseOrderCurrency) {
    this.purchaseOrderCurrency = purchaseOrderCurrency;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate purchasingGroup(String purchasingGroup) {
    this.purchasingGroup = purchasingGroup;
    return this;
  }

   /**
   * Get purchasingGroup
   * @return purchasingGroup
  **/
  public String getPurchasingGroup() {
    return purchasingGroup;
  }

  public void setPurchasingGroup(String purchasingGroup) {
    this.purchasingGroup = purchasingGroup;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate purchasingIsBlockedForSupplier(Boolean purchasingIsBlockedForSupplier) {
    this.purchasingIsBlockedForSupplier = purchasingIsBlockedForSupplier;
    return this;
  }

   /**
   * Purchasing block at purchasing organization level
   * @return purchasingIsBlockedForSupplier
  **/
  public Boolean isPurchasingIsBlockedForSupplier() {
    return purchasingIsBlockedForSupplier;
  }

  public void setPurchasingIsBlockedForSupplier(Boolean purchasingIsBlockedForSupplier) {
    this.purchasingIsBlockedForSupplier = purchasingIsBlockedForSupplier;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate roundingProfile(String roundingProfile) {
    this.roundingProfile = roundingProfile;
    return this;
  }

   /**
   * Get roundingProfile
   * @return roundingProfile
  **/
  public String getRoundingProfile() {
    return roundingProfile;
  }

  public void setRoundingProfile(String roundingProfile) {
    this.roundingProfile = roundingProfile;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate shippingCondition(String shippingCondition) {
    this.shippingCondition = shippingCondition;
    return this;
  }

   /**
   * Get shippingCondition
   * @return shippingCondition
  **/
  public String getShippingCondition() {
    return shippingCondition;
  }

  public void setShippingCondition(String shippingCondition) {
    this.shippingCondition = shippingCondition;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate suplrDiscountInKindIsGranted(Boolean suplrDiscountInKindIsGranted) {
    this.suplrDiscountInKindIsGranted = suplrDiscountInKindIsGranted;
    return this;
  }

   /**
   * Get suplrDiscountInKindIsGranted
   * @return suplrDiscountInKindIsGranted
  **/
  public Boolean isSuplrDiscountInKindIsGranted() {
    return suplrDiscountInKindIsGranted;
  }

  public void setSuplrDiscountInKindIsGranted(Boolean suplrDiscountInKindIsGranted) {
    this.suplrDiscountInKindIsGranted = suplrDiscountInKindIsGranted;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate suplrInvcRevalIsAllowed(Boolean suplrInvcRevalIsAllowed) {
    this.suplrInvcRevalIsAllowed = suplrInvcRevalIsAllowed;
    return this;
  }

   /**
   * Revaluation allowed
   * @return suplrInvcRevalIsAllowed
  **/
  public Boolean isSuplrInvcRevalIsAllowed() {
    return suplrInvcRevalIsAllowed;
  }

  public void setSuplrInvcRevalIsAllowed(Boolean suplrInvcRevalIsAllowed) {
    this.suplrInvcRevalIsAllowed = suplrInvcRevalIsAllowed;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate suplrIsRlvtForSettlmtMgmt(Boolean suplrIsRlvtForSettlmtMgmt) {
    this.suplrIsRlvtForSettlmtMgmt = suplrIsRlvtForSettlmtMgmt;
    return this;
  }

   /**
   * Indicator: Relevant for Settlement Management
   * @return suplrIsRlvtForSettlmtMgmt
  **/
  public Boolean isSuplrIsRlvtForSettlmtMgmt() {
    return suplrIsRlvtForSettlmtMgmt;
  }

  public void setSuplrIsRlvtForSettlmtMgmt(Boolean suplrIsRlvtForSettlmtMgmt) {
    this.suplrIsRlvtForSettlmtMgmt = suplrIsRlvtForSettlmtMgmt;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate suplrPurgOrgIsRlvtForPriceDetn(Boolean suplrPurgOrgIsRlvtForPriceDetn) {
    this.suplrPurgOrgIsRlvtForPriceDetn = suplrPurgOrgIsRlvtForPriceDetn;
    return this;
  }

   /**
   * Indicator: \&quot;relev. to price determination (vend. hierarchy)
   * @return suplrPurgOrgIsRlvtForPriceDetn
  **/
  public Boolean isSuplrPurgOrgIsRlvtForPriceDetn() {
    return suplrPurgOrgIsRlvtForPriceDetn;
  }

  public void setSuplrPurgOrgIsRlvtForPriceDetn(Boolean suplrPurgOrgIsRlvtForPriceDetn) {
    this.suplrPurgOrgIsRlvtForPriceDetn = suplrPurgOrgIsRlvtForPriceDetn;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate supplierABCClassificationCode(String supplierABCClassificationCode) {
    this.supplierABCClassificationCode = supplierABCClassificationCode;
    return this;
  }

   /**
   * Get supplierABCClassificationCode
   * @return supplierABCClassificationCode
  **/
  public String getSupplierABCClassificationCode() {
    return supplierABCClassificationCode;
  }

  public void setSupplierABCClassificationCode(String supplierABCClassificationCode) {
    this.supplierABCClassificationCode = supplierABCClassificationCode;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate supplierAccountNumber(String supplierAccountNumber) {
    this.supplierAccountNumber = supplierAccountNumber;
    return this;
  }

   /**
   * Our account number with the supplier
   * @return supplierAccountNumber
  **/
  public String getSupplierAccountNumber() {
    return supplierAccountNumber;
  }

  public void setSupplierAccountNumber(String supplierAccountNumber) {
    this.supplierAccountNumber = supplierAccountNumber;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate supplierIsReturnsSupplier(Boolean supplierIsReturnsSupplier) {
    this.supplierIsReturnsSupplier = supplierIsReturnsSupplier;
    return this;
  }

   /**
   * Indicates whether supplier is returns supplier
   * @return supplierIsReturnsSupplier
  **/
  public Boolean isSupplierIsReturnsSupplier() {
    return supplierIsReturnsSupplier;
  }

  public void setSupplierIsReturnsSupplier(Boolean supplierIsReturnsSupplier) {
    this.supplierIsReturnsSupplier = supplierIsReturnsSupplier;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate supplierPhoneNumber(String supplierPhoneNumber) {
    this.supplierPhoneNumber = supplierPhoneNumber;
    return this;
  }

   /**
   * Supplier&#x27;s Telephone Number
   * @return supplierPhoneNumber
  **/
  public String getSupplierPhoneNumber() {
    return supplierPhoneNumber;
  }

  public void setSupplierPhoneNumber(String supplierPhoneNumber) {
    this.supplierPhoneNumber = supplierPhoneNumber;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate supplierRespSalesPersonName(String supplierRespSalesPersonName) {
    this.supplierRespSalesPersonName = supplierRespSalesPersonName;
    return this;
  }

   /**
   * Responsible Salesperson at Supplier&#x27;s Office
   * @return supplierRespSalesPersonName
  **/
  public String getSupplierRespSalesPersonName() {
    return supplierRespSalesPersonName;
  }

  public void setSupplierRespSalesPersonName(String supplierRespSalesPersonName) {
    this.supplierRespSalesPersonName = supplierRespSalesPersonName;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate supplierConfirmationControlKey(String supplierConfirmationControlKey) {
    this.supplierConfirmationControlKey = supplierConfirmationControlKey;
    return this;
  }

   /**
   * Confirmation Control Key
   * @return supplierConfirmationControlKey
  **/
  public String getSupplierConfirmationControlKey() {
    return supplierConfirmationControlKey;
  }

  public void setSupplierConfirmationControlKey(String supplierConfirmationControlKey) {
    this.supplierConfirmationControlKey = supplierConfirmationControlKey;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate isOrderAcknRqd(Boolean isOrderAcknRqd) {
    this.isOrderAcknRqd = isOrderAcknRqd;
    return this;
  }

   /**
   * Order Acknowledgment Requirement
   * @return isOrderAcknRqd
  **/
  public Boolean isIsOrderAcknRqd() {
    return isOrderAcknRqd;
  }

  public void setIsOrderAcknRqd(Boolean isOrderAcknRqd) {
    this.isOrderAcknRqd = isOrderAcknRqd;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Authorization Group
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate supplierAccountGroup(String supplierAccountGroup) {
    this.supplierAccountGroup = supplierAccountGroup;
    return this;
  }

   /**
   * Supplier Account Group
   * @return supplierAccountGroup
  **/
  public String getSupplierAccountGroup() {
    return supplierAccountGroup;
  }

  public void setSupplierAccountGroup(String supplierAccountGroup) {
    this.supplierAccountGroup = supplierAccountGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate = (APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate) o;
    return Objects.equals(this.automaticEvaluatedRcptSettlmt, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.automaticEvaluatedRcptSettlmt) &&
        Objects.equals(this.calculationSchemaGroupCode, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.calculationSchemaGroupCode) &&
        Objects.equals(this.deletionIndicator, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.deletionIndicator) &&
        Objects.equals(this.evaldReceiptSettlementIsActive, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.evaldReceiptSettlementIsActive) &&
        Objects.equals(this.incotermsClassification, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.incotermsClassification) &&
        Objects.equals(this.incotermsTransferLocation, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.incotermsTransferLocation) &&
        Objects.equals(this.incotermsVersion, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.incotermsVersion) &&
        Objects.equals(this.incotermsLocation1, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.incotermsLocation1) &&
        Objects.equals(this.incotermsLocation2, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.incotermsLocation2) &&
        Objects.equals(this.incotermsSupChnLoc1AddlUUID, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.incotermsSupChnLoc1AddlUUID) &&
        Objects.equals(this.incotermsSupChnLoc2AddlUUID, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.incotermsSupChnLoc2AddlUUID) &&
        Objects.equals(this.incotermsSupChnDvtgLocAddlUUID, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.incotermsSupChnDvtgLocAddlUUID) &&
        Objects.equals(this.intrastatCrsBorderTrMode, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.intrastatCrsBorderTrMode) &&
        Objects.equals(this.invoiceIsGoodsReceiptBased, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.invoiceIsGoodsReceiptBased) &&
        Objects.equals(this.invoiceIsMMServiceEntryBased, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.invoiceIsMMServiceEntryBased) &&
        Objects.equals(this.materialPlannedDeliveryDurn, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.materialPlannedDeliveryDurn) &&
        Objects.equals(this.minimumOrderAmount, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.minimumOrderAmount) &&
        Objects.equals(this.paymentTerms, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.paymentTerms) &&
        Objects.equals(this.planningCycle, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.planningCycle) &&
        Objects.equals(this.pricingDateControl, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.pricingDateControl) &&
        Objects.equals(this.prodStockAndSlsDataTransfPrfl, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.prodStockAndSlsDataTransfPrfl) &&
        Objects.equals(this.productUnitGroup, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.productUnitGroup) &&
        Objects.equals(this.purOrdAutoGenerationIsAllowed, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.purOrdAutoGenerationIsAllowed) &&
        Objects.equals(this.purchaseOrderCurrency, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.purchaseOrderCurrency) &&
        Objects.equals(this.purchasingGroup, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.purchasingGroup) &&
        Objects.equals(this.purchasingIsBlockedForSupplier, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.purchasingIsBlockedForSupplier) &&
        Objects.equals(this.roundingProfile, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.roundingProfile) &&
        Objects.equals(this.shippingCondition, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.shippingCondition) &&
        Objects.equals(this.suplrDiscountInKindIsGranted, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.suplrDiscountInKindIsGranted) &&
        Objects.equals(this.suplrInvcRevalIsAllowed, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.suplrInvcRevalIsAllowed) &&
        Objects.equals(this.suplrIsRlvtForSettlmtMgmt, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.suplrIsRlvtForSettlmtMgmt) &&
        Objects.equals(this.suplrPurgOrgIsRlvtForPriceDetn, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.suplrPurgOrgIsRlvtForPriceDetn) &&
        Objects.equals(this.supplierABCClassificationCode, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.supplierABCClassificationCode) &&
        Objects.equals(this.supplierAccountNumber, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.supplierAccountNumber) &&
        Objects.equals(this.supplierIsReturnsSupplier, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.supplierIsReturnsSupplier) &&
        Objects.equals(this.supplierPhoneNumber, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.supplierPhoneNumber) &&
        Objects.equals(this.supplierRespSalesPersonName, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.supplierRespSalesPersonName) &&
        Objects.equals(this.supplierConfirmationControlKey, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.supplierConfirmationControlKey) &&
        Objects.equals(this.isOrderAcknRqd, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.isOrderAcknRqd) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.authorizationGroup) &&
        Objects.equals(this.supplierAccountGroup, apIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate.supplierAccountGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(automaticEvaluatedRcptSettlmt, calculationSchemaGroupCode, deletionIndicator, evaldReceiptSettlementIsActive, incotermsClassification, incotermsTransferLocation, incotermsVersion, incotermsLocation1, incotermsLocation2, incotermsSupChnLoc1AddlUUID, incotermsSupChnLoc2AddlUUID, incotermsSupChnDvtgLocAddlUUID, intrastatCrsBorderTrMode, invoiceIsGoodsReceiptBased, invoiceIsMMServiceEntryBased, materialPlannedDeliveryDurn, minimumOrderAmount, paymentTerms, planningCycle, pricingDateControl, prodStockAndSlsDataTransfPrfl, productUnitGroup, purOrdAutoGenerationIsAllowed, purchaseOrderCurrency, purchasingGroup, purchasingIsBlockedForSupplier, roundingProfile, shippingCondition, suplrDiscountInKindIsGranted, suplrInvcRevalIsAllowed, suplrIsRlvtForSettlmtMgmt, suplrPurgOrgIsRlvtForPriceDetn, supplierABCClassificationCode, supplierAccountNumber, supplierIsReturnsSupplier, supplierPhoneNumber, supplierRespSalesPersonName, supplierConfirmationControlKey, isOrderAcknRqd, authorizationGroup, supplierAccountGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERASupplierPurchasingOrgTypeUpdate {\n");
    
    sb.append("    automaticEvaluatedRcptSettlmt: ").append(toIndentedString(automaticEvaluatedRcptSettlmt)).append("\n");
    sb.append("    calculationSchemaGroupCode: ").append(toIndentedString(calculationSchemaGroupCode)).append("\n");
    sb.append("    deletionIndicator: ").append(toIndentedString(deletionIndicator)).append("\n");
    sb.append("    evaldReceiptSettlementIsActive: ").append(toIndentedString(evaldReceiptSettlementIsActive)).append("\n");
    sb.append("    incotermsClassification: ").append(toIndentedString(incotermsClassification)).append("\n");
    sb.append("    incotermsTransferLocation: ").append(toIndentedString(incotermsTransferLocation)).append("\n");
    sb.append("    incotermsVersion: ").append(toIndentedString(incotermsVersion)).append("\n");
    sb.append("    incotermsLocation1: ").append(toIndentedString(incotermsLocation1)).append("\n");
    sb.append("    incotermsLocation2: ").append(toIndentedString(incotermsLocation2)).append("\n");
    sb.append("    incotermsSupChnLoc1AddlUUID: ").append(toIndentedString(incotermsSupChnLoc1AddlUUID)).append("\n");
    sb.append("    incotermsSupChnLoc2AddlUUID: ").append(toIndentedString(incotermsSupChnLoc2AddlUUID)).append("\n");
    sb.append("    incotermsSupChnDvtgLocAddlUUID: ").append(toIndentedString(incotermsSupChnDvtgLocAddlUUID)).append("\n");
    sb.append("    intrastatCrsBorderTrMode: ").append(toIndentedString(intrastatCrsBorderTrMode)).append("\n");
    sb.append("    invoiceIsGoodsReceiptBased: ").append(toIndentedString(invoiceIsGoodsReceiptBased)).append("\n");
    sb.append("    invoiceIsMMServiceEntryBased: ").append(toIndentedString(invoiceIsMMServiceEntryBased)).append("\n");
    sb.append("    materialPlannedDeliveryDurn: ").append(toIndentedString(materialPlannedDeliveryDurn)).append("\n");
    sb.append("    minimumOrderAmount: ").append(toIndentedString(minimumOrderAmount)).append("\n");
    sb.append("    paymentTerms: ").append(toIndentedString(paymentTerms)).append("\n");
    sb.append("    planningCycle: ").append(toIndentedString(planningCycle)).append("\n");
    sb.append("    pricingDateControl: ").append(toIndentedString(pricingDateControl)).append("\n");
    sb.append("    prodStockAndSlsDataTransfPrfl: ").append(toIndentedString(prodStockAndSlsDataTransfPrfl)).append("\n");
    sb.append("    productUnitGroup: ").append(toIndentedString(productUnitGroup)).append("\n");
    sb.append("    purOrdAutoGenerationIsAllowed: ").append(toIndentedString(purOrdAutoGenerationIsAllowed)).append("\n");
    sb.append("    purchaseOrderCurrency: ").append(toIndentedString(purchaseOrderCurrency)).append("\n");
    sb.append("    purchasingGroup: ").append(toIndentedString(purchasingGroup)).append("\n");
    sb.append("    purchasingIsBlockedForSupplier: ").append(toIndentedString(purchasingIsBlockedForSupplier)).append("\n");
    sb.append("    roundingProfile: ").append(toIndentedString(roundingProfile)).append("\n");
    sb.append("    shippingCondition: ").append(toIndentedString(shippingCondition)).append("\n");
    sb.append("    suplrDiscountInKindIsGranted: ").append(toIndentedString(suplrDiscountInKindIsGranted)).append("\n");
    sb.append("    suplrInvcRevalIsAllowed: ").append(toIndentedString(suplrInvcRevalIsAllowed)).append("\n");
    sb.append("    suplrIsRlvtForSettlmtMgmt: ").append(toIndentedString(suplrIsRlvtForSettlmtMgmt)).append("\n");
    sb.append("    suplrPurgOrgIsRlvtForPriceDetn: ").append(toIndentedString(suplrPurgOrgIsRlvtForPriceDetn)).append("\n");
    sb.append("    supplierABCClassificationCode: ").append(toIndentedString(supplierABCClassificationCode)).append("\n");
    sb.append("    supplierAccountNumber: ").append(toIndentedString(supplierAccountNumber)).append("\n");
    sb.append("    supplierIsReturnsSupplier: ").append(toIndentedString(supplierIsReturnsSupplier)).append("\n");
    sb.append("    supplierPhoneNumber: ").append(toIndentedString(supplierPhoneNumber)).append("\n");
    sb.append("    supplierRespSalesPersonName: ").append(toIndentedString(supplierRespSalesPersonName)).append("\n");
    sb.append("    supplierConfirmationControlKey: ").append(toIndentedString(supplierConfirmationControlKey)).append("\n");
    sb.append("    isOrderAcknRqd: ").append(toIndentedString(isOrderAcknRqd)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("    supplierAccountGroup: ").append(toIndentedString(supplierAccountGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
