/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.axon.market.s4hana.client.APIBUSINESSPARTNERABusinessPartnerContactTypecreateToContactAddress;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABusinessPartnerContactTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABusinessPartnerContactTypeCreate {
  @JsonProperty("RelationshipNumber")
  private String relationshipNumber = null;

  @JsonProperty("BusinessPartnerCompany")
  private String businessPartnerCompany = null;

  @JsonProperty("BusinessPartnerPerson")
  private String businessPartnerPerson = null;

  @JsonProperty("ValidityEndDate")
  private String validityEndDate = null;

  @JsonProperty("ValidityStartDate")
  private String validityStartDate = null;

  @JsonProperty("IsStandardRelationship")
  private Boolean isStandardRelationship = null;

  @JsonProperty("RelationshipCategory")
  private String relationshipCategory = null;

  @JsonProperty("to_ContactAddress")
  private APIBUSINESSPARTNERABusinessPartnerContactTypecreateToContactAddress toContactAddress = null;

  @JsonProperty("to_ContactRelationship")
  private AllOfAPIBUSINESSPARTNERABusinessPartnerContactTypeCreateToContactRelationship toContactRelationship = null;

  public APIBUSINESSPARTNERABusinessPartnerContactTypeCreate relationshipNumber(String relationshipNumber) {
    this.relationshipNumber = relationshipNumber;
    return this;
  }

   /**
   * BP Relationship Number
   * @return relationshipNumber
  **/
  public String getRelationshipNumber() {
    return relationshipNumber;
  }

  public void setRelationshipNumber(String relationshipNumber) {
    this.relationshipNumber = relationshipNumber;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactTypeCreate businessPartnerCompany(String businessPartnerCompany) {
    this.businessPartnerCompany = businessPartnerCompany;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartnerCompany
  **/
  public String getBusinessPartnerCompany() {
    return businessPartnerCompany;
  }

  public void setBusinessPartnerCompany(String businessPartnerCompany) {
    this.businessPartnerCompany = businessPartnerCompany;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactTypeCreate businessPartnerPerson(String businessPartnerPerson) {
    this.businessPartnerPerson = businessPartnerPerson;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartnerPerson
  **/
  public String getBusinessPartnerPerson() {
    return businessPartnerPerson;
  }

  public void setBusinessPartnerPerson(String businessPartnerPerson) {
    this.businessPartnerPerson = businessPartnerPerson;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactTypeCreate validityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
    return this;
  }

   /**
   * Validity Date (Valid To)
   * @return validityEndDate
  **/
  public String getValidityEndDate() {
    return validityEndDate;
  }

  public void setValidityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactTypeCreate validityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
    return this;
  }

   /**
   * Validity Date (Valid From)
   * @return validityStartDate
  **/
  public String getValidityStartDate() {
    return validityStartDate;
  }

  public void setValidityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactTypeCreate isStandardRelationship(Boolean isStandardRelationship) {
    this.isStandardRelationship = isStandardRelationship;
    return this;
  }

   /**
   * Standard Relationship
   * @return isStandardRelationship
  **/
  public Boolean isIsStandardRelationship() {
    return isStandardRelationship;
  }

  public void setIsStandardRelationship(Boolean isStandardRelationship) {
    this.isStandardRelationship = isStandardRelationship;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactTypeCreate relationshipCategory(String relationshipCategory) {
    this.relationshipCategory = relationshipCategory;
    return this;
  }

   /**
   * Business Partner Relationship Category
   * @return relationshipCategory
  **/
  public String getRelationshipCategory() {
    return relationshipCategory;
  }

  public void setRelationshipCategory(String relationshipCategory) {
    this.relationshipCategory = relationshipCategory;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactTypeCreate toContactAddress(APIBUSINESSPARTNERABusinessPartnerContactTypecreateToContactAddress toContactAddress) {
    this.toContactAddress = toContactAddress;
    return this;
  }

   /**
   * Get toContactAddress
   * @return toContactAddress
  **/
  public APIBUSINESSPARTNERABusinessPartnerContactTypecreateToContactAddress getToContactAddress() {
    return toContactAddress;
  }

  public void setToContactAddress(APIBUSINESSPARTNERABusinessPartnerContactTypecreateToContactAddress toContactAddress) {
    this.toContactAddress = toContactAddress;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactTypeCreate toContactRelationship(AllOfAPIBUSINESSPARTNERABusinessPartnerContactTypeCreateToContactRelationship toContactRelationship) {
    this.toContactRelationship = toContactRelationship;
    return this;
  }

   /**
   * Get toContactRelationship
   * @return toContactRelationship
  **/
  public AllOfAPIBUSINESSPARTNERABusinessPartnerContactTypeCreateToContactRelationship getToContactRelationship() {
    return toContactRelationship;
  }

  public void setToContactRelationship(AllOfAPIBUSINESSPARTNERABusinessPartnerContactTypeCreateToContactRelationship toContactRelationship) {
    this.toContactRelationship = toContactRelationship;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerContactTypeCreate apIBUSINESSPARTNERABusinessPartnerContactTypeCreate = (APIBUSINESSPARTNERABusinessPartnerContactTypeCreate) o;
    return Objects.equals(this.relationshipNumber, apIBUSINESSPARTNERABusinessPartnerContactTypeCreate.relationshipNumber) &&
        Objects.equals(this.businessPartnerCompany, apIBUSINESSPARTNERABusinessPartnerContactTypeCreate.businessPartnerCompany) &&
        Objects.equals(this.businessPartnerPerson, apIBUSINESSPARTNERABusinessPartnerContactTypeCreate.businessPartnerPerson) &&
        Objects.equals(this.validityEndDate, apIBUSINESSPARTNERABusinessPartnerContactTypeCreate.validityEndDate) &&
        Objects.equals(this.validityStartDate, apIBUSINESSPARTNERABusinessPartnerContactTypeCreate.validityStartDate) &&
        Objects.equals(this.isStandardRelationship, apIBUSINESSPARTNERABusinessPartnerContactTypeCreate.isStandardRelationship) &&
        Objects.equals(this.relationshipCategory, apIBUSINESSPARTNERABusinessPartnerContactTypeCreate.relationshipCategory) &&
        Objects.equals(this.toContactAddress, apIBUSINESSPARTNERABusinessPartnerContactTypeCreate.toContactAddress) &&
        Objects.equals(this.toContactRelationship, apIBUSINESSPARTNERABusinessPartnerContactTypeCreate.toContactRelationship);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, validityStartDate, isStandardRelationship, relationshipCategory, toContactAddress, toContactRelationship);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerContactTypeCreate {\n");
    
    sb.append("    relationshipNumber: ").append(toIndentedString(relationshipNumber)).append("\n");
    sb.append("    businessPartnerCompany: ").append(toIndentedString(businessPartnerCompany)).append("\n");
    sb.append("    businessPartnerPerson: ").append(toIndentedString(businessPartnerPerson)).append("\n");
    sb.append("    validityEndDate: ").append(toIndentedString(validityEndDate)).append("\n");
    sb.append("    validityStartDate: ").append(toIndentedString(validityStartDate)).append("\n");
    sb.append("    isStandardRelationship: ").append(toIndentedString(isStandardRelationship)).append("\n");
    sb.append("    relationshipCategory: ").append(toIndentedString(relationshipCategory)).append("\n");
    sb.append("    toContactAddress: ").append(toIndentedString(toContactAddress)).append("\n");
    sb.append("    toContactRelationship: ").append(toIndentedString(toContactRelationship)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
