/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERACustomerCompanyTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERACustomerCompanyTypeUpdate {
  @JsonProperty("APARToleranceGroup")
  private String apARToleranceGroup = null;

  @JsonProperty("AccountByCustomer")
  private String accountByCustomer = null;

  @JsonProperty("AccountingClerk")
  private String accountingClerk = null;

  @JsonProperty("AccountingClerkFaxNumber")
  private String accountingClerkFaxNumber = null;

  @JsonProperty("AccountingClerkInternetAddress")
  private String accountingClerkInternetAddress = null;

  @JsonProperty("AccountingClerkPhoneNumber")
  private String accountingClerkPhoneNumber = null;

  @JsonProperty("AlternativePayerAccount")
  private String alternativePayerAccount = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  @JsonProperty("CollectiveInvoiceVariant")
  private String collectiveInvoiceVariant = null;

  @JsonProperty("CustomerAccountNote")
  private String customerAccountNote = null;

  @JsonProperty("CustomerHeadOffice")
  private String customerHeadOffice = null;

  @JsonProperty("CustomerSupplierClearingIsUsed")
  private Boolean customerSupplierClearingIsUsed = null;

  @JsonProperty("HouseBank")
  private String houseBank = null;

  @JsonProperty("InterestCalculationCode")
  private String interestCalculationCode = null;

  @JsonProperty("InterestCalculationDate")
  private String interestCalculationDate = null;

  @JsonProperty("IntrstCalcFrequencyInMonths")
  private String intrstCalcFrequencyInMonths = null;

  @JsonProperty("IsToBeLocallyProcessed")
  private Boolean isToBeLocallyProcessed = null;

  @JsonProperty("ItemIsToBePaidSeparately")
  private Boolean itemIsToBePaidSeparately = null;

  @JsonProperty("LayoutSortingRule")
  private String layoutSortingRule = null;

  @JsonProperty("PaymentBlockingReason")
  private String paymentBlockingReason = null;

  @JsonProperty("PaymentMethodsList")
  private String paymentMethodsList = null;

  @JsonProperty("PaymentReason")
  private String paymentReason = null;

  @JsonProperty("PaymentTerms")
  private String paymentTerms = null;

  @JsonProperty("PaytAdviceIsSentbyEDI")
  private Boolean paytAdviceIsSentbyEDI = null;

  @JsonProperty("PhysicalInventoryBlockInd")
  private Boolean physicalInventoryBlockInd = null;

  @JsonProperty("ReconciliationAccount")
  private String reconciliationAccount = null;

  @JsonProperty("RecordPaymentHistoryIndicator")
  private Boolean recordPaymentHistoryIndicator = null;

  @JsonProperty("UserAtCustomer")
  private String userAtCustomer = null;

  @JsonProperty("DeletionIndicator")
  private Boolean deletionIndicator = null;

  @JsonProperty("CashPlanningGroup")
  private String cashPlanningGroup = null;

  @JsonProperty("KnownOrNegotiatedLeave")
  private String knownOrNegotiatedLeave = null;

  @JsonProperty("ValueAdjustmentKey")
  private String valueAdjustmentKey = null;

  @JsonProperty("CustomerAccountGroup")
  private String customerAccountGroup = null;

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate apARToleranceGroup(String apARToleranceGroup) {
    this.apARToleranceGroup = apARToleranceGroup;
    return this;
  }

   /**
   * Tolerance Group for Business Partner/G/L Account
   * @return apARToleranceGroup
  **/
  public String getApARToleranceGroup() {
    return apARToleranceGroup;
  }

  public void setApARToleranceGroup(String apARToleranceGroup) {
    this.apARToleranceGroup = apARToleranceGroup;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate accountByCustomer(String accountByCustomer) {
    this.accountByCustomer = accountByCustomer;
    return this;
  }

   /**
   * Our Account Number at Customer
   * @return accountByCustomer
  **/
  public String getAccountByCustomer() {
    return accountByCustomer;
  }

  public void setAccountByCustomer(String accountByCustomer) {
    this.accountByCustomer = accountByCustomer;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate accountingClerk(String accountingClerk) {
    this.accountingClerk = accountingClerk;
    return this;
  }

   /**
   * Accounting Clerk Abbreviation
   * @return accountingClerk
  **/
  public String getAccountingClerk() {
    return accountingClerk;
  }

  public void setAccountingClerk(String accountingClerk) {
    this.accountingClerk = accountingClerk;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate accountingClerkFaxNumber(String accountingClerkFaxNumber) {
    this.accountingClerkFaxNumber = accountingClerkFaxNumber;
    return this;
  }

   /**
   * Accounting clerk&#x27;s fax number at the customer/vendor
   * @return accountingClerkFaxNumber
  **/
  public String getAccountingClerkFaxNumber() {
    return accountingClerkFaxNumber;
  }

  public void setAccountingClerkFaxNumber(String accountingClerkFaxNumber) {
    this.accountingClerkFaxNumber = accountingClerkFaxNumber;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate accountingClerkInternetAddress(String accountingClerkInternetAddress) {
    this.accountingClerkInternetAddress = accountingClerkInternetAddress;
    return this;
  }

   /**
   * Internet address of partner company clerk
   * @return accountingClerkInternetAddress
  **/
  public String getAccountingClerkInternetAddress() {
    return accountingClerkInternetAddress;
  }

  public void setAccountingClerkInternetAddress(String accountingClerkInternetAddress) {
    this.accountingClerkInternetAddress = accountingClerkInternetAddress;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate accountingClerkPhoneNumber(String accountingClerkPhoneNumber) {
    this.accountingClerkPhoneNumber = accountingClerkPhoneNumber;
    return this;
  }

   /**
   * Accounting clerk&#x27;s telephone number at business partner
   * @return accountingClerkPhoneNumber
  **/
  public String getAccountingClerkPhoneNumber() {
    return accountingClerkPhoneNumber;
  }

  public void setAccountingClerkPhoneNumber(String accountingClerkPhoneNumber) {
    this.accountingClerkPhoneNumber = accountingClerkPhoneNumber;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate alternativePayerAccount(String alternativePayerAccount) {
    this.alternativePayerAccount = alternativePayerAccount;
    return this;
  }

   /**
   * Account number of an alternative payer
   * @return alternativePayerAccount
  **/
  public String getAlternativePayerAccount() {
    return alternativePayerAccount;
  }

  public void setAlternativePayerAccount(String alternativePayerAccount) {
    this.alternativePayerAccount = alternativePayerAccount;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Authorization Group
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate collectiveInvoiceVariant(String collectiveInvoiceVariant) {
    this.collectiveInvoiceVariant = collectiveInvoiceVariant;
    return this;
  }

   /**
   * Collective Invoice Variant
   * @return collectiveInvoiceVariant
  **/
  public String getCollectiveInvoiceVariant() {
    return collectiveInvoiceVariant;
  }

  public void setCollectiveInvoiceVariant(String collectiveInvoiceVariant) {
    this.collectiveInvoiceVariant = collectiveInvoiceVariant;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate customerAccountNote(String customerAccountNote) {
    this.customerAccountNote = customerAccountNote;
    return this;
  }

   /**
   * Memo
   * @return customerAccountNote
  **/
  public String getCustomerAccountNote() {
    return customerAccountNote;
  }

  public void setCustomerAccountNote(String customerAccountNote) {
    this.customerAccountNote = customerAccountNote;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate customerHeadOffice(String customerHeadOffice) {
    this.customerHeadOffice = customerHeadOffice;
    return this;
  }

   /**
   * Head Office Account Number (in branch accounts)
   * @return customerHeadOffice
  **/
  public String getCustomerHeadOffice() {
    return customerHeadOffice;
  }

  public void setCustomerHeadOffice(String customerHeadOffice) {
    this.customerHeadOffice = customerHeadOffice;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate customerSupplierClearingIsUsed(Boolean customerSupplierClearingIsUsed) {
    this.customerSupplierClearingIsUsed = customerSupplierClearingIsUsed;
    return this;
  }

   /**
   * Indicator: Clearing between customer and vendor ?
   * @return customerSupplierClearingIsUsed
  **/
  public Boolean isCustomerSupplierClearingIsUsed() {
    return customerSupplierClearingIsUsed;
  }

  public void setCustomerSupplierClearingIsUsed(Boolean customerSupplierClearingIsUsed) {
    this.customerSupplierClearingIsUsed = customerSupplierClearingIsUsed;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate houseBank(String houseBank) {
    this.houseBank = houseBank;
    return this;
  }

   /**
   * Short Key for a House Bank
   * @return houseBank
  **/
  public String getHouseBank() {
    return houseBank;
  }

  public void setHouseBank(String houseBank) {
    this.houseBank = houseBank;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate interestCalculationCode(String interestCalculationCode) {
    this.interestCalculationCode = interestCalculationCode;
    return this;
  }

   /**
   * Get interestCalculationCode
   * @return interestCalculationCode
  **/
  public String getInterestCalculationCode() {
    return interestCalculationCode;
  }

  public void setInterestCalculationCode(String interestCalculationCode) {
    this.interestCalculationCode = interestCalculationCode;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate interestCalculationDate(String interestCalculationDate) {
    this.interestCalculationDate = interestCalculationDate;
    return this;
  }

   /**
   * Key Date of Last Interest Calculation
   * @return interestCalculationDate
  **/
  public String getInterestCalculationDate() {
    return interestCalculationDate;
  }

  public void setInterestCalculationDate(String interestCalculationDate) {
    this.interestCalculationDate = interestCalculationDate;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate intrstCalcFrequencyInMonths(String intrstCalcFrequencyInMonths) {
    this.intrstCalcFrequencyInMonths = intrstCalcFrequencyInMonths;
    return this;
  }

   /**
   * Interest Calculation Frequency in Months
   * @return intrstCalcFrequencyInMonths
  **/
  public String getIntrstCalcFrequencyInMonths() {
    return intrstCalcFrequencyInMonths;
  }

  public void setIntrstCalcFrequencyInMonths(String intrstCalcFrequencyInMonths) {
    this.intrstCalcFrequencyInMonths = intrstCalcFrequencyInMonths;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate isToBeLocallyProcessed(Boolean isToBeLocallyProcessed) {
    this.isToBeLocallyProcessed = isToBeLocallyProcessed;
    return this;
  }

   /**
   * Indicator: Local Processing?
   * @return isToBeLocallyProcessed
  **/
  public Boolean isIsToBeLocallyProcessed() {
    return isToBeLocallyProcessed;
  }

  public void setIsToBeLocallyProcessed(Boolean isToBeLocallyProcessed) {
    this.isToBeLocallyProcessed = isToBeLocallyProcessed;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate itemIsToBePaidSeparately(Boolean itemIsToBePaidSeparately) {
    this.itemIsToBePaidSeparately = itemIsToBePaidSeparately;
    return this;
  }

   /**
   * Indicator: Pay All Items Separately?
   * @return itemIsToBePaidSeparately
  **/
  public Boolean isItemIsToBePaidSeparately() {
    return itemIsToBePaidSeparately;
  }

  public void setItemIsToBePaidSeparately(Boolean itemIsToBePaidSeparately) {
    this.itemIsToBePaidSeparately = itemIsToBePaidSeparately;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate layoutSortingRule(String layoutSortingRule) {
    this.layoutSortingRule = layoutSortingRule;
    return this;
  }

   /**
   * Key for Sorting According to Assignment Numbers
   * @return layoutSortingRule
  **/
  public String getLayoutSortingRule() {
    return layoutSortingRule;
  }

  public void setLayoutSortingRule(String layoutSortingRule) {
    this.layoutSortingRule = layoutSortingRule;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate paymentBlockingReason(String paymentBlockingReason) {
    this.paymentBlockingReason = paymentBlockingReason;
    return this;
  }

   /**
   * Block Key for Payment
   * @return paymentBlockingReason
  **/
  public String getPaymentBlockingReason() {
    return paymentBlockingReason;
  }

  public void setPaymentBlockingReason(String paymentBlockingReason) {
    this.paymentBlockingReason = paymentBlockingReason;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate paymentMethodsList(String paymentMethodsList) {
    this.paymentMethodsList = paymentMethodsList;
    return this;
  }

   /**
   * List of Respected Payment Methods
   * @return paymentMethodsList
  **/
  public String getPaymentMethodsList() {
    return paymentMethodsList;
  }

  public void setPaymentMethodsList(String paymentMethodsList) {
    this.paymentMethodsList = paymentMethodsList;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate paymentReason(String paymentReason) {
    this.paymentReason = paymentReason;
    return this;
  }

   /**
   * Get paymentReason
   * @return paymentReason
  **/
  public String getPaymentReason() {
    return paymentReason;
  }

  public void setPaymentReason(String paymentReason) {
    this.paymentReason = paymentReason;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate paymentTerms(String paymentTerms) {
    this.paymentTerms = paymentTerms;
    return this;
  }

   /**
   * Key for Terms of Payment
   * @return paymentTerms
  **/
  public String getPaymentTerms() {
    return paymentTerms;
  }

  public void setPaymentTerms(String paymentTerms) {
    this.paymentTerms = paymentTerms;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate paytAdviceIsSentbyEDI(Boolean paytAdviceIsSentbyEDI) {
    this.paytAdviceIsSentbyEDI = paytAdviceIsSentbyEDI;
    return this;
  }

   /**
   * Indicator: Send Payment Advices by EDI
   * @return paytAdviceIsSentbyEDI
  **/
  public Boolean isPaytAdviceIsSentbyEDI() {
    return paytAdviceIsSentbyEDI;
  }

  public void setPaytAdviceIsSentbyEDI(Boolean paytAdviceIsSentbyEDI) {
    this.paytAdviceIsSentbyEDI = paytAdviceIsSentbyEDI;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate physicalInventoryBlockInd(Boolean physicalInventoryBlockInd) {
    this.physicalInventoryBlockInd = physicalInventoryBlockInd;
    return this;
  }

   /**
   * Posting block for company code
   * @return physicalInventoryBlockInd
  **/
  public Boolean isPhysicalInventoryBlockInd() {
    return physicalInventoryBlockInd;
  }

  public void setPhysicalInventoryBlockInd(Boolean physicalInventoryBlockInd) {
    this.physicalInventoryBlockInd = physicalInventoryBlockInd;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate reconciliationAccount(String reconciliationAccount) {
    this.reconciliationAccount = reconciliationAccount;
    return this;
  }

   /**
   * Reconciliation Account in General Ledger
   * @return reconciliationAccount
  **/
  public String getReconciliationAccount() {
    return reconciliationAccount;
  }

  public void setReconciliationAccount(String reconciliationAccount) {
    this.reconciliationAccount = reconciliationAccount;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate recordPaymentHistoryIndicator(Boolean recordPaymentHistoryIndicator) {
    this.recordPaymentHistoryIndicator = recordPaymentHistoryIndicator;
    return this;
  }

   /**
   * Indicator: Record Payment History ?
   * @return recordPaymentHistoryIndicator
  **/
  public Boolean isRecordPaymentHistoryIndicator() {
    return recordPaymentHistoryIndicator;
  }

  public void setRecordPaymentHistoryIndicator(Boolean recordPaymentHistoryIndicator) {
    this.recordPaymentHistoryIndicator = recordPaymentHistoryIndicator;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate userAtCustomer(String userAtCustomer) {
    this.userAtCustomer = userAtCustomer;
    return this;
  }

   /**
   * Get userAtCustomer
   * @return userAtCustomer
  **/
  public String getUserAtCustomer() {
    return userAtCustomer;
  }

  public void setUserAtCustomer(String userAtCustomer) {
    this.userAtCustomer = userAtCustomer;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate deletionIndicator(Boolean deletionIndicator) {
    this.deletionIndicator = deletionIndicator;
    return this;
  }

   /**
   * Deletion Flag for Master Record (Company Code Level)
   * @return deletionIndicator
  **/
  public Boolean isDeletionIndicator() {
    return deletionIndicator;
  }

  public void setDeletionIndicator(Boolean deletionIndicator) {
    this.deletionIndicator = deletionIndicator;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate cashPlanningGroup(String cashPlanningGroup) {
    this.cashPlanningGroup = cashPlanningGroup;
    return this;
  }

   /**
   * Get cashPlanningGroup
   * @return cashPlanningGroup
  **/
  public String getCashPlanningGroup() {
    return cashPlanningGroup;
  }

  public void setCashPlanningGroup(String cashPlanningGroup) {
    this.cashPlanningGroup = cashPlanningGroup;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate knownOrNegotiatedLeave(String knownOrNegotiatedLeave) {
    this.knownOrNegotiatedLeave = knownOrNegotiatedLeave;
    return this;
  }

   /**
   * Short Key for Known/Negotiated Leave
   * @return knownOrNegotiatedLeave
  **/
  public String getKnownOrNegotiatedLeave() {
    return knownOrNegotiatedLeave;
  }

  public void setKnownOrNegotiatedLeave(String knownOrNegotiatedLeave) {
    this.knownOrNegotiatedLeave = knownOrNegotiatedLeave;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate valueAdjustmentKey(String valueAdjustmentKey) {
    this.valueAdjustmentKey = valueAdjustmentKey;
    return this;
  }

   /**
   * Value Adjustment Key
   * @return valueAdjustmentKey
  **/
  public String getValueAdjustmentKey() {
    return valueAdjustmentKey;
  }

  public void setValueAdjustmentKey(String valueAdjustmentKey) {
    this.valueAdjustmentKey = valueAdjustmentKey;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeUpdate customerAccountGroup(String customerAccountGroup) {
    this.customerAccountGroup = customerAccountGroup;
    return this;
  }

   /**
   * Customer Account Group
   * @return customerAccountGroup
  **/
  public String getCustomerAccountGroup() {
    return customerAccountGroup;
  }

  public void setCustomerAccountGroup(String customerAccountGroup) {
    this.customerAccountGroup = customerAccountGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERACustomerCompanyTypeUpdate apIBUSINESSPARTNERACustomerCompanyTypeUpdate = (APIBUSINESSPARTNERACustomerCompanyTypeUpdate) o;
    return Objects.equals(this.apARToleranceGroup, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.apARToleranceGroup) &&
        Objects.equals(this.accountByCustomer, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.accountByCustomer) &&
        Objects.equals(this.accountingClerk, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.accountingClerk) &&
        Objects.equals(this.accountingClerkFaxNumber, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.accountingClerkFaxNumber) &&
        Objects.equals(this.accountingClerkInternetAddress, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.accountingClerkInternetAddress) &&
        Objects.equals(this.accountingClerkPhoneNumber, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.accountingClerkPhoneNumber) &&
        Objects.equals(this.alternativePayerAccount, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.alternativePayerAccount) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.authorizationGroup) &&
        Objects.equals(this.collectiveInvoiceVariant, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.collectiveInvoiceVariant) &&
        Objects.equals(this.customerAccountNote, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.customerAccountNote) &&
        Objects.equals(this.customerHeadOffice, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.customerHeadOffice) &&
        Objects.equals(this.customerSupplierClearingIsUsed, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.customerSupplierClearingIsUsed) &&
        Objects.equals(this.houseBank, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.houseBank) &&
        Objects.equals(this.interestCalculationCode, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.interestCalculationCode) &&
        Objects.equals(this.interestCalculationDate, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.interestCalculationDate) &&
        Objects.equals(this.intrstCalcFrequencyInMonths, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.intrstCalcFrequencyInMonths) &&
        Objects.equals(this.isToBeLocallyProcessed, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.isToBeLocallyProcessed) &&
        Objects.equals(this.itemIsToBePaidSeparately, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.itemIsToBePaidSeparately) &&
        Objects.equals(this.layoutSortingRule, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.layoutSortingRule) &&
        Objects.equals(this.paymentBlockingReason, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.paymentBlockingReason) &&
        Objects.equals(this.paymentMethodsList, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.paymentMethodsList) &&
        Objects.equals(this.paymentReason, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.paymentReason) &&
        Objects.equals(this.paymentTerms, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.paymentTerms) &&
        Objects.equals(this.paytAdviceIsSentbyEDI, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.paytAdviceIsSentbyEDI) &&
        Objects.equals(this.physicalInventoryBlockInd, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.physicalInventoryBlockInd) &&
        Objects.equals(this.reconciliationAccount, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.reconciliationAccount) &&
        Objects.equals(this.recordPaymentHistoryIndicator, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.recordPaymentHistoryIndicator) &&
        Objects.equals(this.userAtCustomer, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.userAtCustomer) &&
        Objects.equals(this.deletionIndicator, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.deletionIndicator) &&
        Objects.equals(this.cashPlanningGroup, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.cashPlanningGroup) &&
        Objects.equals(this.knownOrNegotiatedLeave, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.knownOrNegotiatedLeave) &&
        Objects.equals(this.valueAdjustmentKey, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.valueAdjustmentKey) &&
        Objects.equals(this.customerAccountGroup, apIBUSINESSPARTNERACustomerCompanyTypeUpdate.customerAccountGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apARToleranceGroup, accountByCustomer, accountingClerk, accountingClerkFaxNumber, accountingClerkInternetAddress, accountingClerkPhoneNumber, alternativePayerAccount, authorizationGroup, collectiveInvoiceVariant, customerAccountNote, customerHeadOffice, customerSupplierClearingIsUsed, houseBank, interestCalculationCode, interestCalculationDate, intrstCalcFrequencyInMonths, isToBeLocallyProcessed, itemIsToBePaidSeparately, layoutSortingRule, paymentBlockingReason, paymentMethodsList, paymentReason, paymentTerms, paytAdviceIsSentbyEDI, physicalInventoryBlockInd, reconciliationAccount, recordPaymentHistoryIndicator, userAtCustomer, deletionIndicator, cashPlanningGroup, knownOrNegotiatedLeave, valueAdjustmentKey, customerAccountGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERACustomerCompanyTypeUpdate {\n");
    
    sb.append("    apARToleranceGroup: ").append(toIndentedString(apARToleranceGroup)).append("\n");
    sb.append("    accountByCustomer: ").append(toIndentedString(accountByCustomer)).append("\n");
    sb.append("    accountingClerk: ").append(toIndentedString(accountingClerk)).append("\n");
    sb.append("    accountingClerkFaxNumber: ").append(toIndentedString(accountingClerkFaxNumber)).append("\n");
    sb.append("    accountingClerkInternetAddress: ").append(toIndentedString(accountingClerkInternetAddress)).append("\n");
    sb.append("    accountingClerkPhoneNumber: ").append(toIndentedString(accountingClerkPhoneNumber)).append("\n");
    sb.append("    alternativePayerAccount: ").append(toIndentedString(alternativePayerAccount)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("    collectiveInvoiceVariant: ").append(toIndentedString(collectiveInvoiceVariant)).append("\n");
    sb.append("    customerAccountNote: ").append(toIndentedString(customerAccountNote)).append("\n");
    sb.append("    customerHeadOffice: ").append(toIndentedString(customerHeadOffice)).append("\n");
    sb.append("    customerSupplierClearingIsUsed: ").append(toIndentedString(customerSupplierClearingIsUsed)).append("\n");
    sb.append("    houseBank: ").append(toIndentedString(houseBank)).append("\n");
    sb.append("    interestCalculationCode: ").append(toIndentedString(interestCalculationCode)).append("\n");
    sb.append("    interestCalculationDate: ").append(toIndentedString(interestCalculationDate)).append("\n");
    sb.append("    intrstCalcFrequencyInMonths: ").append(toIndentedString(intrstCalcFrequencyInMonths)).append("\n");
    sb.append("    isToBeLocallyProcessed: ").append(toIndentedString(isToBeLocallyProcessed)).append("\n");
    sb.append("    itemIsToBePaidSeparately: ").append(toIndentedString(itemIsToBePaidSeparately)).append("\n");
    sb.append("    layoutSortingRule: ").append(toIndentedString(layoutSortingRule)).append("\n");
    sb.append("    paymentBlockingReason: ").append(toIndentedString(paymentBlockingReason)).append("\n");
    sb.append("    paymentMethodsList: ").append(toIndentedString(paymentMethodsList)).append("\n");
    sb.append("    paymentReason: ").append(toIndentedString(paymentReason)).append("\n");
    sb.append("    paymentTerms: ").append(toIndentedString(paymentTerms)).append("\n");
    sb.append("    paytAdviceIsSentbyEDI: ").append(toIndentedString(paytAdviceIsSentbyEDI)).append("\n");
    sb.append("    physicalInventoryBlockInd: ").append(toIndentedString(physicalInventoryBlockInd)).append("\n");
    sb.append("    reconciliationAccount: ").append(toIndentedString(reconciliationAccount)).append("\n");
    sb.append("    recordPaymentHistoryIndicator: ").append(toIndentedString(recordPaymentHistoryIndicator)).append("\n");
    sb.append("    userAtCustomer: ").append(toIndentedString(userAtCustomer)).append("\n");
    sb.append("    deletionIndicator: ").append(toIndentedString(deletionIndicator)).append("\n");
    sb.append("    cashPlanningGroup: ").append(toIndentedString(cashPlanningGroup)).append("\n");
    sb.append("    knownOrNegotiatedLeave: ").append(toIndentedString(knownOrNegotiatedLeave)).append("\n");
    sb.append("    valueAdjustmentKey: ").append(toIndentedString(valueAdjustmentKey)).append("\n");
    sb.append("    customerAccountGroup: ").append(toIndentedString(customerAccountGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
