/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERAAddressHomePageURLType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERAAddressHomePageURLType {
  @JsonProperty("AddressID")
  private String addressID = null;

  @JsonProperty("Person")
  private String person = null;

  @JsonProperty("OrdinalNumber")
  private String ordinalNumber = null;

  @JsonProperty("ValidityStartDate")
  private String validityStartDate = null;

  @JsonProperty("IsDefaultURLAddress")
  private Boolean isDefaultURLAddress = null;

  @JsonProperty("SearchURLAddress")
  private String searchURLAddress = null;

  @JsonProperty("AddressCommunicationRemarkText")
  private String addressCommunicationRemarkText = null;

  @JsonProperty("URLFieldLength")
  private Integer urLFieldLength = null;

  @JsonProperty("WebsiteURL")
  private String websiteURL = null;

  public APIBUSINESSPARTNERAAddressHomePageURLType addressID(String addressID) {
    this.addressID = addressID;
    return this;
  }

   /**
   * Get addressID
   * @return addressID
  **/
  public String getAddressID() {
    return addressID;
  }

  public void setAddressID(String addressID) {
    this.addressID = addressID;
  }

  public APIBUSINESSPARTNERAAddressHomePageURLType person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public APIBUSINESSPARTNERAAddressHomePageURLType ordinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
    return this;
  }

   /**
   * Get ordinalNumber
   * @return ordinalNumber
  **/
  public String getOrdinalNumber() {
    return ordinalNumber;
  }

  public void setOrdinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
  }

  public APIBUSINESSPARTNERAAddressHomePageURLType validityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
    return this;
  }

   /**
   * Valid-from date - in current Release only 00010101 possible
   * @return validityStartDate
  **/
  public String getValidityStartDate() {
    return validityStartDate;
  }

  public void setValidityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
  }

  public APIBUSINESSPARTNERAAddressHomePageURLType isDefaultURLAddress(Boolean isDefaultURLAddress) {
    this.isDefaultURLAddress = isDefaultURLAddress;
    return this;
  }

   /**
   * Flag: this address is the default address
   * @return isDefaultURLAddress
  **/
  public Boolean isIsDefaultURLAddress() {
    return isDefaultURLAddress;
  }

  public void setIsDefaultURLAddress(Boolean isDefaultURLAddress) {
    this.isDefaultURLAddress = isDefaultURLAddress;
  }

  public APIBUSINESSPARTNERAAddressHomePageURLType searchURLAddress(String searchURLAddress) {
    this.searchURLAddress = searchURLAddress;
    return this;
  }

   /**
   * URI address search field
   * @return searchURLAddress
  **/
  public String getSearchURLAddress() {
    return searchURLAddress;
  }

  public void setSearchURLAddress(String searchURLAddress) {
    this.searchURLAddress = searchURLAddress;
  }

  public APIBUSINESSPARTNERAAddressHomePageURLType addressCommunicationRemarkText(String addressCommunicationRemarkText) {
    this.addressCommunicationRemarkText = addressCommunicationRemarkText;
    return this;
  }

   /**
   * Communication link notes
   * @return addressCommunicationRemarkText
  **/
  public String getAddressCommunicationRemarkText() {
    return addressCommunicationRemarkText;
  }

  public void setAddressCommunicationRemarkText(String addressCommunicationRemarkText) {
    this.addressCommunicationRemarkText = addressCommunicationRemarkText;
  }

  public APIBUSINESSPARTNERAAddressHomePageURLType urLFieldLength(Integer urLFieldLength) {
    this.urLFieldLength = urLFieldLength;
    return this;
  }

   /**
   * URI field length
   * @return urLFieldLength
  **/
  public Integer getUrLFieldLength() {
    return urLFieldLength;
  }

  public void setUrLFieldLength(Integer urLFieldLength) {
    this.urLFieldLength = urLFieldLength;
  }

  public APIBUSINESSPARTNERAAddressHomePageURLType websiteURL(String websiteURL) {
    this.websiteURL = websiteURL;
    return this;
  }

   /**
   * Universal Resource Identifier (URI)
   * @return websiteURL
  **/
  public String getWebsiteURL() {
    return websiteURL;
  }

  public void setWebsiteURL(String websiteURL) {
    this.websiteURL = websiteURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERAAddressHomePageURLType apIBUSINESSPARTNERAAddressHomePageURLType = (APIBUSINESSPARTNERAAddressHomePageURLType) o;
    return Objects.equals(this.addressID, apIBUSINESSPARTNERAAddressHomePageURLType.addressID) &&
        Objects.equals(this.person, apIBUSINESSPARTNERAAddressHomePageURLType.person) &&
        Objects.equals(this.ordinalNumber, apIBUSINESSPARTNERAAddressHomePageURLType.ordinalNumber) &&
        Objects.equals(this.validityStartDate, apIBUSINESSPARTNERAAddressHomePageURLType.validityStartDate) &&
        Objects.equals(this.isDefaultURLAddress, apIBUSINESSPARTNERAAddressHomePageURLType.isDefaultURLAddress) &&
        Objects.equals(this.searchURLAddress, apIBUSINESSPARTNERAAddressHomePageURLType.searchURLAddress) &&
        Objects.equals(this.addressCommunicationRemarkText, apIBUSINESSPARTNERAAddressHomePageURLType.addressCommunicationRemarkText) &&
        Objects.equals(this.urLFieldLength, apIBUSINESSPARTNERAAddressHomePageURLType.urLFieldLength) &&
        Objects.equals(this.websiteURL, apIBUSINESSPARTNERAAddressHomePageURLType.websiteURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressID, person, ordinalNumber, validityStartDate, isDefaultURLAddress, searchURLAddress, addressCommunicationRemarkText, urLFieldLength, websiteURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERAAddressHomePageURLType {\n");
    
    sb.append("    addressID: ").append(toIndentedString(addressID)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    ordinalNumber: ").append(toIndentedString(ordinalNumber)).append("\n");
    sb.append("    validityStartDate: ").append(toIndentedString(validityStartDate)).append("\n");
    sb.append("    isDefaultURLAddress: ").append(toIndentedString(isDefaultURLAddress)).append("\n");
    sb.append("    searchURLAddress: ").append(toIndentedString(searchURLAddress)).append("\n");
    sb.append("    addressCommunicationRemarkText: ").append(toIndentedString(addressCommunicationRemarkText)).append("\n");
    sb.append("    urLFieldLength: ").append(toIndentedString(urLFieldLength)).append("\n");
    sb.append("    websiteURL: ").append(toIndentedString(websiteURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
