/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABPCreditWorthinessType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABPCreditWorthinessType {
  @JsonProperty("BusinessPartner")
  private String businessPartner = null;

  @JsonProperty("BusPartCreditStanding")
  private String busPartCreditStanding = null;

  @JsonProperty("BPCreditStandingStatus")
  private String bpCreditStandingStatus = null;

  @JsonProperty("CreditRatingAgency")
  private String creditRatingAgency = null;

  @JsonProperty("BPCreditStandingComment")
  private String bpCreditStandingComment = null;

  @JsonProperty("BPCreditStandingDate")
  private String bpCreditStandingDate = null;

  @JsonProperty("BPCreditStandingRating")
  private String bpCreditStandingRating = null;

  @JsonProperty("BPLegalProceedingStatus")
  private String bpLegalProceedingStatus = null;

  @JsonProperty("BPLglProceedingInitiationDate")
  private String bpLglProceedingInitiationDate = null;

  @JsonProperty("BusinessPartnerIsUnderOath")
  private Boolean businessPartnerIsUnderOath = null;

  @JsonProperty("BusinessPartnerOathDate")
  private String businessPartnerOathDate = null;

  @JsonProperty("BusinessPartnerIsBankrupt")
  private Boolean businessPartnerIsBankrupt = null;

  @JsonProperty("BusinessPartnerBankruptcyDate")
  private String businessPartnerBankruptcyDate = null;

  @JsonProperty("BPForeclosureIsInitiated")
  private Boolean bpForeclosureIsInitiated = null;

  @JsonProperty("BPForeclosureDate")
  private String bpForeclosureDate = null;

  @JsonProperty("BPCrdtWrthnssAccessChkIsActive")
  private String bpCrdtWrthnssAccessChkIsActive = null;

  public APIBUSINESSPARTNERABPCreditWorthinessType businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartner
  **/
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType busPartCreditStanding(String busPartCreditStanding) {
    this.busPartCreditStanding = busPartCreditStanding;
    return this;
  }

   /**
   * Get busPartCreditStanding
   * @return busPartCreditStanding
  **/
  public String getBusPartCreditStanding() {
    return busPartCreditStanding;
  }

  public void setBusPartCreditStanding(String busPartCreditStanding) {
    this.busPartCreditStanding = busPartCreditStanding;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType bpCreditStandingStatus(String bpCreditStandingStatus) {
    this.bpCreditStandingStatus = bpCreditStandingStatus;
    return this;
  }

   /**
   * Status of Credit Standing Information
   * @return bpCreditStandingStatus
  **/
  public String getBpCreditStandingStatus() {
    return bpCreditStandingStatus;
  }

  public void setBpCreditStandingStatus(String bpCreditStandingStatus) {
    this.bpCreditStandingStatus = bpCreditStandingStatus;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType creditRatingAgency(String creditRatingAgency) {
    this.creditRatingAgency = creditRatingAgency;
    return this;
  }

   /**
   * Institute Providing Credit Standing Information
   * @return creditRatingAgency
  **/
  public String getCreditRatingAgency() {
    return creditRatingAgency;
  }

  public void setCreditRatingAgency(String creditRatingAgency) {
    this.creditRatingAgency = creditRatingAgency;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType bpCreditStandingComment(String bpCreditStandingComment) {
    this.bpCreditStandingComment = bpCreditStandingComment;
    return this;
  }

   /**
   * Additional Credit Standing Information
   * @return bpCreditStandingComment
  **/
  public String getBpCreditStandingComment() {
    return bpCreditStandingComment;
  }

  public void setBpCreditStandingComment(String bpCreditStandingComment) {
    this.bpCreditStandingComment = bpCreditStandingComment;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType bpCreditStandingDate(String bpCreditStandingDate) {
    this.bpCreditStandingDate = bpCreditStandingDate;
    return this;
  }

   /**
   * Date of Credit Standing Information
   * @return bpCreditStandingDate
  **/
  public String getBpCreditStandingDate() {
    return bpCreditStandingDate;
  }

  public void setBpCreditStandingDate(String bpCreditStandingDate) {
    this.bpCreditStandingDate = bpCreditStandingDate;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType bpCreditStandingRating(String bpCreditStandingRating) {
    this.bpCreditStandingRating = bpCreditStandingRating;
    return this;
  }

   /**
   * Get bpCreditStandingRating
   * @return bpCreditStandingRating
  **/
  public String getBpCreditStandingRating() {
    return bpCreditStandingRating;
  }

  public void setBpCreditStandingRating(String bpCreditStandingRating) {
    this.bpCreditStandingRating = bpCreditStandingRating;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType bpLegalProceedingStatus(String bpLegalProceedingStatus) {
    this.bpLegalProceedingStatus = bpLegalProceedingStatus;
    return this;
  }

   /**
   * Status of Legal Proceedings
   * @return bpLegalProceedingStatus
  **/
  public String getBpLegalProceedingStatus() {
    return bpLegalProceedingStatus;
  }

  public void setBpLegalProceedingStatus(String bpLegalProceedingStatus) {
    this.bpLegalProceedingStatus = bpLegalProceedingStatus;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType bpLglProceedingInitiationDate(String bpLglProceedingInitiationDate) {
    this.bpLglProceedingInitiationDate = bpLglProceedingInitiationDate;
    return this;
  }

   /**
   * Date of Initiation of Legal Proceedings
   * @return bpLglProceedingInitiationDate
  **/
  public String getBpLglProceedingInitiationDate() {
    return bpLglProceedingInitiationDate;
  }

  public void setBpLglProceedingInitiationDate(String bpLglProceedingInitiationDate) {
    this.bpLglProceedingInitiationDate = bpLglProceedingInitiationDate;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType businessPartnerIsUnderOath(Boolean businessPartnerIsUnderOath) {
    this.businessPartnerIsUnderOath = businessPartnerIsUnderOath;
    return this;
  }

   /**
   * Get businessPartnerIsUnderOath
   * @return businessPartnerIsUnderOath
  **/
  public Boolean isBusinessPartnerIsUnderOath() {
    return businessPartnerIsUnderOath;
  }

  public void setBusinessPartnerIsUnderOath(Boolean businessPartnerIsUnderOath) {
    this.businessPartnerIsUnderOath = businessPartnerIsUnderOath;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType businessPartnerOathDate(String businessPartnerOathDate) {
    this.businessPartnerOathDate = businessPartnerOathDate;
    return this;
  }

   /**
   * Get businessPartnerOathDate
   * @return businessPartnerOathDate
  **/
  public String getBusinessPartnerOathDate() {
    return businessPartnerOathDate;
  }

  public void setBusinessPartnerOathDate(String businessPartnerOathDate) {
    this.businessPartnerOathDate = businessPartnerOathDate;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType businessPartnerIsBankrupt(Boolean businessPartnerIsBankrupt) {
    this.businessPartnerIsBankrupt = businessPartnerIsBankrupt;
    return this;
  }

   /**
   * Launch Bankruptcy Proceedings
   * @return businessPartnerIsBankrupt
  **/
  public Boolean isBusinessPartnerIsBankrupt() {
    return businessPartnerIsBankrupt;
  }

  public void setBusinessPartnerIsBankrupt(Boolean businessPartnerIsBankrupt) {
    this.businessPartnerIsBankrupt = businessPartnerIsBankrupt;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType businessPartnerBankruptcyDate(String businessPartnerBankruptcyDate) {
    this.businessPartnerBankruptcyDate = businessPartnerBankruptcyDate;
    return this;
  }

   /**
   * Commencement Date of Bankruptcy Proceedings
   * @return businessPartnerBankruptcyDate
  **/
  public String getBusinessPartnerBankruptcyDate() {
    return businessPartnerBankruptcyDate;
  }

  public void setBusinessPartnerBankruptcyDate(String businessPartnerBankruptcyDate) {
    this.businessPartnerBankruptcyDate = businessPartnerBankruptcyDate;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType bpForeclosureIsInitiated(Boolean bpForeclosureIsInitiated) {
    this.bpForeclosureIsInitiated = bpForeclosureIsInitiated;
    return this;
  }

   /**
   * Get bpForeclosureIsInitiated
   * @return bpForeclosureIsInitiated
  **/
  public Boolean isBpForeclosureIsInitiated() {
    return bpForeclosureIsInitiated;
  }

  public void setBpForeclosureIsInitiated(Boolean bpForeclosureIsInitiated) {
    this.bpForeclosureIsInitiated = bpForeclosureIsInitiated;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType bpForeclosureDate(String bpForeclosureDate) {
    this.bpForeclosureDate = bpForeclosureDate;
    return this;
  }

   /**
   * Get bpForeclosureDate
   * @return bpForeclosureDate
  **/
  public String getBpForeclosureDate() {
    return bpForeclosureDate;
  }

  public void setBpForeclosureDate(String bpForeclosureDate) {
    this.bpForeclosureDate = bpForeclosureDate;
  }

  public APIBUSINESSPARTNERABPCreditWorthinessType bpCrdtWrthnssAccessChkIsActive(String bpCrdtWrthnssAccessChkIsActive) {
    this.bpCrdtWrthnssAccessChkIsActive = bpCrdtWrthnssAccessChkIsActive;
    return this;
  }

   /**
   * Get bpCrdtWrthnssAccessChkIsActive
   * @return bpCrdtWrthnssAccessChkIsActive
  **/
  public String getBpCrdtWrthnssAccessChkIsActive() {
    return bpCrdtWrthnssAccessChkIsActive;
  }

  public void setBpCrdtWrthnssAccessChkIsActive(String bpCrdtWrthnssAccessChkIsActive) {
    this.bpCrdtWrthnssAccessChkIsActive = bpCrdtWrthnssAccessChkIsActive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABPCreditWorthinessType apIBUSINESSPARTNERABPCreditWorthinessType = (APIBUSINESSPARTNERABPCreditWorthinessType) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABPCreditWorthinessType.businessPartner) &&
        Objects.equals(this.busPartCreditStanding, apIBUSINESSPARTNERABPCreditWorthinessType.busPartCreditStanding) &&
        Objects.equals(this.bpCreditStandingStatus, apIBUSINESSPARTNERABPCreditWorthinessType.bpCreditStandingStatus) &&
        Objects.equals(this.creditRatingAgency, apIBUSINESSPARTNERABPCreditWorthinessType.creditRatingAgency) &&
        Objects.equals(this.bpCreditStandingComment, apIBUSINESSPARTNERABPCreditWorthinessType.bpCreditStandingComment) &&
        Objects.equals(this.bpCreditStandingDate, apIBUSINESSPARTNERABPCreditWorthinessType.bpCreditStandingDate) &&
        Objects.equals(this.bpCreditStandingRating, apIBUSINESSPARTNERABPCreditWorthinessType.bpCreditStandingRating) &&
        Objects.equals(this.bpLegalProceedingStatus, apIBUSINESSPARTNERABPCreditWorthinessType.bpLegalProceedingStatus) &&
        Objects.equals(this.bpLglProceedingInitiationDate, apIBUSINESSPARTNERABPCreditWorthinessType.bpLglProceedingInitiationDate) &&
        Objects.equals(this.businessPartnerIsUnderOath, apIBUSINESSPARTNERABPCreditWorthinessType.businessPartnerIsUnderOath) &&
        Objects.equals(this.businessPartnerOathDate, apIBUSINESSPARTNERABPCreditWorthinessType.businessPartnerOathDate) &&
        Objects.equals(this.businessPartnerIsBankrupt, apIBUSINESSPARTNERABPCreditWorthinessType.businessPartnerIsBankrupt) &&
        Objects.equals(this.businessPartnerBankruptcyDate, apIBUSINESSPARTNERABPCreditWorthinessType.businessPartnerBankruptcyDate) &&
        Objects.equals(this.bpForeclosureIsInitiated, apIBUSINESSPARTNERABPCreditWorthinessType.bpForeclosureIsInitiated) &&
        Objects.equals(this.bpForeclosureDate, apIBUSINESSPARTNERABPCreditWorthinessType.bpForeclosureDate) &&
        Objects.equals(this.bpCrdtWrthnssAccessChkIsActive, apIBUSINESSPARTNERABPCreditWorthinessType.bpCrdtWrthnssAccessChkIsActive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, busPartCreditStanding, bpCreditStandingStatus, creditRatingAgency, bpCreditStandingComment, bpCreditStandingDate, bpCreditStandingRating, bpLegalProceedingStatus, bpLglProceedingInitiationDate, businessPartnerIsUnderOath, businessPartnerOathDate, businessPartnerIsBankrupt, businessPartnerBankruptcyDate, bpForeclosureIsInitiated, bpForeclosureDate, bpCrdtWrthnssAccessChkIsActive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABPCreditWorthinessType {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    busPartCreditStanding: ").append(toIndentedString(busPartCreditStanding)).append("\n");
    sb.append("    bpCreditStandingStatus: ").append(toIndentedString(bpCreditStandingStatus)).append("\n");
    sb.append("    creditRatingAgency: ").append(toIndentedString(creditRatingAgency)).append("\n");
    sb.append("    bpCreditStandingComment: ").append(toIndentedString(bpCreditStandingComment)).append("\n");
    sb.append("    bpCreditStandingDate: ").append(toIndentedString(bpCreditStandingDate)).append("\n");
    sb.append("    bpCreditStandingRating: ").append(toIndentedString(bpCreditStandingRating)).append("\n");
    sb.append("    bpLegalProceedingStatus: ").append(toIndentedString(bpLegalProceedingStatus)).append("\n");
    sb.append("    bpLglProceedingInitiationDate: ").append(toIndentedString(bpLglProceedingInitiationDate)).append("\n");
    sb.append("    businessPartnerIsUnderOath: ").append(toIndentedString(businessPartnerIsUnderOath)).append("\n");
    sb.append("    businessPartnerOathDate: ").append(toIndentedString(businessPartnerOathDate)).append("\n");
    sb.append("    businessPartnerIsBankrupt: ").append(toIndentedString(businessPartnerIsBankrupt)).append("\n");
    sb.append("    businessPartnerBankruptcyDate: ").append(toIndentedString(businessPartnerBankruptcyDate)).append("\n");
    sb.append("    bpForeclosureIsInitiated: ").append(toIndentedString(bpForeclosureIsInitiated)).append("\n");
    sb.append("    bpForeclosureDate: ").append(toIndentedString(bpForeclosureDate)).append("\n");
    sb.append("    bpCrdtWrthnssAccessChkIsActive: ").append(toIndentedString(bpCrdtWrthnssAccessChkIsActive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
