/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate {
  @JsonProperty("BusinessPartnerRatingGrade")
  private String businessPartnerRatingGrade = null;

  @JsonProperty("BusinessPartnerRatingTrend")
  private String businessPartnerRatingTrend = null;

  @JsonProperty("BPRatingValidityStartDate")
  private String bpRatingValidityStartDate = null;

  @JsonProperty("BPRatingCreationDate")
  private String bpRatingCreationDate = null;

  @JsonProperty("BusinessPartnerRatingComment")
  private String businessPartnerRatingComment = null;

  @JsonProperty("BusinessPartnerRatingIsAllowed")
  private Boolean businessPartnerRatingIsAllowed = null;

  @JsonProperty("BPRatingIsValidOnKeyDate")
  private Boolean bpRatingIsValidOnKeyDate = null;

  @JsonProperty("BusinessPartnerRatingKeyDate")
  private String businessPartnerRatingKeyDate = null;

  @JsonProperty("BusinessPartnerRatingIsExpired")
  private Boolean businessPartnerRatingIsExpired = null;

  @JsonProperty("BPRatingLongComment")
  private String bpRatingLongComment = null;

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate businessPartnerRatingGrade(String businessPartnerRatingGrade) {
    this.businessPartnerRatingGrade = businessPartnerRatingGrade;
    return this;
  }

   /**
   * Get businessPartnerRatingGrade
   * @return businessPartnerRatingGrade
  **/
  public String getBusinessPartnerRatingGrade() {
    return businessPartnerRatingGrade;
  }

  public void setBusinessPartnerRatingGrade(String businessPartnerRatingGrade) {
    this.businessPartnerRatingGrade = businessPartnerRatingGrade;
  }

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate businessPartnerRatingTrend(String businessPartnerRatingTrend) {
    this.businessPartnerRatingTrend = businessPartnerRatingTrend;
    return this;
  }

   /**
   * Get businessPartnerRatingTrend
   * @return businessPartnerRatingTrend
  **/
  public String getBusinessPartnerRatingTrend() {
    return businessPartnerRatingTrend;
  }

  public void setBusinessPartnerRatingTrend(String businessPartnerRatingTrend) {
    this.businessPartnerRatingTrend = businessPartnerRatingTrend;
  }

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate bpRatingValidityStartDate(String bpRatingValidityStartDate) {
    this.bpRatingValidityStartDate = bpRatingValidityStartDate;
    return this;
  }

   /**
   * Valid-from Date for Rating
   * @return bpRatingValidityStartDate
  **/
  public String getBpRatingValidityStartDate() {
    return bpRatingValidityStartDate;
  }

  public void setBpRatingValidityStartDate(String bpRatingValidityStartDate) {
    this.bpRatingValidityStartDate = bpRatingValidityStartDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate bpRatingCreationDate(String bpRatingCreationDate) {
    this.bpRatingCreationDate = bpRatingCreationDate;
    return this;
  }

   /**
   * Entered-on Date for Rating
   * @return bpRatingCreationDate
  **/
  public String getBpRatingCreationDate() {
    return bpRatingCreationDate;
  }

  public void setBpRatingCreationDate(String bpRatingCreationDate) {
    this.bpRatingCreationDate = bpRatingCreationDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate businessPartnerRatingComment(String businessPartnerRatingComment) {
    this.businessPartnerRatingComment = businessPartnerRatingComment;
    return this;
  }

   /**
   * Text for Ratings
   * @return businessPartnerRatingComment
  **/
  public String getBusinessPartnerRatingComment() {
    return businessPartnerRatingComment;
  }

  public void setBusinessPartnerRatingComment(String businessPartnerRatingComment) {
    this.businessPartnerRatingComment = businessPartnerRatingComment;
  }

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate businessPartnerRatingIsAllowed(Boolean businessPartnerRatingIsAllowed) {
    this.businessPartnerRatingIsAllowed = businessPartnerRatingIsAllowed;
    return this;
  }

   /**
   * Get businessPartnerRatingIsAllowed
   * @return businessPartnerRatingIsAllowed
  **/
  public Boolean isBusinessPartnerRatingIsAllowed() {
    return businessPartnerRatingIsAllowed;
  }

  public void setBusinessPartnerRatingIsAllowed(Boolean businessPartnerRatingIsAllowed) {
    this.businessPartnerRatingIsAllowed = businessPartnerRatingIsAllowed;
  }

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate bpRatingIsValidOnKeyDate(Boolean bpRatingIsValidOnKeyDate) {
    this.bpRatingIsValidOnKeyDate = bpRatingIsValidOnKeyDate;
    return this;
  }

   /**
   * Business Partner Rating is valid on Key Date
   * @return bpRatingIsValidOnKeyDate
  **/
  public Boolean isBpRatingIsValidOnKeyDate() {
    return bpRatingIsValidOnKeyDate;
  }

  public void setBpRatingIsValidOnKeyDate(Boolean bpRatingIsValidOnKeyDate) {
    this.bpRatingIsValidOnKeyDate = bpRatingIsValidOnKeyDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate businessPartnerRatingKeyDate(String businessPartnerRatingKeyDate) {
    this.businessPartnerRatingKeyDate = businessPartnerRatingKeyDate;
    return this;
  }

   /**
   * Key Date of Accessing Business Partner Rating Data
   * @return businessPartnerRatingKeyDate
  **/
  public String getBusinessPartnerRatingKeyDate() {
    return businessPartnerRatingKeyDate;
  }

  public void setBusinessPartnerRatingKeyDate(String businessPartnerRatingKeyDate) {
    this.businessPartnerRatingKeyDate = businessPartnerRatingKeyDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate businessPartnerRatingIsExpired(Boolean businessPartnerRatingIsExpired) {
    this.businessPartnerRatingIsExpired = businessPartnerRatingIsExpired;
    return this;
  }

   /**
   * Rating Validity is Expired according to Permitted Period
   * @return businessPartnerRatingIsExpired
  **/
  public Boolean isBusinessPartnerRatingIsExpired() {
    return businessPartnerRatingIsExpired;
  }

  public void setBusinessPartnerRatingIsExpired(Boolean businessPartnerRatingIsExpired) {
    this.businessPartnerRatingIsExpired = businessPartnerRatingIsExpired;
  }

  public APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate bpRatingLongComment(String bpRatingLongComment) {
    this.bpRatingLongComment = bpRatingLongComment;
    return this;
  }

   /**
   * Longtext for Rating
   * @return bpRatingLongComment
  **/
  public String getBpRatingLongComment() {
    return bpRatingLongComment;
  }

  public void setBpRatingLongComment(String bpRatingLongComment) {
    this.bpRatingLongComment = bpRatingLongComment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate = (APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate) o;
    return Objects.equals(this.businessPartnerRatingGrade, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.businessPartnerRatingGrade) &&
        Objects.equals(this.businessPartnerRatingTrend, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.businessPartnerRatingTrend) &&
        Objects.equals(this.bpRatingValidityStartDate, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.bpRatingValidityStartDate) &&
        Objects.equals(this.bpRatingCreationDate, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.bpRatingCreationDate) &&
        Objects.equals(this.businessPartnerRatingComment, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.businessPartnerRatingComment) &&
        Objects.equals(this.businessPartnerRatingIsAllowed, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.businessPartnerRatingIsAllowed) &&
        Objects.equals(this.bpRatingIsValidOnKeyDate, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.bpRatingIsValidOnKeyDate) &&
        Objects.equals(this.businessPartnerRatingKeyDate, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.businessPartnerRatingKeyDate) &&
        Objects.equals(this.businessPartnerRatingIsExpired, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.businessPartnerRatingIsExpired) &&
        Objects.equals(this.bpRatingLongComment, apIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate.bpRatingLongComment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartnerRatingGrade, businessPartnerRatingTrend, bpRatingValidityStartDate, bpRatingCreationDate, businessPartnerRatingComment, businessPartnerRatingIsAllowed, bpRatingIsValidOnKeyDate, businessPartnerRatingKeyDate, businessPartnerRatingIsExpired, bpRatingLongComment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerRatingTypeUpdate {\n");
    
    sb.append("    businessPartnerRatingGrade: ").append(toIndentedString(businessPartnerRatingGrade)).append("\n");
    sb.append("    businessPartnerRatingTrend: ").append(toIndentedString(businessPartnerRatingTrend)).append("\n");
    sb.append("    bpRatingValidityStartDate: ").append(toIndentedString(bpRatingValidityStartDate)).append("\n");
    sb.append("    bpRatingCreationDate: ").append(toIndentedString(bpRatingCreationDate)).append("\n");
    sb.append("    businessPartnerRatingComment: ").append(toIndentedString(businessPartnerRatingComment)).append("\n");
    sb.append("    businessPartnerRatingIsAllowed: ").append(toIndentedString(businessPartnerRatingIsAllowed)).append("\n");
    sb.append("    bpRatingIsValidOnKeyDate: ").append(toIndentedString(bpRatingIsValidOnKeyDate)).append("\n");
    sb.append("    businessPartnerRatingKeyDate: ").append(toIndentedString(businessPartnerRatingKeyDate)).append("\n");
    sb.append("    businessPartnerRatingIsExpired: ").append(toIndentedString(businessPartnerRatingIsExpired)).append("\n");
    sb.append("    bpRatingLongComment: ").append(toIndentedString(bpRatingLongComment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
