/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate {
  @JsonProperty("BusinessPartner")
  private String businessPartner = null;

  @JsonProperty("BusinessPartnerFiscalYear")
  private String businessPartnerFiscalYear = null;

  @JsonProperty("BPBalanceSheetCurrency")
  private String bpBalanceSheetCurrency = null;

  @JsonProperty("BPAnnualStockholderMeetingDate")
  private String bpAnnualStockholderMeetingDate = null;

  @JsonProperty("BPFiscalYearStartDate")
  private String bpFiscalYearStartDate = null;

  @JsonProperty("BPFiscalYearEndDate")
  private String bpFiscalYearEndDate = null;

  @JsonProperty("BPFiscalYearIsClosed")
  private Boolean bpFiscalYearIsClosed = null;

  @JsonProperty("BPFiscalYearClosingDate")
  private String bpFiscalYearClosingDate = null;

  @JsonProperty("BPFsclYrCnsldtdFinStatementDte")
  private String bpFsclYrCnsldtdFinStatementDte = null;

  @JsonProperty("BPCapitalStockAmtInBalShtCrcy")
  private String bpCapitalStockAmtInBalShtCrcy = null;

  @JsonProperty("BPIssdStockCptlAmtInBalShtCrcy")
  private String bpIssdStockCptlAmtInBalShtCrcy = null;

  @JsonProperty("BPPartcipnCertAmtInBalShtCrcy")
  private String bpPartcipnCertAmtInBalShtCrcy = null;

  @JsonProperty("BPEquityCapitalAmtInBalShtCrcy")
  private String bpEquityCapitalAmtInBalShtCrcy = null;

  @JsonProperty("BPGrossPremiumAmtInBalShtCrcy")
  private String bpGrossPremiumAmtInBalShtCrcy = null;

  @JsonProperty("BPNetPremiumAmtInBalShtCrcy")
  private String bpNetPremiumAmtInBalShtCrcy = null;

  @JsonProperty("BPAnnualSalesAmtInBalShtCrcy")
  private String bpAnnualSalesAmtInBalShtCrcy = null;

  @JsonProperty("BPAnnualNetIncAmtInBalShtCrcy")
  private String bpAnnualNetIncAmtInBalShtCrcy = null;

  @JsonProperty("BPDividendDistrAmtInBalShtCrcy")
  private String bpDividendDistrAmtInBalShtCrcy = null;

  @JsonProperty("BPDebtRatioInYears")
  private String bpDebtRatioInYears = null;

  @JsonProperty("BPAnnualPnLAmtInBalShtCrcy")
  private String bpAnnualPnLAmtInBalShtCrcy = null;

  @JsonProperty("BPBalSheetTotalAmtInBalShtCrcy")
  private String bpBalSheetTotalAmtInBalShtCrcy = null;

  @JsonProperty("BPNumberOfEmployees")
  private String bpNumberOfEmployees = null;

  @JsonProperty("BPCptlReserveAmtInBalShtCrcy")
  private String bpCptlReserveAmtInBalShtCrcy = null;

  @JsonProperty("BPLglRevnRsrvAmtInBalShtCrcy")
  private String bpLglRevnRsrvAmtInBalShtCrcy = null;

  @JsonProperty("RevnRsrvOwnStkAmtInBalShtCrcy")
  private String revnRsrvOwnStkAmtInBalShtCrcy = null;

  @JsonProperty("BPStatryReserveAmtInBalShtCrcy")
  private String bpStatryReserveAmtInBalShtCrcy = null;

  @JsonProperty("BPOthRevnRsrvAmtInBalShtCrcy")
  private String bpOthRevnRsrvAmtInBalShtCrcy = null;

  @JsonProperty("BPPnLCarryfwdAmtInBalShtCrcy")
  private String bpPnLCarryfwdAmtInBalShtCrcy = null;

  @JsonProperty("BPSuborddLbltyAmtInBalShtCrcy")
  private String bpSuborddLbltyAmtInBalShtCrcy = null;

  @JsonProperty("BPRetOnTotalCptlEmpldInPercent")
  private String bpRetOnTotalCptlEmpldInPercent = null;

  @JsonProperty("BPDebtClearancePeriodInYears")
  private String bpDebtClearancePeriodInYears = null;

  @JsonProperty("BPFinancingCoeffInPercent")
  private String bpFinancingCoeffInPercent = null;

  @JsonProperty("BPEquityRatioInPercent")
  private String bpEquityRatioInPercent = null;

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartner
  **/
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate businessPartnerFiscalYear(String businessPartnerFiscalYear) {
    this.businessPartnerFiscalYear = businessPartnerFiscalYear;
    return this;
  }

   /**
   * Get businessPartnerFiscalYear
   * @return businessPartnerFiscalYear
  **/
  public String getBusinessPartnerFiscalYear() {
    return businessPartnerFiscalYear;
  }

  public void setBusinessPartnerFiscalYear(String businessPartnerFiscalYear) {
    this.businessPartnerFiscalYear = businessPartnerFiscalYear;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpBalanceSheetCurrency(String bpBalanceSheetCurrency) {
    this.bpBalanceSheetCurrency = bpBalanceSheetCurrency;
    return this;
  }

   /**
   * Balance Sheet Currency
   * @return bpBalanceSheetCurrency
  **/
  public String getBpBalanceSheetCurrency() {
    return bpBalanceSheetCurrency;
  }

  public void setBpBalanceSheetCurrency(String bpBalanceSheetCurrency) {
    this.bpBalanceSheetCurrency = bpBalanceSheetCurrency;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpAnnualStockholderMeetingDate(String bpAnnualStockholderMeetingDate) {
    this.bpAnnualStockholderMeetingDate = bpAnnualStockholderMeetingDate;
    return this;
  }

   /**
   * Date of Annual Stockholders Meeting
   * @return bpAnnualStockholderMeetingDate
  **/
  public String getBpAnnualStockholderMeetingDate() {
    return bpAnnualStockholderMeetingDate;
  }

  public void setBpAnnualStockholderMeetingDate(String bpAnnualStockholderMeetingDate) {
    this.bpAnnualStockholderMeetingDate = bpAnnualStockholderMeetingDate;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpFiscalYearStartDate(String bpFiscalYearStartDate) {
    this.bpFiscalYearStartDate = bpFiscalYearStartDate;
    return this;
  }

   /**
   * Fiscal Year Start Date
   * @return bpFiscalYearStartDate
  **/
  public String getBpFiscalYearStartDate() {
    return bpFiscalYearStartDate;
  }

  public void setBpFiscalYearStartDate(String bpFiscalYearStartDate) {
    this.bpFiscalYearStartDate = bpFiscalYearStartDate;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpFiscalYearEndDate(String bpFiscalYearEndDate) {
    this.bpFiscalYearEndDate = bpFiscalYearEndDate;
    return this;
  }

   /**
   * Fiscal Year End Date
   * @return bpFiscalYearEndDate
  **/
  public String getBpFiscalYearEndDate() {
    return bpFiscalYearEndDate;
  }

  public void setBpFiscalYearEndDate(String bpFiscalYearEndDate) {
    this.bpFiscalYearEndDate = bpFiscalYearEndDate;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpFiscalYearIsClosed(Boolean bpFiscalYearIsClosed) {
    this.bpFiscalYearIsClosed = bpFiscalYearIsClosed;
    return this;
  }

   /**
   * Get bpFiscalYearIsClosed
   * @return bpFiscalYearIsClosed
  **/
  public Boolean isBpFiscalYearIsClosed() {
    return bpFiscalYearIsClosed;
  }

  public void setBpFiscalYearIsClosed(Boolean bpFiscalYearIsClosed) {
    this.bpFiscalYearIsClosed = bpFiscalYearIsClosed;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpFiscalYearClosingDate(String bpFiscalYearClosingDate) {
    this.bpFiscalYearClosingDate = bpFiscalYearClosingDate;
    return this;
  }

   /**
   * Year-End Closing Date for Fiscal Year
   * @return bpFiscalYearClosingDate
  **/
  public String getBpFiscalYearClosingDate() {
    return bpFiscalYearClosingDate;
  }

  public void setBpFiscalYearClosingDate(String bpFiscalYearClosingDate) {
    this.bpFiscalYearClosingDate = bpFiscalYearClosingDate;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpFsclYrCnsldtdFinStatementDte(String bpFsclYrCnsldtdFinStatementDte) {
    this.bpFsclYrCnsldtdFinStatementDte = bpFsclYrCnsldtdFinStatementDte;
    return this;
  }

   /**
   * Date of Consolidated Financial Statements of Group Company
   * @return bpFsclYrCnsldtdFinStatementDte
  **/
  public String getBpFsclYrCnsldtdFinStatementDte() {
    return bpFsclYrCnsldtdFinStatementDte;
  }

  public void setBpFsclYrCnsldtdFinStatementDte(String bpFsclYrCnsldtdFinStatementDte) {
    this.bpFsclYrCnsldtdFinStatementDte = bpFsclYrCnsldtdFinStatementDte;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpCapitalStockAmtInBalShtCrcy(String bpCapitalStockAmtInBalShtCrcy) {
    this.bpCapitalStockAmtInBalShtCrcy = bpCapitalStockAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Authorized Capital Stock for Company
   * @return bpCapitalStockAmtInBalShtCrcy
  **/
  public String getBpCapitalStockAmtInBalShtCrcy() {
    return bpCapitalStockAmtInBalShtCrcy;
  }

  public void setBpCapitalStockAmtInBalShtCrcy(String bpCapitalStockAmtInBalShtCrcy) {
    this.bpCapitalStockAmtInBalShtCrcy = bpCapitalStockAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpIssdStockCptlAmtInBalShtCrcy(String bpIssdStockCptlAmtInBalShtCrcy) {
    this.bpIssdStockCptlAmtInBalShtCrcy = bpIssdStockCptlAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Issued Stock Capital for Company
   * @return bpIssdStockCptlAmtInBalShtCrcy
  **/
  public String getBpIssdStockCptlAmtInBalShtCrcy() {
    return bpIssdStockCptlAmtInBalShtCrcy;
  }

  public void setBpIssdStockCptlAmtInBalShtCrcy(String bpIssdStockCptlAmtInBalShtCrcy) {
    this.bpIssdStockCptlAmtInBalShtCrcy = bpIssdStockCptlAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpPartcipnCertAmtInBalShtCrcy(String bpPartcipnCertAmtInBalShtCrcy) {
    this.bpPartcipnCertAmtInBalShtCrcy = bpPartcipnCertAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Participation Certificates Outstanding for Company
   * @return bpPartcipnCertAmtInBalShtCrcy
  **/
  public String getBpPartcipnCertAmtInBalShtCrcy() {
    return bpPartcipnCertAmtInBalShtCrcy;
  }

  public void setBpPartcipnCertAmtInBalShtCrcy(String bpPartcipnCertAmtInBalShtCrcy) {
    this.bpPartcipnCertAmtInBalShtCrcy = bpPartcipnCertAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpEquityCapitalAmtInBalShtCrcy(String bpEquityCapitalAmtInBalShtCrcy) {
    this.bpEquityCapitalAmtInBalShtCrcy = bpEquityCapitalAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Equity Capital for Company
   * @return bpEquityCapitalAmtInBalShtCrcy
  **/
  public String getBpEquityCapitalAmtInBalShtCrcy() {
    return bpEquityCapitalAmtInBalShtCrcy;
  }

  public void setBpEquityCapitalAmtInBalShtCrcy(String bpEquityCapitalAmtInBalShtCrcy) {
    this.bpEquityCapitalAmtInBalShtCrcy = bpEquityCapitalAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpGrossPremiumAmtInBalShtCrcy(String bpGrossPremiumAmtInBalShtCrcy) {
    this.bpGrossPremiumAmtInBalShtCrcy = bpGrossPremiumAmtInBalShtCrcy;
    return this;
  }

   /**
   * Get bpGrossPremiumAmtInBalShtCrcy
   * @return bpGrossPremiumAmtInBalShtCrcy
  **/
  public String getBpGrossPremiumAmtInBalShtCrcy() {
    return bpGrossPremiumAmtInBalShtCrcy;
  }

  public void setBpGrossPremiumAmtInBalShtCrcy(String bpGrossPremiumAmtInBalShtCrcy) {
    this.bpGrossPremiumAmtInBalShtCrcy = bpGrossPremiumAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpNetPremiumAmtInBalShtCrcy(String bpNetPremiumAmtInBalShtCrcy) {
    this.bpNetPremiumAmtInBalShtCrcy = bpNetPremiumAmtInBalShtCrcy;
    return this;
  }

   /**
   * Get bpNetPremiumAmtInBalShtCrcy
   * @return bpNetPremiumAmtInBalShtCrcy
  **/
  public String getBpNetPremiumAmtInBalShtCrcy() {
    return bpNetPremiumAmtInBalShtCrcy;
  }

  public void setBpNetPremiumAmtInBalShtCrcy(String bpNetPremiumAmtInBalShtCrcy) {
    this.bpNetPremiumAmtInBalShtCrcy = bpNetPremiumAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpAnnualSalesAmtInBalShtCrcy(String bpAnnualSalesAmtInBalShtCrcy) {
    this.bpAnnualSalesAmtInBalShtCrcy = bpAnnualSalesAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Annual Sales for Company
   * @return bpAnnualSalesAmtInBalShtCrcy
  **/
  public String getBpAnnualSalesAmtInBalShtCrcy() {
    return bpAnnualSalesAmtInBalShtCrcy;
  }

  public void setBpAnnualSalesAmtInBalShtCrcy(String bpAnnualSalesAmtInBalShtCrcy) {
    this.bpAnnualSalesAmtInBalShtCrcy = bpAnnualSalesAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpAnnualNetIncAmtInBalShtCrcy(String bpAnnualNetIncAmtInBalShtCrcy) {
    this.bpAnnualNetIncAmtInBalShtCrcy = bpAnnualNetIncAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Annual Net Income/Net Loss for Company
   * @return bpAnnualNetIncAmtInBalShtCrcy
  **/
  public String getBpAnnualNetIncAmtInBalShtCrcy() {
    return bpAnnualNetIncAmtInBalShtCrcy;
  }

  public void setBpAnnualNetIncAmtInBalShtCrcy(String bpAnnualNetIncAmtInBalShtCrcy) {
    this.bpAnnualNetIncAmtInBalShtCrcy = bpAnnualNetIncAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpDividendDistrAmtInBalShtCrcy(String bpDividendDistrAmtInBalShtCrcy) {
    this.bpDividendDistrAmtInBalShtCrcy = bpDividendDistrAmtInBalShtCrcy;
    return this;
  }

   /**
   * Dividend/Profit Distribution Amount for Company
   * @return bpDividendDistrAmtInBalShtCrcy
  **/
  public String getBpDividendDistrAmtInBalShtCrcy() {
    return bpDividendDistrAmtInBalShtCrcy;
  }

  public void setBpDividendDistrAmtInBalShtCrcy(String bpDividendDistrAmtInBalShtCrcy) {
    this.bpDividendDistrAmtInBalShtCrcy = bpDividendDistrAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpDebtRatioInYears(String bpDebtRatioInYears) {
    this.bpDebtRatioInYears = bpDebtRatioInYears;
    return this;
  }

   /**
   * Debt Ratio in Years
   * @return bpDebtRatioInYears
  **/
  public String getBpDebtRatioInYears() {
    return bpDebtRatioInYears;
  }

  public void setBpDebtRatioInYears(String bpDebtRatioInYears) {
    this.bpDebtRatioInYears = bpDebtRatioInYears;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpAnnualPnLAmtInBalShtCrcy(String bpAnnualPnLAmtInBalShtCrcy) {
    this.bpAnnualPnLAmtInBalShtCrcy = bpAnnualPnLAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Annual Profit/Loss for Organization
   * @return bpAnnualPnLAmtInBalShtCrcy
  **/
  public String getBpAnnualPnLAmtInBalShtCrcy() {
    return bpAnnualPnLAmtInBalShtCrcy;
  }

  public void setBpAnnualPnLAmtInBalShtCrcy(String bpAnnualPnLAmtInBalShtCrcy) {
    this.bpAnnualPnLAmtInBalShtCrcy = bpAnnualPnLAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpBalSheetTotalAmtInBalShtCrcy(String bpBalSheetTotalAmtInBalShtCrcy) {
    this.bpBalSheetTotalAmtInBalShtCrcy = bpBalSheetTotalAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Balance Sheet Total for Company
   * @return bpBalSheetTotalAmtInBalShtCrcy
  **/
  public String getBpBalSheetTotalAmtInBalShtCrcy() {
    return bpBalSheetTotalAmtInBalShtCrcy;
  }

  public void setBpBalSheetTotalAmtInBalShtCrcy(String bpBalSheetTotalAmtInBalShtCrcy) {
    this.bpBalSheetTotalAmtInBalShtCrcy = bpBalSheetTotalAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpNumberOfEmployees(String bpNumberOfEmployees) {
    this.bpNumberOfEmployees = bpNumberOfEmployees;
    return this;
  }

   /**
   * Number of Employees in Company
   * @return bpNumberOfEmployees
  **/
  public String getBpNumberOfEmployees() {
    return bpNumberOfEmployees;
  }

  public void setBpNumberOfEmployees(String bpNumberOfEmployees) {
    this.bpNumberOfEmployees = bpNumberOfEmployees;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpCptlReserveAmtInBalShtCrcy(String bpCptlReserveAmtInBalShtCrcy) {
    this.bpCptlReserveAmtInBalShtCrcy = bpCptlReserveAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Capital Reserve for Company
   * @return bpCptlReserveAmtInBalShtCrcy
  **/
  public String getBpCptlReserveAmtInBalShtCrcy() {
    return bpCptlReserveAmtInBalShtCrcy;
  }

  public void setBpCptlReserveAmtInBalShtCrcy(String bpCptlReserveAmtInBalShtCrcy) {
    this.bpCptlReserveAmtInBalShtCrcy = bpCptlReserveAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpLglRevnRsrvAmtInBalShtCrcy(String bpLglRevnRsrvAmtInBalShtCrcy) {
    this.bpLglRevnRsrvAmtInBalShtCrcy = bpLglRevnRsrvAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Legal Revenue Reserves for Company
   * @return bpLglRevnRsrvAmtInBalShtCrcy
  **/
  public String getBpLglRevnRsrvAmtInBalShtCrcy() {
    return bpLglRevnRsrvAmtInBalShtCrcy;
  }

  public void setBpLglRevnRsrvAmtInBalShtCrcy(String bpLglRevnRsrvAmtInBalShtCrcy) {
    this.bpLglRevnRsrvAmtInBalShtCrcy = bpLglRevnRsrvAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate revnRsrvOwnStkAmtInBalShtCrcy(String revnRsrvOwnStkAmtInBalShtCrcy) {
    this.revnRsrvOwnStkAmtInBalShtCrcy = revnRsrvOwnStkAmtInBalShtCrcy;
    return this;
  }

   /**
   * Revenue Reserves for Own Stock
   * @return revnRsrvOwnStkAmtInBalShtCrcy
  **/
  public String getRevnRsrvOwnStkAmtInBalShtCrcy() {
    return revnRsrvOwnStkAmtInBalShtCrcy;
  }

  public void setRevnRsrvOwnStkAmtInBalShtCrcy(String revnRsrvOwnStkAmtInBalShtCrcy) {
    this.revnRsrvOwnStkAmtInBalShtCrcy = revnRsrvOwnStkAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpStatryReserveAmtInBalShtCrcy(String bpStatryReserveAmtInBalShtCrcy) {
    this.bpStatryReserveAmtInBalShtCrcy = bpStatryReserveAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Statutory Revenue Reserve for Company
   * @return bpStatryReserveAmtInBalShtCrcy
  **/
  public String getBpStatryReserveAmtInBalShtCrcy() {
    return bpStatryReserveAmtInBalShtCrcy;
  }

  public void setBpStatryReserveAmtInBalShtCrcy(String bpStatryReserveAmtInBalShtCrcy) {
    this.bpStatryReserveAmtInBalShtCrcy = bpStatryReserveAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpOthRevnRsrvAmtInBalShtCrcy(String bpOthRevnRsrvAmtInBalShtCrcy) {
    this.bpOthRevnRsrvAmtInBalShtCrcy = bpOthRevnRsrvAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Other Revenue Reserves for Company
   * @return bpOthRevnRsrvAmtInBalShtCrcy
  **/
  public String getBpOthRevnRsrvAmtInBalShtCrcy() {
    return bpOthRevnRsrvAmtInBalShtCrcy;
  }

  public void setBpOthRevnRsrvAmtInBalShtCrcy(String bpOthRevnRsrvAmtInBalShtCrcy) {
    this.bpOthRevnRsrvAmtInBalShtCrcy = bpOthRevnRsrvAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpPnLCarryfwdAmtInBalShtCrcy(String bpPnLCarryfwdAmtInBalShtCrcy) {
    this.bpPnLCarryfwdAmtInBalShtCrcy = bpPnLCarryfwdAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Profit/Loss Carried Forward for Company
   * @return bpPnLCarryfwdAmtInBalShtCrcy
  **/
  public String getBpPnLCarryfwdAmtInBalShtCrcy() {
    return bpPnLCarryfwdAmtInBalShtCrcy;
  }

  public void setBpPnLCarryfwdAmtInBalShtCrcy(String bpPnLCarryfwdAmtInBalShtCrcy) {
    this.bpPnLCarryfwdAmtInBalShtCrcy = bpPnLCarryfwdAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpSuborddLbltyAmtInBalShtCrcy(String bpSuborddLbltyAmtInBalShtCrcy) {
    this.bpSuborddLbltyAmtInBalShtCrcy = bpSuborddLbltyAmtInBalShtCrcy;
    return this;
  }

   /**
   * Amount of Subordinated Liabilities for Company
   * @return bpSuborddLbltyAmtInBalShtCrcy
  **/
  public String getBpSuborddLbltyAmtInBalShtCrcy() {
    return bpSuborddLbltyAmtInBalShtCrcy;
  }

  public void setBpSuborddLbltyAmtInBalShtCrcy(String bpSuborddLbltyAmtInBalShtCrcy) {
    this.bpSuborddLbltyAmtInBalShtCrcy = bpSuborddLbltyAmtInBalShtCrcy;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpRetOnTotalCptlEmpldInPercent(String bpRetOnTotalCptlEmpldInPercent) {
    this.bpRetOnTotalCptlEmpldInPercent = bpRetOnTotalCptlEmpldInPercent;
    return this;
  }

   /**
   * Return on Total Capital Employed for Company in Percent
   * @return bpRetOnTotalCptlEmpldInPercent
  **/
  public String getBpRetOnTotalCptlEmpldInPercent() {
    return bpRetOnTotalCptlEmpldInPercent;
  }

  public void setBpRetOnTotalCptlEmpldInPercent(String bpRetOnTotalCptlEmpldInPercent) {
    this.bpRetOnTotalCptlEmpldInPercent = bpRetOnTotalCptlEmpldInPercent;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpDebtClearancePeriodInYears(String bpDebtClearancePeriodInYears) {
    this.bpDebtClearancePeriodInYears = bpDebtClearancePeriodInYears;
    return this;
  }

   /**
   * Debt Clearance Period in Years
   * @return bpDebtClearancePeriodInYears
  **/
  public String getBpDebtClearancePeriodInYears() {
    return bpDebtClearancePeriodInYears;
  }

  public void setBpDebtClearancePeriodInYears(String bpDebtClearancePeriodInYears) {
    this.bpDebtClearancePeriodInYears = bpDebtClearancePeriodInYears;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpFinancingCoeffInPercent(String bpFinancingCoeffInPercent) {
    this.bpFinancingCoeffInPercent = bpFinancingCoeffInPercent;
    return this;
  }

   /**
   * Financing Coefficient for Company in Percent
   * @return bpFinancingCoeffInPercent
  **/
  public String getBpFinancingCoeffInPercent() {
    return bpFinancingCoeffInPercent;
  }

  public void setBpFinancingCoeffInPercent(String bpFinancingCoeffInPercent) {
    this.bpFinancingCoeffInPercent = bpFinancingCoeffInPercent;
  }

  public APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate bpEquityRatioInPercent(String bpEquityRatioInPercent) {
    this.bpEquityRatioInPercent = bpEquityRatioInPercent;
    return this;
  }

   /**
   * Equity Ratio of Company in Percent
   * @return bpEquityRatioInPercent
  **/
  public String getBpEquityRatioInPercent() {
    return bpEquityRatioInPercent;
  }

  public void setBpEquityRatioInPercent(String bpEquityRatioInPercent) {
    this.bpEquityRatioInPercent = bpEquityRatioInPercent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate = (APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.businessPartner) &&
        Objects.equals(this.businessPartnerFiscalYear, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.businessPartnerFiscalYear) &&
        Objects.equals(this.bpBalanceSheetCurrency, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpBalanceSheetCurrency) &&
        Objects.equals(this.bpAnnualStockholderMeetingDate, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpAnnualStockholderMeetingDate) &&
        Objects.equals(this.bpFiscalYearStartDate, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpFiscalYearStartDate) &&
        Objects.equals(this.bpFiscalYearEndDate, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpFiscalYearEndDate) &&
        Objects.equals(this.bpFiscalYearIsClosed, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpFiscalYearIsClosed) &&
        Objects.equals(this.bpFiscalYearClosingDate, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpFiscalYearClosingDate) &&
        Objects.equals(this.bpFsclYrCnsldtdFinStatementDte, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpFsclYrCnsldtdFinStatementDte) &&
        Objects.equals(this.bpCapitalStockAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpCapitalStockAmtInBalShtCrcy) &&
        Objects.equals(this.bpIssdStockCptlAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpIssdStockCptlAmtInBalShtCrcy) &&
        Objects.equals(this.bpPartcipnCertAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpPartcipnCertAmtInBalShtCrcy) &&
        Objects.equals(this.bpEquityCapitalAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpEquityCapitalAmtInBalShtCrcy) &&
        Objects.equals(this.bpGrossPremiumAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpGrossPremiumAmtInBalShtCrcy) &&
        Objects.equals(this.bpNetPremiumAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpNetPremiumAmtInBalShtCrcy) &&
        Objects.equals(this.bpAnnualSalesAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpAnnualSalesAmtInBalShtCrcy) &&
        Objects.equals(this.bpAnnualNetIncAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpAnnualNetIncAmtInBalShtCrcy) &&
        Objects.equals(this.bpDividendDistrAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpDividendDistrAmtInBalShtCrcy) &&
        Objects.equals(this.bpDebtRatioInYears, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpDebtRatioInYears) &&
        Objects.equals(this.bpAnnualPnLAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpAnnualPnLAmtInBalShtCrcy) &&
        Objects.equals(this.bpBalSheetTotalAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpBalSheetTotalAmtInBalShtCrcy) &&
        Objects.equals(this.bpNumberOfEmployees, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpNumberOfEmployees) &&
        Objects.equals(this.bpCptlReserveAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpCptlReserveAmtInBalShtCrcy) &&
        Objects.equals(this.bpLglRevnRsrvAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpLglRevnRsrvAmtInBalShtCrcy) &&
        Objects.equals(this.revnRsrvOwnStkAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.revnRsrvOwnStkAmtInBalShtCrcy) &&
        Objects.equals(this.bpStatryReserveAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpStatryReserveAmtInBalShtCrcy) &&
        Objects.equals(this.bpOthRevnRsrvAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpOthRevnRsrvAmtInBalShtCrcy) &&
        Objects.equals(this.bpPnLCarryfwdAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpPnLCarryfwdAmtInBalShtCrcy) &&
        Objects.equals(this.bpSuborddLbltyAmtInBalShtCrcy, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpSuborddLbltyAmtInBalShtCrcy) &&
        Objects.equals(this.bpRetOnTotalCptlEmpldInPercent, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpRetOnTotalCptlEmpldInPercent) &&
        Objects.equals(this.bpDebtClearancePeriodInYears, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpDebtClearancePeriodInYears) &&
        Objects.equals(this.bpFinancingCoeffInPercent, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpFinancingCoeffInPercent) &&
        Objects.equals(this.bpEquityRatioInPercent, apIBUSINESSPARTNERABPFiscalYearInformationTypeCreate.bpEquityRatioInPercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, businessPartnerFiscalYear, bpBalanceSheetCurrency, bpAnnualStockholderMeetingDate, bpFiscalYearStartDate, bpFiscalYearEndDate, bpFiscalYearIsClosed, bpFiscalYearClosingDate, bpFsclYrCnsldtdFinStatementDte, bpCapitalStockAmtInBalShtCrcy, bpIssdStockCptlAmtInBalShtCrcy, bpPartcipnCertAmtInBalShtCrcy, bpEquityCapitalAmtInBalShtCrcy, bpGrossPremiumAmtInBalShtCrcy, bpNetPremiumAmtInBalShtCrcy, bpAnnualSalesAmtInBalShtCrcy, bpAnnualNetIncAmtInBalShtCrcy, bpDividendDistrAmtInBalShtCrcy, bpDebtRatioInYears, bpAnnualPnLAmtInBalShtCrcy, bpBalSheetTotalAmtInBalShtCrcy, bpNumberOfEmployees, bpCptlReserveAmtInBalShtCrcy, bpLglRevnRsrvAmtInBalShtCrcy, revnRsrvOwnStkAmtInBalShtCrcy, bpStatryReserveAmtInBalShtCrcy, bpOthRevnRsrvAmtInBalShtCrcy, bpPnLCarryfwdAmtInBalShtCrcy, bpSuborddLbltyAmtInBalShtCrcy, bpRetOnTotalCptlEmpldInPercent, bpDebtClearancePeriodInYears, bpFinancingCoeffInPercent, bpEquityRatioInPercent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABPFiscalYearInformationTypeCreate {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    businessPartnerFiscalYear: ").append(toIndentedString(businessPartnerFiscalYear)).append("\n");
    sb.append("    bpBalanceSheetCurrency: ").append(toIndentedString(bpBalanceSheetCurrency)).append("\n");
    sb.append("    bpAnnualStockholderMeetingDate: ").append(toIndentedString(bpAnnualStockholderMeetingDate)).append("\n");
    sb.append("    bpFiscalYearStartDate: ").append(toIndentedString(bpFiscalYearStartDate)).append("\n");
    sb.append("    bpFiscalYearEndDate: ").append(toIndentedString(bpFiscalYearEndDate)).append("\n");
    sb.append("    bpFiscalYearIsClosed: ").append(toIndentedString(bpFiscalYearIsClosed)).append("\n");
    sb.append("    bpFiscalYearClosingDate: ").append(toIndentedString(bpFiscalYearClosingDate)).append("\n");
    sb.append("    bpFsclYrCnsldtdFinStatementDte: ").append(toIndentedString(bpFsclYrCnsldtdFinStatementDte)).append("\n");
    sb.append("    bpCapitalStockAmtInBalShtCrcy: ").append(toIndentedString(bpCapitalStockAmtInBalShtCrcy)).append("\n");
    sb.append("    bpIssdStockCptlAmtInBalShtCrcy: ").append(toIndentedString(bpIssdStockCptlAmtInBalShtCrcy)).append("\n");
    sb.append("    bpPartcipnCertAmtInBalShtCrcy: ").append(toIndentedString(bpPartcipnCertAmtInBalShtCrcy)).append("\n");
    sb.append("    bpEquityCapitalAmtInBalShtCrcy: ").append(toIndentedString(bpEquityCapitalAmtInBalShtCrcy)).append("\n");
    sb.append("    bpGrossPremiumAmtInBalShtCrcy: ").append(toIndentedString(bpGrossPremiumAmtInBalShtCrcy)).append("\n");
    sb.append("    bpNetPremiumAmtInBalShtCrcy: ").append(toIndentedString(bpNetPremiumAmtInBalShtCrcy)).append("\n");
    sb.append("    bpAnnualSalesAmtInBalShtCrcy: ").append(toIndentedString(bpAnnualSalesAmtInBalShtCrcy)).append("\n");
    sb.append("    bpAnnualNetIncAmtInBalShtCrcy: ").append(toIndentedString(bpAnnualNetIncAmtInBalShtCrcy)).append("\n");
    sb.append("    bpDividendDistrAmtInBalShtCrcy: ").append(toIndentedString(bpDividendDistrAmtInBalShtCrcy)).append("\n");
    sb.append("    bpDebtRatioInYears: ").append(toIndentedString(bpDebtRatioInYears)).append("\n");
    sb.append("    bpAnnualPnLAmtInBalShtCrcy: ").append(toIndentedString(bpAnnualPnLAmtInBalShtCrcy)).append("\n");
    sb.append("    bpBalSheetTotalAmtInBalShtCrcy: ").append(toIndentedString(bpBalSheetTotalAmtInBalShtCrcy)).append("\n");
    sb.append("    bpNumberOfEmployees: ").append(toIndentedString(bpNumberOfEmployees)).append("\n");
    sb.append("    bpCptlReserveAmtInBalShtCrcy: ").append(toIndentedString(bpCptlReserveAmtInBalShtCrcy)).append("\n");
    sb.append("    bpLglRevnRsrvAmtInBalShtCrcy: ").append(toIndentedString(bpLglRevnRsrvAmtInBalShtCrcy)).append("\n");
    sb.append("    revnRsrvOwnStkAmtInBalShtCrcy: ").append(toIndentedString(revnRsrvOwnStkAmtInBalShtCrcy)).append("\n");
    sb.append("    bpStatryReserveAmtInBalShtCrcy: ").append(toIndentedString(bpStatryReserveAmtInBalShtCrcy)).append("\n");
    sb.append("    bpOthRevnRsrvAmtInBalShtCrcy: ").append(toIndentedString(bpOthRevnRsrvAmtInBalShtCrcy)).append("\n");
    sb.append("    bpPnLCarryfwdAmtInBalShtCrcy: ").append(toIndentedString(bpPnLCarryfwdAmtInBalShtCrcy)).append("\n");
    sb.append("    bpSuborddLbltyAmtInBalShtCrcy: ").append(toIndentedString(bpSuborddLbltyAmtInBalShtCrcy)).append("\n");
    sb.append("    bpRetOnTotalCptlEmpldInPercent: ").append(toIndentedString(bpRetOnTotalCptlEmpldInPercent)).append("\n");
    sb.append("    bpDebtClearancePeriodInYears: ").append(toIndentedString(bpDebtClearancePeriodInYears)).append("\n");
    sb.append("    bpFinancingCoeffInPercent: ").append(toIndentedString(bpFinancingCoeffInPercent)).append("\n");
    sb.append("    bpEquityRatioInPercent: ").append(toIndentedString(bpEquityRatioInPercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
