/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERACustomerCompanyTextType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERACustomerCompanyTextType {
  @JsonProperty("Customer")
  private String customer = null;

  @JsonProperty("CompanyCode")
  private String companyCode = null;

  @JsonProperty("Language")
  private String language = null;

  @JsonProperty("LongTextID")
  private String longTextID = null;

  @JsonProperty("LongText")
  private String longText = null;

  public APIBUSINESSPARTNERACustomerCompanyTextType customer(String customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Customer Number
   * @return customer
  **/
  public String getCustomer() {
    return customer;
  }

  public void setCustomer(String customer) {
    this.customer = customer;
  }

  public APIBUSINESSPARTNERACustomerCompanyTextType companyCode(String companyCode) {
    this.companyCode = companyCode;
    return this;
  }

   /**
   * Get companyCode
   * @return companyCode
  **/
  public String getCompanyCode() {
    return companyCode;
  }

  public void setCompanyCode(String companyCode) {
    this.companyCode = companyCode;
  }

  public APIBUSINESSPARTNERACustomerCompanyTextType language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Language key
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public APIBUSINESSPARTNERACustomerCompanyTextType longTextID(String longTextID) {
    this.longTextID = longTextID;
    return this;
  }

   /**
   * Get longTextID
   * @return longTextID
  **/
  public String getLongTextID() {
    return longTextID;
  }

  public void setLongTextID(String longTextID) {
    this.longTextID = longTextID;
  }

  public APIBUSINESSPARTNERACustomerCompanyTextType longText(String longText) {
    this.longText = longText;
    return this;
  }

   /**
   * Get longText
   * @return longText
  **/
  public String getLongText() {
    return longText;
  }

  public void setLongText(String longText) {
    this.longText = longText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERACustomerCompanyTextType apIBUSINESSPARTNERACustomerCompanyTextType = (APIBUSINESSPARTNERACustomerCompanyTextType) o;
    return Objects.equals(this.customer, apIBUSINESSPARTNERACustomerCompanyTextType.customer) &&
        Objects.equals(this.companyCode, apIBUSINESSPARTNERACustomerCompanyTextType.companyCode) &&
        Objects.equals(this.language, apIBUSINESSPARTNERACustomerCompanyTextType.language) &&
        Objects.equals(this.longTextID, apIBUSINESSPARTNERACustomerCompanyTextType.longTextID) &&
        Objects.equals(this.longText, apIBUSINESSPARTNERACustomerCompanyTextType.longText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customer, companyCode, language, longTextID, longText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERACustomerCompanyTextType {\n");
    
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    longTextID: ").append(toIndentedString(longTextID)).append("\n");
    sb.append("    longText: ").append(toIndentedString(longText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
