/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate {
  @JsonProperty("IsDefaultFaxNumber")
  private Boolean isDefaultFaxNumber = null;

  @JsonProperty("FaxCountry")
  private String faxCountry = null;

  @JsonProperty("FaxNumber")
  private String faxNumber = null;

  @JsonProperty("FaxNumberExtension")
  private String faxNumberExtension = null;

  @JsonProperty("AddressCommunicationRemarkText")
  private String addressCommunicationRemarkText = null;

  public APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate isDefaultFaxNumber(Boolean isDefaultFaxNumber) {
    this.isDefaultFaxNumber = isDefaultFaxNumber;
    return this;
  }

   /**
   * Standard Sender Address in this Communication Type
   * @return isDefaultFaxNumber
  **/
  public Boolean isIsDefaultFaxNumber() {
    return isDefaultFaxNumber;
  }

  public void setIsDefaultFaxNumber(Boolean isDefaultFaxNumber) {
    this.isDefaultFaxNumber = isDefaultFaxNumber;
  }

  public APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate faxCountry(String faxCountry) {
    this.faxCountry = faxCountry;
    return this;
  }

   /**
   * Country/Region for Telephone/Fax Number
   * @return faxCountry
  **/
  public String getFaxCountry() {
    return faxCountry;
  }

  public void setFaxCountry(String faxCountry) {
    this.faxCountry = faxCountry;
  }

  public APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate faxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

   /**
   * Fax Number: Dialing Code and Number
   * @return faxNumber
  **/
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
  }

  public APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate faxNumberExtension(String faxNumberExtension) {
    this.faxNumberExtension = faxNumberExtension;
    return this;
  }

   /**
   * Fax no.: Extension
   * @return faxNumberExtension
  **/
  public String getFaxNumberExtension() {
    return faxNumberExtension;
  }

  public void setFaxNumberExtension(String faxNumberExtension) {
    this.faxNumberExtension = faxNumberExtension;
  }

  public APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate addressCommunicationRemarkText(String addressCommunicationRemarkText) {
    this.addressCommunicationRemarkText = addressCommunicationRemarkText;
    return this;
  }

   /**
   * Communication link notes
   * @return addressCommunicationRemarkText
  **/
  public String getAddressCommunicationRemarkText() {
    return addressCommunicationRemarkText;
  }

  public void setAddressCommunicationRemarkText(String addressCommunicationRemarkText) {
    this.addressCommunicationRemarkText = addressCommunicationRemarkText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate apIBUSINESSPARTNERAAddressFaxNumberTypeUpdate = (APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate) o;
    return Objects.equals(this.isDefaultFaxNumber, apIBUSINESSPARTNERAAddressFaxNumberTypeUpdate.isDefaultFaxNumber) &&
        Objects.equals(this.faxCountry, apIBUSINESSPARTNERAAddressFaxNumberTypeUpdate.faxCountry) &&
        Objects.equals(this.faxNumber, apIBUSINESSPARTNERAAddressFaxNumberTypeUpdate.faxNumber) &&
        Objects.equals(this.faxNumberExtension, apIBUSINESSPARTNERAAddressFaxNumberTypeUpdate.faxNumberExtension) &&
        Objects.equals(this.addressCommunicationRemarkText, apIBUSINESSPARTNERAAddressFaxNumberTypeUpdate.addressCommunicationRemarkText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isDefaultFaxNumber, faxCountry, faxNumber, faxNumberExtension, addressCommunicationRemarkText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERAAddressFaxNumberTypeUpdate {\n");
    
    sb.append("    isDefaultFaxNumber: ").append(toIndentedString(isDefaultFaxNumber)).append("\n");
    sb.append("    faxCountry: ").append(toIndentedString(faxCountry)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    faxNumberExtension: ").append(toIndentedString(faxNumberExtension)).append("\n");
    sb.append("    addressCommunicationRemarkText: ").append(toIndentedString(addressCommunicationRemarkText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
