/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABPDataControllerTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABPDataControllerTypeCreate {
  @JsonProperty("BusinessPartner")
  private String businessPartner = null;

  @JsonProperty("DataController")
  private String dataController = null;

  @JsonProperty("PurposeForPersonalData")
  private String purposeForPersonalData = null;

  @JsonProperty("DataControlAssignmentStatus")
  private String dataControlAssignmentStatus = null;

  public APIBUSINESSPARTNERABPDataControllerTypeCreate businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartner
  **/
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABPDataControllerTypeCreate dataController(String dataController) {
    this.dataController = dataController;
    return this;
  }

   /**
   * BP: Data Controller
   * @return dataController
  **/
  public String getDataController() {
    return dataController;
  }

  public void setDataController(String dataController) {
    this.dataController = dataController;
  }

  public APIBUSINESSPARTNERABPDataControllerTypeCreate purposeForPersonalData(String purposeForPersonalData) {
    this.purposeForPersonalData = purposeForPersonalData;
    return this;
  }

   /**
   * BP: Purpose
   * @return purposeForPersonalData
  **/
  public String getPurposeForPersonalData() {
    return purposeForPersonalData;
  }

  public void setPurposeForPersonalData(String purposeForPersonalData) {
    this.purposeForPersonalData = purposeForPersonalData;
  }

  public APIBUSINESSPARTNERABPDataControllerTypeCreate dataControlAssignmentStatus(String dataControlAssignmentStatus) {
    this.dataControlAssignmentStatus = dataControlAssignmentStatus;
    return this;
  }

   /**
   * BP: Data Controller Purpose Assignment Status
   * @return dataControlAssignmentStatus
  **/
  public String getDataControlAssignmentStatus() {
    return dataControlAssignmentStatus;
  }

  public void setDataControlAssignmentStatus(String dataControlAssignmentStatus) {
    this.dataControlAssignmentStatus = dataControlAssignmentStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABPDataControllerTypeCreate apIBUSINESSPARTNERABPDataControllerTypeCreate = (APIBUSINESSPARTNERABPDataControllerTypeCreate) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABPDataControllerTypeCreate.businessPartner) &&
        Objects.equals(this.dataController, apIBUSINESSPARTNERABPDataControllerTypeCreate.dataController) &&
        Objects.equals(this.purposeForPersonalData, apIBUSINESSPARTNERABPDataControllerTypeCreate.purposeForPersonalData) &&
        Objects.equals(this.dataControlAssignmentStatus, apIBUSINESSPARTNERABPDataControllerTypeCreate.dataControlAssignmentStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, dataController, purposeForPersonalData, dataControlAssignmentStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABPDataControllerTypeCreate {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    dataController: ").append(toIndentedString(dataController)).append("\n");
    sb.append("    purposeForPersonalData: ").append(toIndentedString(purposeForPersonalData)).append("\n");
    sb.append("    dataControlAssignmentStatus: ").append(toIndentedString(dataControlAssignmentStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
