/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate {
  @JsonProperty("EmailAddress")
  private String emailAddress = null;

  @JsonProperty("IsDefaultEmailAddress")
  private Boolean isDefaultEmailAddress = null;

  @JsonProperty("ValidityStartDate")
  private String validityStartDate = null;

  @JsonProperty("ValidityEndDate")
  private String validityEndDate = null;

  public APIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Get emailAddress
   * @return emailAddress
  **/
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public APIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate isDefaultEmailAddress(Boolean isDefaultEmailAddress) {
    this.isDefaultEmailAddress = isDefaultEmailAddress;
    return this;
  }

   /**
   * Indicator : Current Default Email Address
   * @return isDefaultEmailAddress
  **/
  public Boolean isIsDefaultEmailAddress() {
    return isDefaultEmailAddress;
  }

  public void setIsDefaultEmailAddress(Boolean isDefaultEmailAddress) {
    this.isDefaultEmailAddress = isDefaultEmailAddress;
  }

  public APIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate validityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
    return this;
  }

   /**
   * Get validityStartDate
   * @return validityStartDate
  **/
  public String getValidityStartDate() {
    return validityStartDate;
  }

  public void setValidityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
  }

  public APIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate validityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
    return this;
  }

   /**
   * Get validityEndDate
   * @return validityEndDate
  **/
  public String getValidityEndDate() {
    return validityEndDate;
  }

  public void setValidityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate apIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate = (APIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate) o;
    return Objects.equals(this.emailAddress, apIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate.emailAddress) &&
        Objects.equals(this.isDefaultEmailAddress, apIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate.isDefaultEmailAddress) &&
        Objects.equals(this.validityStartDate, apIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate.validityStartDate) &&
        Objects.equals(this.validityEndDate, apIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate.validityEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailAddress, isDefaultEmailAddress, validityStartDate, validityEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABPAddressIndependentEmailTypeUpdate {\n");
    
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    isDefaultEmailAddress: ").append(toIndentedString(isDefaultEmailAddress)).append("\n");
    sb.append("    validityStartDate: ").append(toIndentedString(validityStartDate)).append("\n");
    sb.append("    validityEndDate: ").append(toIndentedString(validityEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
