/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate {
  @JsonProperty("DefaultPartner")
  private Boolean defaultPartner = null;

  @JsonProperty("ReferenceSupplier")
  private String referenceSupplier = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate defaultPartner(Boolean defaultPartner) {
    this.defaultPartner = defaultPartner;
    return this;
  }

   /**
   * Get defaultPartner
   * @return defaultPartner
  **/
  public Boolean isDefaultPartner() {
    return defaultPartner;
  }

  public void setDefaultPartner(Boolean defaultPartner) {
    this.defaultPartner = defaultPartner;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate referenceSupplier(String referenceSupplier) {
    this.referenceSupplier = referenceSupplier;
    return this;
  }

   /**
   * Reference to other supplier
   * @return referenceSupplier
  **/
  public String getReferenceSupplier() {
    return referenceSupplier;
  }

  public void setReferenceSupplier(String referenceSupplier) {
    this.referenceSupplier = referenceSupplier;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Authorization Group
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate apIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate = (APIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate) o;
    return Objects.equals(this.defaultPartner, apIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate.defaultPartner) &&
        Objects.equals(this.referenceSupplier, apIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate.referenceSupplier) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate.authorizationGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultPartner, referenceSupplier, authorizationGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERASupplierPartnerFuncTypeUpdate {\n");
    
    sb.append("    defaultPartner: ").append(toIndentedString(defaultPartner)).append("\n");
    sb.append("    referenceSupplier: ").append(toIndentedString(referenceSupplier)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
