/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate {
  @JsonProperty("Supplier")
  private String supplier = null;

  @JsonProperty("CompanyCode")
  private String companyCode = null;

  @JsonProperty("WithholdingTaxType")
  private String withholdingTaxType = null;

  @JsonProperty("ExemptionDateBegin")
  private String exemptionDateBegin = null;

  @JsonProperty("ExemptionDateEnd")
  private String exemptionDateEnd = null;

  @JsonProperty("ExemptionReason")
  private String exemptionReason = null;

  @JsonProperty("IsWithholdingTaxSubject")
  private Boolean isWithholdingTaxSubject = null;

  @JsonProperty("RecipientType")
  private String recipientType = null;

  @JsonProperty("WithholdingTaxCertificate")
  private String withholdingTaxCertificate = null;

  @JsonProperty("WithholdingTaxCode")
  private String withholdingTaxCode = null;

  @JsonProperty("WithholdingTaxExmptPercent")
  private String withholdingTaxExmptPercent = null;

  @JsonProperty("WithholdingTaxNumber")
  private String withholdingTaxNumber = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate supplier(String supplier) {
    this.supplier = supplier;
    return this;
  }

   /**
   * Account Number of Supplier
   * @return supplier
  **/
  public String getSupplier() {
    return supplier;
  }

  public void setSupplier(String supplier) {
    this.supplier = supplier;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate companyCode(String companyCode) {
    this.companyCode = companyCode;
    return this;
  }

   /**
   * Get companyCode
   * @return companyCode
  **/
  public String getCompanyCode() {
    return companyCode;
  }

  public void setCompanyCode(String companyCode) {
    this.companyCode = companyCode;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate withholdingTaxType(String withholdingTaxType) {
    this.withholdingTaxType = withholdingTaxType;
    return this;
  }

   /**
   * Indicator for Withholding Tax Type
   * @return withholdingTaxType
  **/
  public String getWithholdingTaxType() {
    return withholdingTaxType;
  }

  public void setWithholdingTaxType(String withholdingTaxType) {
    this.withholdingTaxType = withholdingTaxType;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate exemptionDateBegin(String exemptionDateBegin) {
    this.exemptionDateBegin = exemptionDateBegin;
    return this;
  }

   /**
   * Date on Which Exemption Begins
   * @return exemptionDateBegin
  **/
  public String getExemptionDateBegin() {
    return exemptionDateBegin;
  }

  public void setExemptionDateBegin(String exemptionDateBegin) {
    this.exemptionDateBegin = exemptionDateBegin;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate exemptionDateEnd(String exemptionDateEnd) {
    this.exemptionDateEnd = exemptionDateEnd;
    return this;
  }

   /**
   * Date on Which Exemption Ends
   * @return exemptionDateEnd
  **/
  public String getExemptionDateEnd() {
    return exemptionDateEnd;
  }

  public void setExemptionDateEnd(String exemptionDateEnd) {
    this.exemptionDateEnd = exemptionDateEnd;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate exemptionReason(String exemptionReason) {
    this.exemptionReason = exemptionReason;
    return this;
  }

   /**
   * Reason for Exemption
   * @return exemptionReason
  **/
  public String getExemptionReason() {
    return exemptionReason;
  }

  public void setExemptionReason(String exemptionReason) {
    this.exemptionReason = exemptionReason;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate isWithholdingTaxSubject(Boolean isWithholdingTaxSubject) {
    this.isWithholdingTaxSubject = isWithholdingTaxSubject;
    return this;
  }

   /**
   * Indicator: Subject to Withholding Tax?
   * @return isWithholdingTaxSubject
  **/
  public Boolean isIsWithholdingTaxSubject() {
    return isWithholdingTaxSubject;
  }

  public void setIsWithholdingTaxSubject(Boolean isWithholdingTaxSubject) {
    this.isWithholdingTaxSubject = isWithholdingTaxSubject;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate recipientType(String recipientType) {
    this.recipientType = recipientType;
    return this;
  }

   /**
   * Type of Recipient
   * @return recipientType
  **/
  public String getRecipientType() {
    return recipientType;
  }

  public void setRecipientType(String recipientType) {
    this.recipientType = recipientType;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate withholdingTaxCertificate(String withholdingTaxCertificate) {
    this.withholdingTaxCertificate = withholdingTaxCertificate;
    return this;
  }

   /**
   * Exemption Certificate Number
   * @return withholdingTaxCertificate
  **/
  public String getWithholdingTaxCertificate() {
    return withholdingTaxCertificate;
  }

  public void setWithholdingTaxCertificate(String withholdingTaxCertificate) {
    this.withholdingTaxCertificate = withholdingTaxCertificate;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate withholdingTaxCode(String withholdingTaxCode) {
    this.withholdingTaxCode = withholdingTaxCode;
    return this;
  }

   /**
   * Withholding Tax Code
   * @return withholdingTaxCode
  **/
  public String getWithholdingTaxCode() {
    return withholdingTaxCode;
  }

  public void setWithholdingTaxCode(String withholdingTaxCode) {
    this.withholdingTaxCode = withholdingTaxCode;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate withholdingTaxExmptPercent(String withholdingTaxExmptPercent) {
    this.withholdingTaxExmptPercent = withholdingTaxExmptPercent;
    return this;
  }

   /**
   * Get withholdingTaxExmptPercent
   * @return withholdingTaxExmptPercent
  **/
  public String getWithholdingTaxExmptPercent() {
    return withholdingTaxExmptPercent;
  }

  public void setWithholdingTaxExmptPercent(String withholdingTaxExmptPercent) {
    this.withholdingTaxExmptPercent = withholdingTaxExmptPercent;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate withholdingTaxNumber(String withholdingTaxNumber) {
    this.withholdingTaxNumber = withholdingTaxNumber;
    return this;
  }

   /**
   * Withholding tax identification number
   * @return withholdingTaxNumber
  **/
  public String getWithholdingTaxNumber() {
    return withholdingTaxNumber;
  }

  public void setWithholdingTaxNumber(String withholdingTaxNumber) {
    this.withholdingTaxNumber = withholdingTaxNumber;
  }

  public APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Authorization Group
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate = (APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate) o;
    return Objects.equals(this.supplier, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.supplier) &&
        Objects.equals(this.companyCode, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.companyCode) &&
        Objects.equals(this.withholdingTaxType, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.withholdingTaxType) &&
        Objects.equals(this.exemptionDateBegin, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.exemptionDateBegin) &&
        Objects.equals(this.exemptionDateEnd, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.exemptionDateEnd) &&
        Objects.equals(this.exemptionReason, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.exemptionReason) &&
        Objects.equals(this.isWithholdingTaxSubject, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.isWithholdingTaxSubject) &&
        Objects.equals(this.recipientType, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.recipientType) &&
        Objects.equals(this.withholdingTaxCertificate, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.withholdingTaxCertificate) &&
        Objects.equals(this.withholdingTaxCode, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.withholdingTaxCode) &&
        Objects.equals(this.withholdingTaxExmptPercent, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.withholdingTaxExmptPercent) &&
        Objects.equals(this.withholdingTaxNumber, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.withholdingTaxNumber) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate.authorizationGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplier, companyCode, withholdingTaxType, exemptionDateBegin, exemptionDateEnd, exemptionReason, isWithholdingTaxSubject, recipientType, withholdingTaxCertificate, withholdingTaxCode, withholdingTaxExmptPercent, withholdingTaxNumber, authorizationGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERASupplierWithHoldingTaxTypeCreate {\n");
    
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    withholdingTaxType: ").append(toIndentedString(withholdingTaxType)).append("\n");
    sb.append("    exemptionDateBegin: ").append(toIndentedString(exemptionDateBegin)).append("\n");
    sb.append("    exemptionDateEnd: ").append(toIndentedString(exemptionDateEnd)).append("\n");
    sb.append("    exemptionReason: ").append(toIndentedString(exemptionReason)).append("\n");
    sb.append("    isWithholdingTaxSubject: ").append(toIndentedString(isWithholdingTaxSubject)).append("\n");
    sb.append("    recipientType: ").append(toIndentedString(recipientType)).append("\n");
    sb.append("    withholdingTaxCertificate: ").append(toIndentedString(withholdingTaxCertificate)).append("\n");
    sb.append("    withholdingTaxCode: ").append(toIndentedString(withholdingTaxCode)).append("\n");
    sb.append("    withholdingTaxExmptPercent: ").append(toIndentedString(withholdingTaxExmptPercent)).append("\n");
    sb.append("    withholdingTaxNumber: ").append(toIndentedString(withholdingTaxNumber)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
