/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABusinessPartnerAliasTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABusinessPartnerAliasTypeCreate {
  @JsonProperty("BusinessPartner")
  private String businessPartner = null;

  @JsonProperty("BPAliasPositionNumber")
  private String bpAliasPositionNumber = null;

  @JsonProperty("BusinessPartnerAliasName")
  private String businessPartnerAliasName = null;

  public APIBUSINESSPARTNERABusinessPartnerAliasTypeCreate businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartner
  **/
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABusinessPartnerAliasTypeCreate bpAliasPositionNumber(String bpAliasPositionNumber) {
    this.bpAliasPositionNumber = bpAliasPositionNumber;
    return this;
  }

   /**
   * Items with Business Partner Name/Alias
   * @return bpAliasPositionNumber
  **/
  public String getBpAliasPositionNumber() {
    return bpAliasPositionNumber;
  }

  public void setBpAliasPositionNumber(String bpAliasPositionNumber) {
    this.bpAliasPositionNumber = bpAliasPositionNumber;
  }

  public APIBUSINESSPARTNERABusinessPartnerAliasTypeCreate businessPartnerAliasName(String businessPartnerAliasName) {
    this.businessPartnerAliasName = businessPartnerAliasName;
    return this;
  }

   /**
   * Business Partner Alias
   * @return businessPartnerAliasName
  **/
  public String getBusinessPartnerAliasName() {
    return businessPartnerAliasName;
  }

  public void setBusinessPartnerAliasName(String businessPartnerAliasName) {
    this.businessPartnerAliasName = businessPartnerAliasName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerAliasTypeCreate apIBUSINESSPARTNERABusinessPartnerAliasTypeCreate = (APIBUSINESSPARTNERABusinessPartnerAliasTypeCreate) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABusinessPartnerAliasTypeCreate.businessPartner) &&
        Objects.equals(this.bpAliasPositionNumber, apIBUSINESSPARTNERABusinessPartnerAliasTypeCreate.bpAliasPositionNumber) &&
        Objects.equals(this.businessPartnerAliasName, apIBUSINESSPARTNERABusinessPartnerAliasTypeCreate.businessPartnerAliasName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, bpAliasPositionNumber, businessPartnerAliasName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerAliasTypeCreate {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    bpAliasPositionNumber: ").append(toIndentedString(bpAliasPositionNumber)).append("\n");
    sb.append("    businessPartnerAliasName: ").append(toIndentedString(businessPartnerAliasName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
