/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABusinessPartnerTaxNumberType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABusinessPartnerTaxNumberType {
  @JsonProperty("BusinessPartner")
  private String businessPartner = null;

  @JsonProperty("BPTaxType")
  private String bpTaxType = null;

  @JsonProperty("BPTaxNumber")
  private String bpTaxNumber = null;

  @JsonProperty("BPTaxLongNumber")
  private String bpTaxLongNumber = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  public APIBUSINESSPARTNERABusinessPartnerTaxNumberType businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartner
  **/
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABusinessPartnerTaxNumberType bpTaxType(String bpTaxType) {
    this.bpTaxType = bpTaxType;
    return this;
  }

   /**
   * Get bpTaxType
   * @return bpTaxType
  **/
  public String getBpTaxType() {
    return bpTaxType;
  }

  public void setBpTaxType(String bpTaxType) {
    this.bpTaxType = bpTaxType;
  }

  public APIBUSINESSPARTNERABusinessPartnerTaxNumberType bpTaxNumber(String bpTaxNumber) {
    this.bpTaxNumber = bpTaxNumber;
    return this;
  }

   /**
   * Business Partner Tax Number
   * @return bpTaxNumber
  **/
  public String getBpTaxNumber() {
    return bpTaxNumber;
  }

  public void setBpTaxNumber(String bpTaxNumber) {
    this.bpTaxNumber = bpTaxNumber;
  }

  public APIBUSINESSPARTNERABusinessPartnerTaxNumberType bpTaxLongNumber(String bpTaxLongNumber) {
    this.bpTaxLongNumber = bpTaxLongNumber;
    return this;
  }

   /**
   * Business Partner Tax Number
   * @return bpTaxLongNumber
  **/
  public String getBpTaxLongNumber() {
    return bpTaxLongNumber;
  }

  public void setBpTaxLongNumber(String bpTaxLongNumber) {
    this.bpTaxLongNumber = bpTaxLongNumber;
  }

  public APIBUSINESSPARTNERABusinessPartnerTaxNumberType authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Get authorizationGroup
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerTaxNumberType apIBUSINESSPARTNERABusinessPartnerTaxNumberType = (APIBUSINESSPARTNERABusinessPartnerTaxNumberType) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABusinessPartnerTaxNumberType.businessPartner) &&
        Objects.equals(this.bpTaxType, apIBUSINESSPARTNERABusinessPartnerTaxNumberType.bpTaxType) &&
        Objects.equals(this.bpTaxNumber, apIBUSINESSPARTNERABusinessPartnerTaxNumberType.bpTaxNumber) &&
        Objects.equals(this.bpTaxLongNumber, apIBUSINESSPARTNERABusinessPartnerTaxNumberType.bpTaxLongNumber) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERABusinessPartnerTaxNumberType.authorizationGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, bpTaxType, bpTaxNumber, bpTaxLongNumber, authorizationGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerTaxNumberType {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    bpTaxType: ").append(toIndentedString(bpTaxType)).append("\n");
    sb.append("    bpTaxNumber: ").append(toIndentedString(bpTaxNumber)).append("\n");
    sb.append("    bpTaxLongNumber: ").append(toIndentedString(bpTaxLongNumber)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
