/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate {
  @JsonProperty("ContactPersonAuthorityType")
  private String contactPersonAuthorityType = null;

  @JsonProperty("ContactPersonDepartment")
  private String contactPersonDepartment = null;

  @JsonProperty("ContactPersonDepartmentName")
  private String contactPersonDepartmentName = null;

  @JsonProperty("ContactPersonFunction")
  private String contactPersonFunction = null;

  @JsonProperty("ContactPersonFunctionName")
  private String contactPersonFunctionName = null;

  @JsonProperty("ContactPersonRemarkText")
  private String contactPersonRemarkText = null;

  @JsonProperty("ContactPersonVIPType")
  private String contactPersonVIPType = null;

  @JsonProperty("EmailAddress")
  private String emailAddress = null;

  @JsonProperty("FaxNumber")
  private String faxNumber = null;

  @JsonProperty("FaxNumberExtension")
  private String faxNumberExtension = null;

  @JsonProperty("PhoneNumber")
  private String phoneNumber = null;

  @JsonProperty("PhoneNumberExtension")
  private String phoneNumberExtension = null;

  @JsonProperty("RelationshipCategory")
  private String relationshipCategory = null;

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate contactPersonAuthorityType(String contactPersonAuthorityType) {
    this.contactPersonAuthorityType = contactPersonAuthorityType;
    return this;
  }

   /**
   * Partner&#x27;s Authority
   * @return contactPersonAuthorityType
  **/
  public String getContactPersonAuthorityType() {
    return contactPersonAuthorityType;
  }

  public void setContactPersonAuthorityType(String contactPersonAuthorityType) {
    this.contactPersonAuthorityType = contactPersonAuthorityType;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate contactPersonDepartment(String contactPersonDepartment) {
    this.contactPersonDepartment = contactPersonDepartment;
    return this;
  }

   /**
   * Get contactPersonDepartment
   * @return contactPersonDepartment
  **/
  public String getContactPersonDepartment() {
    return contactPersonDepartment;
  }

  public void setContactPersonDepartment(String contactPersonDepartment) {
    this.contactPersonDepartment = contactPersonDepartment;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate contactPersonDepartmentName(String contactPersonDepartmentName) {
    this.contactPersonDepartmentName = contactPersonDepartmentName;
    return this;
  }

   /**
   * Department at business partner
   * @return contactPersonDepartmentName
  **/
  public String getContactPersonDepartmentName() {
    return contactPersonDepartmentName;
  }

  public void setContactPersonDepartmentName(String contactPersonDepartmentName) {
    this.contactPersonDepartmentName = contactPersonDepartmentName;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate contactPersonFunction(String contactPersonFunction) {
    this.contactPersonFunction = contactPersonFunction;
    return this;
  }

   /**
   * Function of partner
   * @return contactPersonFunction
  **/
  public String getContactPersonFunction() {
    return contactPersonFunction;
  }

  public void setContactPersonFunction(String contactPersonFunction) {
    this.contactPersonFunction = contactPersonFunction;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate contactPersonFunctionName(String contactPersonFunctionName) {
    this.contactPersonFunctionName = contactPersonFunctionName;
    return this;
  }

   /**
   * Function name of partner
   * @return contactPersonFunctionName
  **/
  public String getContactPersonFunctionName() {
    return contactPersonFunctionName;
  }

  public void setContactPersonFunctionName(String contactPersonFunctionName) {
    this.contactPersonFunctionName = contactPersonFunctionName;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate contactPersonRemarkText(String contactPersonRemarkText) {
    this.contactPersonRemarkText = contactPersonRemarkText;
    return this;
  }

   /**
   * Notes for Partner
   * @return contactPersonRemarkText
  **/
  public String getContactPersonRemarkText() {
    return contactPersonRemarkText;
  }

  public void setContactPersonRemarkText(String contactPersonRemarkText) {
    this.contactPersonRemarkText = contactPersonRemarkText;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate contactPersonVIPType(String contactPersonVIPType) {
    this.contactPersonVIPType = contactPersonVIPType;
    return this;
  }

   /**
   * VIP Partner
   * @return contactPersonVIPType
  **/
  public String getContactPersonVIPType() {
    return contactPersonVIPType;
  }

  public void setContactPersonVIPType(String contactPersonVIPType) {
    this.contactPersonVIPType = contactPersonVIPType;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Get emailAddress
   * @return emailAddress
  **/
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate faxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

   /**
   * Fax Number: Dialing Code and Number
   * @return faxNumber
  **/
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate faxNumberExtension(String faxNumberExtension) {
    this.faxNumberExtension = faxNumberExtension;
    return this;
  }

   /**
   * Fax no.: Extension
   * @return faxNumberExtension
  **/
  public String getFaxNumberExtension() {
    return faxNumberExtension;
  }

  public void setFaxNumberExtension(String faxNumberExtension) {
    this.faxNumberExtension = faxNumberExtension;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Telephone No.: Dialing Code and Number
   * @return phoneNumber
  **/
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate phoneNumberExtension(String phoneNumberExtension) {
    this.phoneNumberExtension = phoneNumberExtension;
    return this;
  }

   /**
   * Telephone no.: Extension
   * @return phoneNumberExtension
  **/
  public String getPhoneNumberExtension() {
    return phoneNumberExtension;
  }

  public void setPhoneNumberExtension(String phoneNumberExtension) {
    this.phoneNumberExtension = phoneNumberExtension;
  }

  public APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate relationshipCategory(String relationshipCategory) {
    this.relationshipCategory = relationshipCategory;
    return this;
  }

   /**
   * Business Partner Relationship Category
   * @return relationshipCategory
  **/
  public String getRelationshipCategory() {
    return relationshipCategory;
  }

  public void setRelationshipCategory(String relationshipCategory) {
    this.relationshipCategory = relationshipCategory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate = (APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate) o;
    return Objects.equals(this.contactPersonAuthorityType, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.contactPersonAuthorityType) &&
        Objects.equals(this.contactPersonDepartment, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.contactPersonDepartment) &&
        Objects.equals(this.contactPersonDepartmentName, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.contactPersonDepartmentName) &&
        Objects.equals(this.contactPersonFunction, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.contactPersonFunction) &&
        Objects.equals(this.contactPersonFunctionName, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.contactPersonFunctionName) &&
        Objects.equals(this.contactPersonRemarkText, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.contactPersonRemarkText) &&
        Objects.equals(this.contactPersonVIPType, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.contactPersonVIPType) &&
        Objects.equals(this.emailAddress, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.emailAddress) &&
        Objects.equals(this.faxNumber, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.faxNumber) &&
        Objects.equals(this.faxNumberExtension, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.faxNumberExtension) &&
        Objects.equals(this.phoneNumber, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.phoneNumber) &&
        Objects.equals(this.phoneNumberExtension, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.phoneNumberExtension) &&
        Objects.equals(this.relationshipCategory, apIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate.relationshipCategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactPersonAuthorityType, contactPersonDepartment, contactPersonDepartmentName, contactPersonFunction, contactPersonFunctionName, contactPersonRemarkText, contactPersonVIPType, emailAddress, faxNumber, faxNumberExtension, phoneNumber, phoneNumberExtension, relationshipCategory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABPContactToFuncAndDeptTypeUpdate {\n");
    
    sb.append("    contactPersonAuthorityType: ").append(toIndentedString(contactPersonAuthorityType)).append("\n");
    sb.append("    contactPersonDepartment: ").append(toIndentedString(contactPersonDepartment)).append("\n");
    sb.append("    contactPersonDepartmentName: ").append(toIndentedString(contactPersonDepartmentName)).append("\n");
    sb.append("    contactPersonFunction: ").append(toIndentedString(contactPersonFunction)).append("\n");
    sb.append("    contactPersonFunctionName: ").append(toIndentedString(contactPersonFunctionName)).append("\n");
    sb.append("    contactPersonRemarkText: ").append(toIndentedString(contactPersonRemarkText)).append("\n");
    sb.append("    contactPersonVIPType: ").append(toIndentedString(contactPersonVIPType)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    faxNumberExtension: ").append(toIndentedString(faxNumberExtension)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    phoneNumberExtension: ").append(toIndentedString(phoneNumberExtension)).append("\n");
    sb.append("    relationshipCategory: ").append(toIndentedString(relationshipCategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
