/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERAAddressEmailAddressTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERAAddressEmailAddressTypeCreate {
  @JsonProperty("AddressID")
  private String addressID = null;

  @JsonProperty("Person")
  private String person = null;

  @JsonProperty("OrdinalNumber")
  private String ordinalNumber = null;

  @JsonProperty("IsDefaultEmailAddress")
  private Boolean isDefaultEmailAddress = null;

  @JsonProperty("EmailAddress")
  private String emailAddress = null;

  @JsonProperty("AddressCommunicationRemarkText")
  private String addressCommunicationRemarkText = null;

  public APIBUSINESSPARTNERAAddressEmailAddressTypeCreate addressID(String addressID) {
    this.addressID = addressID;
    return this;
  }

   /**
   * Get addressID
   * @return addressID
  **/
  public String getAddressID() {
    return addressID;
  }

  public void setAddressID(String addressID) {
    this.addressID = addressID;
  }

  public APIBUSINESSPARTNERAAddressEmailAddressTypeCreate person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public APIBUSINESSPARTNERAAddressEmailAddressTypeCreate ordinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
    return this;
  }

   /**
   * Get ordinalNumber
   * @return ordinalNumber
  **/
  public String getOrdinalNumber() {
    return ordinalNumber;
  }

  public void setOrdinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
  }

  public APIBUSINESSPARTNERAAddressEmailAddressTypeCreate isDefaultEmailAddress(Boolean isDefaultEmailAddress) {
    this.isDefaultEmailAddress = isDefaultEmailAddress;
    return this;
  }

   /**
   * Flag: this address is the default address
   * @return isDefaultEmailAddress
  **/
  public Boolean isIsDefaultEmailAddress() {
    return isDefaultEmailAddress;
  }

  public void setIsDefaultEmailAddress(Boolean isDefaultEmailAddress) {
    this.isDefaultEmailAddress = isDefaultEmailAddress;
  }

  public APIBUSINESSPARTNERAAddressEmailAddressTypeCreate emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Get emailAddress
   * @return emailAddress
  **/
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public APIBUSINESSPARTNERAAddressEmailAddressTypeCreate addressCommunicationRemarkText(String addressCommunicationRemarkText) {
    this.addressCommunicationRemarkText = addressCommunicationRemarkText;
    return this;
  }

   /**
   * Communication link notes
   * @return addressCommunicationRemarkText
  **/
  public String getAddressCommunicationRemarkText() {
    return addressCommunicationRemarkText;
  }

  public void setAddressCommunicationRemarkText(String addressCommunicationRemarkText) {
    this.addressCommunicationRemarkText = addressCommunicationRemarkText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERAAddressEmailAddressTypeCreate apIBUSINESSPARTNERAAddressEmailAddressTypeCreate = (APIBUSINESSPARTNERAAddressEmailAddressTypeCreate) o;
    return Objects.equals(this.addressID, apIBUSINESSPARTNERAAddressEmailAddressTypeCreate.addressID) &&
        Objects.equals(this.person, apIBUSINESSPARTNERAAddressEmailAddressTypeCreate.person) &&
        Objects.equals(this.ordinalNumber, apIBUSINESSPARTNERAAddressEmailAddressTypeCreate.ordinalNumber) &&
        Objects.equals(this.isDefaultEmailAddress, apIBUSINESSPARTNERAAddressEmailAddressTypeCreate.isDefaultEmailAddress) &&
        Objects.equals(this.emailAddress, apIBUSINESSPARTNERAAddressEmailAddressTypeCreate.emailAddress) &&
        Objects.equals(this.addressCommunicationRemarkText, apIBUSINESSPARTNERAAddressEmailAddressTypeCreate.addressCommunicationRemarkText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressID, person, ordinalNumber, isDefaultEmailAddress, emailAddress, addressCommunicationRemarkText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERAAddressEmailAddressTypeCreate {\n");
    
    sb.append("    addressID: ").append(toIndentedString(addressID)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    ordinalNumber: ").append(toIndentedString(ordinalNumber)).append("\n");
    sb.append("    isDefaultEmailAddress: ").append(toIndentedString(isDefaultEmailAddress)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    addressCommunicationRemarkText: ").append(toIndentedString(addressCommunicationRemarkText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
