/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERAAddressHomePageURLTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERAAddressHomePageURLTypeUpdate {
  @JsonProperty("AddressCommunicationRemarkText")
  private String addressCommunicationRemarkText = null;

  @JsonProperty("WebsiteURL")
  private String websiteURL = null;

  public APIBUSINESSPARTNERAAddressHomePageURLTypeUpdate addressCommunicationRemarkText(String addressCommunicationRemarkText) {
    this.addressCommunicationRemarkText = addressCommunicationRemarkText;
    return this;
  }

   /**
   * Communication link notes
   * @return addressCommunicationRemarkText
  **/
  public String getAddressCommunicationRemarkText() {
    return addressCommunicationRemarkText;
  }

  public void setAddressCommunicationRemarkText(String addressCommunicationRemarkText) {
    this.addressCommunicationRemarkText = addressCommunicationRemarkText;
  }

  public APIBUSINESSPARTNERAAddressHomePageURLTypeUpdate websiteURL(String websiteURL) {
    this.websiteURL = websiteURL;
    return this;
  }

   /**
   * Universal Resource Identifier (URI)
   * @return websiteURL
  **/
  public String getWebsiteURL() {
    return websiteURL;
  }

  public void setWebsiteURL(String websiteURL) {
    this.websiteURL = websiteURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERAAddressHomePageURLTypeUpdate apIBUSINESSPARTNERAAddressHomePageURLTypeUpdate = (APIBUSINESSPARTNERAAddressHomePageURLTypeUpdate) o;
    return Objects.equals(this.addressCommunicationRemarkText, apIBUSINESSPARTNERAAddressHomePageURLTypeUpdate.addressCommunicationRemarkText) &&
        Objects.equals(this.websiteURL, apIBUSINESSPARTNERAAddressHomePageURLTypeUpdate.websiteURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressCommunicationRemarkText, websiteURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERAAddressHomePageURLTypeUpdate {\n");
    
    sb.append("    addressCommunicationRemarkText: ").append(toIndentedString(addressCommunicationRemarkText)).append("\n");
    sb.append("    websiteURL: ").append(toIndentedString(websiteURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
