/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.axon.market.s4hana.client.APIBUSINESSPARTNERACustomerCompanyTypecreateToCompanyText;
import com.axon.market.s4hana.client.APIBUSINESSPARTNERACustomerCompanyTypecreateToCustomerDunning;
import com.axon.market.s4hana.client.APIBUSINESSPARTNERACustomerCompanyTypecreateToWithHoldingTax;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERACustomerCompanyTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERACustomerCompanyTypeCreate {
  @JsonProperty("Customer")
  private String customer = null;

  @JsonProperty("CompanyCode")
  private String companyCode = null;

  @JsonProperty("APARToleranceGroup")
  private String apARToleranceGroup = null;

  @JsonProperty("AccountByCustomer")
  private String accountByCustomer = null;

  @JsonProperty("AccountingClerk")
  private String accountingClerk = null;

  @JsonProperty("AccountingClerkFaxNumber")
  private String accountingClerkFaxNumber = null;

  @JsonProperty("AccountingClerkInternetAddress")
  private String accountingClerkInternetAddress = null;

  @JsonProperty("AccountingClerkPhoneNumber")
  private String accountingClerkPhoneNumber = null;

  @JsonProperty("AlternativePayerAccount")
  private String alternativePayerAccount = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  @JsonProperty("CollectiveInvoiceVariant")
  private String collectiveInvoiceVariant = null;

  @JsonProperty("CustomerAccountNote")
  private String customerAccountNote = null;

  @JsonProperty("CustomerHeadOffice")
  private String customerHeadOffice = null;

  @JsonProperty("CustomerSupplierClearingIsUsed")
  private Boolean customerSupplierClearingIsUsed = null;

  @JsonProperty("HouseBank")
  private String houseBank = null;

  @JsonProperty("InterestCalculationCode")
  private String interestCalculationCode = null;

  @JsonProperty("InterestCalculationDate")
  private String interestCalculationDate = null;

  @JsonProperty("IntrstCalcFrequencyInMonths")
  private String intrstCalcFrequencyInMonths = null;

  @JsonProperty("IsToBeLocallyProcessed")
  private Boolean isToBeLocallyProcessed = null;

  @JsonProperty("ItemIsToBePaidSeparately")
  private Boolean itemIsToBePaidSeparately = null;

  @JsonProperty("LayoutSortingRule")
  private String layoutSortingRule = null;

  @JsonProperty("PaymentBlockingReason")
  private String paymentBlockingReason = null;

  @JsonProperty("PaymentMethodsList")
  private String paymentMethodsList = null;

  @JsonProperty("PaymentReason")
  private String paymentReason = null;

  @JsonProperty("PaymentTerms")
  private String paymentTerms = null;

  @JsonProperty("PaytAdviceIsSentbyEDI")
  private Boolean paytAdviceIsSentbyEDI = null;

  @JsonProperty("PhysicalInventoryBlockInd")
  private Boolean physicalInventoryBlockInd = null;

  @JsonProperty("ReconciliationAccount")
  private String reconciliationAccount = null;

  @JsonProperty("RecordPaymentHistoryIndicator")
  private Boolean recordPaymentHistoryIndicator = null;

  @JsonProperty("UserAtCustomer")
  private String userAtCustomer = null;

  @JsonProperty("DeletionIndicator")
  private Boolean deletionIndicator = null;

  @JsonProperty("CashPlanningGroup")
  private String cashPlanningGroup = null;

  @JsonProperty("KnownOrNegotiatedLeave")
  private String knownOrNegotiatedLeave = null;

  @JsonProperty("ValueAdjustmentKey")
  private String valueAdjustmentKey = null;

  @JsonProperty("CustomerAccountGroup")
  private String customerAccountGroup = null;

  @JsonProperty("to_CompanyText")
  private APIBUSINESSPARTNERACustomerCompanyTypecreateToCompanyText toCompanyText = null;

  @JsonProperty("to_CustomerDunning")
  private APIBUSINESSPARTNERACustomerCompanyTypecreateToCustomerDunning toCustomerDunning = null;

  @JsonProperty("to_WithHoldingTax")
  private APIBUSINESSPARTNERACustomerCompanyTypecreateToWithHoldingTax toWithHoldingTax = null;

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate customer(String customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Customer Number
   * @return customer
  **/
  public String getCustomer() {
    return customer;
  }

  public void setCustomer(String customer) {
    this.customer = customer;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate companyCode(String companyCode) {
    this.companyCode = companyCode;
    return this;
  }

   /**
   * Get companyCode
   * @return companyCode
  **/
  public String getCompanyCode() {
    return companyCode;
  }

  public void setCompanyCode(String companyCode) {
    this.companyCode = companyCode;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate apARToleranceGroup(String apARToleranceGroup) {
    this.apARToleranceGroup = apARToleranceGroup;
    return this;
  }

   /**
   * Tolerance Group for Business Partner/G/L Account
   * @return apARToleranceGroup
  **/
  public String getApARToleranceGroup() {
    return apARToleranceGroup;
  }

  public void setApARToleranceGroup(String apARToleranceGroup) {
    this.apARToleranceGroup = apARToleranceGroup;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate accountByCustomer(String accountByCustomer) {
    this.accountByCustomer = accountByCustomer;
    return this;
  }

   /**
   * Our Account Number at Customer
   * @return accountByCustomer
  **/
  public String getAccountByCustomer() {
    return accountByCustomer;
  }

  public void setAccountByCustomer(String accountByCustomer) {
    this.accountByCustomer = accountByCustomer;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate accountingClerk(String accountingClerk) {
    this.accountingClerk = accountingClerk;
    return this;
  }

   /**
   * Accounting Clerk Abbreviation
   * @return accountingClerk
  **/
  public String getAccountingClerk() {
    return accountingClerk;
  }

  public void setAccountingClerk(String accountingClerk) {
    this.accountingClerk = accountingClerk;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate accountingClerkFaxNumber(String accountingClerkFaxNumber) {
    this.accountingClerkFaxNumber = accountingClerkFaxNumber;
    return this;
  }

   /**
   * Accounting clerk&#x27;s fax number at the customer/vendor
   * @return accountingClerkFaxNumber
  **/
  public String getAccountingClerkFaxNumber() {
    return accountingClerkFaxNumber;
  }

  public void setAccountingClerkFaxNumber(String accountingClerkFaxNumber) {
    this.accountingClerkFaxNumber = accountingClerkFaxNumber;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate accountingClerkInternetAddress(String accountingClerkInternetAddress) {
    this.accountingClerkInternetAddress = accountingClerkInternetAddress;
    return this;
  }

   /**
   * Internet address of partner company clerk
   * @return accountingClerkInternetAddress
  **/
  public String getAccountingClerkInternetAddress() {
    return accountingClerkInternetAddress;
  }

  public void setAccountingClerkInternetAddress(String accountingClerkInternetAddress) {
    this.accountingClerkInternetAddress = accountingClerkInternetAddress;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate accountingClerkPhoneNumber(String accountingClerkPhoneNumber) {
    this.accountingClerkPhoneNumber = accountingClerkPhoneNumber;
    return this;
  }

   /**
   * Accounting clerk&#x27;s telephone number at business partner
   * @return accountingClerkPhoneNumber
  **/
  public String getAccountingClerkPhoneNumber() {
    return accountingClerkPhoneNumber;
  }

  public void setAccountingClerkPhoneNumber(String accountingClerkPhoneNumber) {
    this.accountingClerkPhoneNumber = accountingClerkPhoneNumber;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate alternativePayerAccount(String alternativePayerAccount) {
    this.alternativePayerAccount = alternativePayerAccount;
    return this;
  }

   /**
   * Account number of an alternative payer
   * @return alternativePayerAccount
  **/
  public String getAlternativePayerAccount() {
    return alternativePayerAccount;
  }

  public void setAlternativePayerAccount(String alternativePayerAccount) {
    this.alternativePayerAccount = alternativePayerAccount;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Authorization Group
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate collectiveInvoiceVariant(String collectiveInvoiceVariant) {
    this.collectiveInvoiceVariant = collectiveInvoiceVariant;
    return this;
  }

   /**
   * Collective Invoice Variant
   * @return collectiveInvoiceVariant
  **/
  public String getCollectiveInvoiceVariant() {
    return collectiveInvoiceVariant;
  }

  public void setCollectiveInvoiceVariant(String collectiveInvoiceVariant) {
    this.collectiveInvoiceVariant = collectiveInvoiceVariant;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate customerAccountNote(String customerAccountNote) {
    this.customerAccountNote = customerAccountNote;
    return this;
  }

   /**
   * Memo
   * @return customerAccountNote
  **/
  public String getCustomerAccountNote() {
    return customerAccountNote;
  }

  public void setCustomerAccountNote(String customerAccountNote) {
    this.customerAccountNote = customerAccountNote;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate customerHeadOffice(String customerHeadOffice) {
    this.customerHeadOffice = customerHeadOffice;
    return this;
  }

   /**
   * Head Office Account Number (in branch accounts)
   * @return customerHeadOffice
  **/
  public String getCustomerHeadOffice() {
    return customerHeadOffice;
  }

  public void setCustomerHeadOffice(String customerHeadOffice) {
    this.customerHeadOffice = customerHeadOffice;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate customerSupplierClearingIsUsed(Boolean customerSupplierClearingIsUsed) {
    this.customerSupplierClearingIsUsed = customerSupplierClearingIsUsed;
    return this;
  }

   /**
   * Indicator: Clearing between customer and vendor ?
   * @return customerSupplierClearingIsUsed
  **/
  public Boolean isCustomerSupplierClearingIsUsed() {
    return customerSupplierClearingIsUsed;
  }

  public void setCustomerSupplierClearingIsUsed(Boolean customerSupplierClearingIsUsed) {
    this.customerSupplierClearingIsUsed = customerSupplierClearingIsUsed;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate houseBank(String houseBank) {
    this.houseBank = houseBank;
    return this;
  }

   /**
   * Short Key for a House Bank
   * @return houseBank
  **/
  public String getHouseBank() {
    return houseBank;
  }

  public void setHouseBank(String houseBank) {
    this.houseBank = houseBank;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate interestCalculationCode(String interestCalculationCode) {
    this.interestCalculationCode = interestCalculationCode;
    return this;
  }

   /**
   * Get interestCalculationCode
   * @return interestCalculationCode
  **/
  public String getInterestCalculationCode() {
    return interestCalculationCode;
  }

  public void setInterestCalculationCode(String interestCalculationCode) {
    this.interestCalculationCode = interestCalculationCode;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate interestCalculationDate(String interestCalculationDate) {
    this.interestCalculationDate = interestCalculationDate;
    return this;
  }

   /**
   * Key Date of Last Interest Calculation
   * @return interestCalculationDate
  **/
  public String getInterestCalculationDate() {
    return interestCalculationDate;
  }

  public void setInterestCalculationDate(String interestCalculationDate) {
    this.interestCalculationDate = interestCalculationDate;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate intrstCalcFrequencyInMonths(String intrstCalcFrequencyInMonths) {
    this.intrstCalcFrequencyInMonths = intrstCalcFrequencyInMonths;
    return this;
  }

   /**
   * Interest Calculation Frequency in Months
   * @return intrstCalcFrequencyInMonths
  **/
  public String getIntrstCalcFrequencyInMonths() {
    return intrstCalcFrequencyInMonths;
  }

  public void setIntrstCalcFrequencyInMonths(String intrstCalcFrequencyInMonths) {
    this.intrstCalcFrequencyInMonths = intrstCalcFrequencyInMonths;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate isToBeLocallyProcessed(Boolean isToBeLocallyProcessed) {
    this.isToBeLocallyProcessed = isToBeLocallyProcessed;
    return this;
  }

   /**
   * Indicator: Local Processing?
   * @return isToBeLocallyProcessed
  **/
  public Boolean isIsToBeLocallyProcessed() {
    return isToBeLocallyProcessed;
  }

  public void setIsToBeLocallyProcessed(Boolean isToBeLocallyProcessed) {
    this.isToBeLocallyProcessed = isToBeLocallyProcessed;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate itemIsToBePaidSeparately(Boolean itemIsToBePaidSeparately) {
    this.itemIsToBePaidSeparately = itemIsToBePaidSeparately;
    return this;
  }

   /**
   * Indicator: Pay All Items Separately?
   * @return itemIsToBePaidSeparately
  **/
  public Boolean isItemIsToBePaidSeparately() {
    return itemIsToBePaidSeparately;
  }

  public void setItemIsToBePaidSeparately(Boolean itemIsToBePaidSeparately) {
    this.itemIsToBePaidSeparately = itemIsToBePaidSeparately;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate layoutSortingRule(String layoutSortingRule) {
    this.layoutSortingRule = layoutSortingRule;
    return this;
  }

   /**
   * Key for Sorting According to Assignment Numbers
   * @return layoutSortingRule
  **/
  public String getLayoutSortingRule() {
    return layoutSortingRule;
  }

  public void setLayoutSortingRule(String layoutSortingRule) {
    this.layoutSortingRule = layoutSortingRule;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate paymentBlockingReason(String paymentBlockingReason) {
    this.paymentBlockingReason = paymentBlockingReason;
    return this;
  }

   /**
   * Block Key for Payment
   * @return paymentBlockingReason
  **/
  public String getPaymentBlockingReason() {
    return paymentBlockingReason;
  }

  public void setPaymentBlockingReason(String paymentBlockingReason) {
    this.paymentBlockingReason = paymentBlockingReason;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate paymentMethodsList(String paymentMethodsList) {
    this.paymentMethodsList = paymentMethodsList;
    return this;
  }

   /**
   * List of Respected Payment Methods
   * @return paymentMethodsList
  **/
  public String getPaymentMethodsList() {
    return paymentMethodsList;
  }

  public void setPaymentMethodsList(String paymentMethodsList) {
    this.paymentMethodsList = paymentMethodsList;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate paymentReason(String paymentReason) {
    this.paymentReason = paymentReason;
    return this;
  }

   /**
   * Get paymentReason
   * @return paymentReason
  **/
  public String getPaymentReason() {
    return paymentReason;
  }

  public void setPaymentReason(String paymentReason) {
    this.paymentReason = paymentReason;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate paymentTerms(String paymentTerms) {
    this.paymentTerms = paymentTerms;
    return this;
  }

   /**
   * Key for Terms of Payment
   * @return paymentTerms
  **/
  public String getPaymentTerms() {
    return paymentTerms;
  }

  public void setPaymentTerms(String paymentTerms) {
    this.paymentTerms = paymentTerms;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate paytAdviceIsSentbyEDI(Boolean paytAdviceIsSentbyEDI) {
    this.paytAdviceIsSentbyEDI = paytAdviceIsSentbyEDI;
    return this;
  }

   /**
   * Indicator: Send Payment Advices by EDI
   * @return paytAdviceIsSentbyEDI
  **/
  public Boolean isPaytAdviceIsSentbyEDI() {
    return paytAdviceIsSentbyEDI;
  }

  public void setPaytAdviceIsSentbyEDI(Boolean paytAdviceIsSentbyEDI) {
    this.paytAdviceIsSentbyEDI = paytAdviceIsSentbyEDI;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate physicalInventoryBlockInd(Boolean physicalInventoryBlockInd) {
    this.physicalInventoryBlockInd = physicalInventoryBlockInd;
    return this;
  }

   /**
   * Posting block for company code
   * @return physicalInventoryBlockInd
  **/
  public Boolean isPhysicalInventoryBlockInd() {
    return physicalInventoryBlockInd;
  }

  public void setPhysicalInventoryBlockInd(Boolean physicalInventoryBlockInd) {
    this.physicalInventoryBlockInd = physicalInventoryBlockInd;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate reconciliationAccount(String reconciliationAccount) {
    this.reconciliationAccount = reconciliationAccount;
    return this;
  }

   /**
   * Reconciliation Account in General Ledger
   * @return reconciliationAccount
  **/
  public String getReconciliationAccount() {
    return reconciliationAccount;
  }

  public void setReconciliationAccount(String reconciliationAccount) {
    this.reconciliationAccount = reconciliationAccount;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate recordPaymentHistoryIndicator(Boolean recordPaymentHistoryIndicator) {
    this.recordPaymentHistoryIndicator = recordPaymentHistoryIndicator;
    return this;
  }

   /**
   * Indicator: Record Payment History ?
   * @return recordPaymentHistoryIndicator
  **/
  public Boolean isRecordPaymentHistoryIndicator() {
    return recordPaymentHistoryIndicator;
  }

  public void setRecordPaymentHistoryIndicator(Boolean recordPaymentHistoryIndicator) {
    this.recordPaymentHistoryIndicator = recordPaymentHistoryIndicator;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate userAtCustomer(String userAtCustomer) {
    this.userAtCustomer = userAtCustomer;
    return this;
  }

   /**
   * Get userAtCustomer
   * @return userAtCustomer
  **/
  public String getUserAtCustomer() {
    return userAtCustomer;
  }

  public void setUserAtCustomer(String userAtCustomer) {
    this.userAtCustomer = userAtCustomer;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate deletionIndicator(Boolean deletionIndicator) {
    this.deletionIndicator = deletionIndicator;
    return this;
  }

   /**
   * Deletion Flag for Master Record (Company Code Level)
   * @return deletionIndicator
  **/
  public Boolean isDeletionIndicator() {
    return deletionIndicator;
  }

  public void setDeletionIndicator(Boolean deletionIndicator) {
    this.deletionIndicator = deletionIndicator;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate cashPlanningGroup(String cashPlanningGroup) {
    this.cashPlanningGroup = cashPlanningGroup;
    return this;
  }

   /**
   * Get cashPlanningGroup
   * @return cashPlanningGroup
  **/
  public String getCashPlanningGroup() {
    return cashPlanningGroup;
  }

  public void setCashPlanningGroup(String cashPlanningGroup) {
    this.cashPlanningGroup = cashPlanningGroup;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate knownOrNegotiatedLeave(String knownOrNegotiatedLeave) {
    this.knownOrNegotiatedLeave = knownOrNegotiatedLeave;
    return this;
  }

   /**
   * Short Key for Known/Negotiated Leave
   * @return knownOrNegotiatedLeave
  **/
  public String getKnownOrNegotiatedLeave() {
    return knownOrNegotiatedLeave;
  }

  public void setKnownOrNegotiatedLeave(String knownOrNegotiatedLeave) {
    this.knownOrNegotiatedLeave = knownOrNegotiatedLeave;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate valueAdjustmentKey(String valueAdjustmentKey) {
    this.valueAdjustmentKey = valueAdjustmentKey;
    return this;
  }

   /**
   * Value Adjustment Key
   * @return valueAdjustmentKey
  **/
  public String getValueAdjustmentKey() {
    return valueAdjustmentKey;
  }

  public void setValueAdjustmentKey(String valueAdjustmentKey) {
    this.valueAdjustmentKey = valueAdjustmentKey;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate customerAccountGroup(String customerAccountGroup) {
    this.customerAccountGroup = customerAccountGroup;
    return this;
  }

   /**
   * Customer Account Group
   * @return customerAccountGroup
  **/
  public String getCustomerAccountGroup() {
    return customerAccountGroup;
  }

  public void setCustomerAccountGroup(String customerAccountGroup) {
    this.customerAccountGroup = customerAccountGroup;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate toCompanyText(APIBUSINESSPARTNERACustomerCompanyTypecreateToCompanyText toCompanyText) {
    this.toCompanyText = toCompanyText;
    return this;
  }

   /**
   * Get toCompanyText
   * @return toCompanyText
  **/
  public APIBUSINESSPARTNERACustomerCompanyTypecreateToCompanyText getToCompanyText() {
    return toCompanyText;
  }

  public void setToCompanyText(APIBUSINESSPARTNERACustomerCompanyTypecreateToCompanyText toCompanyText) {
    this.toCompanyText = toCompanyText;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate toCustomerDunning(APIBUSINESSPARTNERACustomerCompanyTypecreateToCustomerDunning toCustomerDunning) {
    this.toCustomerDunning = toCustomerDunning;
    return this;
  }

   /**
   * Get toCustomerDunning
   * @return toCustomerDunning
  **/
  public APIBUSINESSPARTNERACustomerCompanyTypecreateToCustomerDunning getToCustomerDunning() {
    return toCustomerDunning;
  }

  public void setToCustomerDunning(APIBUSINESSPARTNERACustomerCompanyTypecreateToCustomerDunning toCustomerDunning) {
    this.toCustomerDunning = toCustomerDunning;
  }

  public APIBUSINESSPARTNERACustomerCompanyTypeCreate toWithHoldingTax(APIBUSINESSPARTNERACustomerCompanyTypecreateToWithHoldingTax toWithHoldingTax) {
    this.toWithHoldingTax = toWithHoldingTax;
    return this;
  }

   /**
   * Get toWithHoldingTax
   * @return toWithHoldingTax
  **/
  public APIBUSINESSPARTNERACustomerCompanyTypecreateToWithHoldingTax getToWithHoldingTax() {
    return toWithHoldingTax;
  }

  public void setToWithHoldingTax(APIBUSINESSPARTNERACustomerCompanyTypecreateToWithHoldingTax toWithHoldingTax) {
    this.toWithHoldingTax = toWithHoldingTax;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERACustomerCompanyTypeCreate apIBUSINESSPARTNERACustomerCompanyTypeCreate = (APIBUSINESSPARTNERACustomerCompanyTypeCreate) o;
    return Objects.equals(this.customer, apIBUSINESSPARTNERACustomerCompanyTypeCreate.customer) &&
        Objects.equals(this.companyCode, apIBUSINESSPARTNERACustomerCompanyTypeCreate.companyCode) &&
        Objects.equals(this.apARToleranceGroup, apIBUSINESSPARTNERACustomerCompanyTypeCreate.apARToleranceGroup) &&
        Objects.equals(this.accountByCustomer, apIBUSINESSPARTNERACustomerCompanyTypeCreate.accountByCustomer) &&
        Objects.equals(this.accountingClerk, apIBUSINESSPARTNERACustomerCompanyTypeCreate.accountingClerk) &&
        Objects.equals(this.accountingClerkFaxNumber, apIBUSINESSPARTNERACustomerCompanyTypeCreate.accountingClerkFaxNumber) &&
        Objects.equals(this.accountingClerkInternetAddress, apIBUSINESSPARTNERACustomerCompanyTypeCreate.accountingClerkInternetAddress) &&
        Objects.equals(this.accountingClerkPhoneNumber, apIBUSINESSPARTNERACustomerCompanyTypeCreate.accountingClerkPhoneNumber) &&
        Objects.equals(this.alternativePayerAccount, apIBUSINESSPARTNERACustomerCompanyTypeCreate.alternativePayerAccount) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERACustomerCompanyTypeCreate.authorizationGroup) &&
        Objects.equals(this.collectiveInvoiceVariant, apIBUSINESSPARTNERACustomerCompanyTypeCreate.collectiveInvoiceVariant) &&
        Objects.equals(this.customerAccountNote, apIBUSINESSPARTNERACustomerCompanyTypeCreate.customerAccountNote) &&
        Objects.equals(this.customerHeadOffice, apIBUSINESSPARTNERACustomerCompanyTypeCreate.customerHeadOffice) &&
        Objects.equals(this.customerSupplierClearingIsUsed, apIBUSINESSPARTNERACustomerCompanyTypeCreate.customerSupplierClearingIsUsed) &&
        Objects.equals(this.houseBank, apIBUSINESSPARTNERACustomerCompanyTypeCreate.houseBank) &&
        Objects.equals(this.interestCalculationCode, apIBUSINESSPARTNERACustomerCompanyTypeCreate.interestCalculationCode) &&
        Objects.equals(this.interestCalculationDate, apIBUSINESSPARTNERACustomerCompanyTypeCreate.interestCalculationDate) &&
        Objects.equals(this.intrstCalcFrequencyInMonths, apIBUSINESSPARTNERACustomerCompanyTypeCreate.intrstCalcFrequencyInMonths) &&
        Objects.equals(this.isToBeLocallyProcessed, apIBUSINESSPARTNERACustomerCompanyTypeCreate.isToBeLocallyProcessed) &&
        Objects.equals(this.itemIsToBePaidSeparately, apIBUSINESSPARTNERACustomerCompanyTypeCreate.itemIsToBePaidSeparately) &&
        Objects.equals(this.layoutSortingRule, apIBUSINESSPARTNERACustomerCompanyTypeCreate.layoutSortingRule) &&
        Objects.equals(this.paymentBlockingReason, apIBUSINESSPARTNERACustomerCompanyTypeCreate.paymentBlockingReason) &&
        Objects.equals(this.paymentMethodsList, apIBUSINESSPARTNERACustomerCompanyTypeCreate.paymentMethodsList) &&
        Objects.equals(this.paymentReason, apIBUSINESSPARTNERACustomerCompanyTypeCreate.paymentReason) &&
        Objects.equals(this.paymentTerms, apIBUSINESSPARTNERACustomerCompanyTypeCreate.paymentTerms) &&
        Objects.equals(this.paytAdviceIsSentbyEDI, apIBUSINESSPARTNERACustomerCompanyTypeCreate.paytAdviceIsSentbyEDI) &&
        Objects.equals(this.physicalInventoryBlockInd, apIBUSINESSPARTNERACustomerCompanyTypeCreate.physicalInventoryBlockInd) &&
        Objects.equals(this.reconciliationAccount, apIBUSINESSPARTNERACustomerCompanyTypeCreate.reconciliationAccount) &&
        Objects.equals(this.recordPaymentHistoryIndicator, apIBUSINESSPARTNERACustomerCompanyTypeCreate.recordPaymentHistoryIndicator) &&
        Objects.equals(this.userAtCustomer, apIBUSINESSPARTNERACustomerCompanyTypeCreate.userAtCustomer) &&
        Objects.equals(this.deletionIndicator, apIBUSINESSPARTNERACustomerCompanyTypeCreate.deletionIndicator) &&
        Objects.equals(this.cashPlanningGroup, apIBUSINESSPARTNERACustomerCompanyTypeCreate.cashPlanningGroup) &&
        Objects.equals(this.knownOrNegotiatedLeave, apIBUSINESSPARTNERACustomerCompanyTypeCreate.knownOrNegotiatedLeave) &&
        Objects.equals(this.valueAdjustmentKey, apIBUSINESSPARTNERACustomerCompanyTypeCreate.valueAdjustmentKey) &&
        Objects.equals(this.customerAccountGroup, apIBUSINESSPARTNERACustomerCompanyTypeCreate.customerAccountGroup) &&
        Objects.equals(this.toCompanyText, apIBUSINESSPARTNERACustomerCompanyTypeCreate.toCompanyText) &&
        Objects.equals(this.toCustomerDunning, apIBUSINESSPARTNERACustomerCompanyTypeCreate.toCustomerDunning) &&
        Objects.equals(this.toWithHoldingTax, apIBUSINESSPARTNERACustomerCompanyTypeCreate.toWithHoldingTax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customer, companyCode, apARToleranceGroup, accountByCustomer, accountingClerk, accountingClerkFaxNumber, accountingClerkInternetAddress, accountingClerkPhoneNumber, alternativePayerAccount, authorizationGroup, collectiveInvoiceVariant, customerAccountNote, customerHeadOffice, customerSupplierClearingIsUsed, houseBank, interestCalculationCode, interestCalculationDate, intrstCalcFrequencyInMonths, isToBeLocallyProcessed, itemIsToBePaidSeparately, layoutSortingRule, paymentBlockingReason, paymentMethodsList, paymentReason, paymentTerms, paytAdviceIsSentbyEDI, physicalInventoryBlockInd, reconciliationAccount, recordPaymentHistoryIndicator, userAtCustomer, deletionIndicator, cashPlanningGroup, knownOrNegotiatedLeave, valueAdjustmentKey, customerAccountGroup, toCompanyText, toCustomerDunning, toWithHoldingTax);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERACustomerCompanyTypeCreate {\n");
    
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    apARToleranceGroup: ").append(toIndentedString(apARToleranceGroup)).append("\n");
    sb.append("    accountByCustomer: ").append(toIndentedString(accountByCustomer)).append("\n");
    sb.append("    accountingClerk: ").append(toIndentedString(accountingClerk)).append("\n");
    sb.append("    accountingClerkFaxNumber: ").append(toIndentedString(accountingClerkFaxNumber)).append("\n");
    sb.append("    accountingClerkInternetAddress: ").append(toIndentedString(accountingClerkInternetAddress)).append("\n");
    sb.append("    accountingClerkPhoneNumber: ").append(toIndentedString(accountingClerkPhoneNumber)).append("\n");
    sb.append("    alternativePayerAccount: ").append(toIndentedString(alternativePayerAccount)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("    collectiveInvoiceVariant: ").append(toIndentedString(collectiveInvoiceVariant)).append("\n");
    sb.append("    customerAccountNote: ").append(toIndentedString(customerAccountNote)).append("\n");
    sb.append("    customerHeadOffice: ").append(toIndentedString(customerHeadOffice)).append("\n");
    sb.append("    customerSupplierClearingIsUsed: ").append(toIndentedString(customerSupplierClearingIsUsed)).append("\n");
    sb.append("    houseBank: ").append(toIndentedString(houseBank)).append("\n");
    sb.append("    interestCalculationCode: ").append(toIndentedString(interestCalculationCode)).append("\n");
    sb.append("    interestCalculationDate: ").append(toIndentedString(interestCalculationDate)).append("\n");
    sb.append("    intrstCalcFrequencyInMonths: ").append(toIndentedString(intrstCalcFrequencyInMonths)).append("\n");
    sb.append("    isToBeLocallyProcessed: ").append(toIndentedString(isToBeLocallyProcessed)).append("\n");
    sb.append("    itemIsToBePaidSeparately: ").append(toIndentedString(itemIsToBePaidSeparately)).append("\n");
    sb.append("    layoutSortingRule: ").append(toIndentedString(layoutSortingRule)).append("\n");
    sb.append("    paymentBlockingReason: ").append(toIndentedString(paymentBlockingReason)).append("\n");
    sb.append("    paymentMethodsList: ").append(toIndentedString(paymentMethodsList)).append("\n");
    sb.append("    paymentReason: ").append(toIndentedString(paymentReason)).append("\n");
    sb.append("    paymentTerms: ").append(toIndentedString(paymentTerms)).append("\n");
    sb.append("    paytAdviceIsSentbyEDI: ").append(toIndentedString(paytAdviceIsSentbyEDI)).append("\n");
    sb.append("    physicalInventoryBlockInd: ").append(toIndentedString(physicalInventoryBlockInd)).append("\n");
    sb.append("    reconciliationAccount: ").append(toIndentedString(reconciliationAccount)).append("\n");
    sb.append("    recordPaymentHistoryIndicator: ").append(toIndentedString(recordPaymentHistoryIndicator)).append("\n");
    sb.append("    userAtCustomer: ").append(toIndentedString(userAtCustomer)).append("\n");
    sb.append("    deletionIndicator: ").append(toIndentedString(deletionIndicator)).append("\n");
    sb.append("    cashPlanningGroup: ").append(toIndentedString(cashPlanningGroup)).append("\n");
    sb.append("    knownOrNegotiatedLeave: ").append(toIndentedString(knownOrNegotiatedLeave)).append("\n");
    sb.append("    valueAdjustmentKey: ").append(toIndentedString(valueAdjustmentKey)).append("\n");
    sb.append("    customerAccountGroup: ").append(toIndentedString(customerAccountGroup)).append("\n");
    sb.append("    toCompanyText: ").append(toIndentedString(toCompanyText)).append("\n");
    sb.append("    toCustomerDunning: ").append(toIndentedString(toCustomerDunning)).append("\n");
    sb.append("    toWithHoldingTax: ").append(toIndentedString(toWithHoldingTax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
