/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate {
  @JsonProperty("DestinationLocationCountry")
  private String destinationLocationCountry = null;

  @JsonProperty("IsDefaultPhoneNumber")
  private Boolean isDefaultPhoneNumber = null;

  @JsonProperty("PhoneNumber")
  private String phoneNumber = null;

  @JsonProperty("PhoneNumberExtension")
  private String phoneNumberExtension = null;

  @JsonProperty("ValidityStartDate")
  private String validityStartDate = null;

  @JsonProperty("ValidityEndDate")
  private String validityEndDate = null;

  public APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate destinationLocationCountry(String destinationLocationCountry) {
    this.destinationLocationCountry = destinationLocationCountry;
    return this;
  }

   /**
   * Country/Region for Telephone/Fax Number
   * @return destinationLocationCountry
  **/
  public String getDestinationLocationCountry() {
    return destinationLocationCountry;
  }

  public void setDestinationLocationCountry(String destinationLocationCountry) {
    this.destinationLocationCountry = destinationLocationCountry;
  }

  public APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate isDefaultPhoneNumber(Boolean isDefaultPhoneNumber) {
    this.isDefaultPhoneNumber = isDefaultPhoneNumber;
    return this;
  }

   /**
   * Data element for domain BOOLE: TRUE (&#x3D;&#x27;X&#x27;) and FALSE (&#x3D;&#x27; &#x27;)
   * @return isDefaultPhoneNumber
  **/
  public Boolean isIsDefaultPhoneNumber() {
    return isDefaultPhoneNumber;
  }

  public void setIsDefaultPhoneNumber(Boolean isDefaultPhoneNumber) {
    this.isDefaultPhoneNumber = isDefaultPhoneNumber;
  }

  public APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Telephone No.: Dialing Code and Number
   * @return phoneNumber
  **/
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate phoneNumberExtension(String phoneNumberExtension) {
    this.phoneNumberExtension = phoneNumberExtension;
    return this;
  }

   /**
   * Telephone no.: Extension
   * @return phoneNumberExtension
  **/
  public String getPhoneNumberExtension() {
    return phoneNumberExtension;
  }

  public void setPhoneNumberExtension(String phoneNumberExtension) {
    this.phoneNumberExtension = phoneNumberExtension;
  }

  public APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate validityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
    return this;
  }

   /**
   * Get validityStartDate
   * @return validityStartDate
  **/
  public String getValidityStartDate() {
    return validityStartDate;
  }

  public void setValidityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
  }

  public APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate validityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
    return this;
  }

   /**
   * Get validityEndDate
   * @return validityEndDate
  **/
  public String getValidityEndDate() {
    return validityEndDate;
  }

  public void setValidityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate apIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate = (APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate) o;
    return Objects.equals(this.destinationLocationCountry, apIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate.destinationLocationCountry) &&
        Objects.equals(this.isDefaultPhoneNumber, apIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate.isDefaultPhoneNumber) &&
        Objects.equals(this.phoneNumber, apIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate.phoneNumber) &&
        Objects.equals(this.phoneNumberExtension, apIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate.phoneNumberExtension) &&
        Objects.equals(this.validityStartDate, apIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate.validityStartDate) &&
        Objects.equals(this.validityEndDate, apIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate.validityEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationLocationCountry, isDefaultPhoneNumber, phoneNumber, phoneNumberExtension, validityStartDate, validityEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABPAddressIndependentPhoneTypeUpdate {\n");
    
    sb.append("    destinationLocationCountry: ").append(toIndentedString(destinationLocationCountry)).append("\n");
    sb.append("    isDefaultPhoneNumber: ").append(toIndentedString(isDefaultPhoneNumber)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    phoneNumberExtension: ").append(toIndentedString(phoneNumberExtension)).append("\n");
    sb.append("    validityStartDate: ").append(toIndentedString(validityStartDate)).append("\n");
    sb.append("    validityEndDate: ").append(toIndentedString(validityEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
