/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERACustomerSalesAreaTextType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERACustomerSalesAreaTextType {
  @JsonProperty("Customer")
  private String customer = null;

  @JsonProperty("SalesOrganization")
  private String salesOrganization = null;

  @JsonProperty("DistributionChannel")
  private String distributionChannel = null;

  @JsonProperty("Division")
  private String division = null;

  @JsonProperty("Language")
  private String language = null;

  @JsonProperty("LongTextID")
  private String longTextID = null;

  @JsonProperty("LongText")
  private String longText = null;

  public APIBUSINESSPARTNERACustomerSalesAreaTextType customer(String customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Customer Number
   * @return customer
  **/
  public String getCustomer() {
    return customer;
  }

  public void setCustomer(String customer) {
    this.customer = customer;
  }

  public APIBUSINESSPARTNERACustomerSalesAreaTextType salesOrganization(String salesOrganization) {
    this.salesOrganization = salesOrganization;
    return this;
  }

   /**
   * Get salesOrganization
   * @return salesOrganization
  **/
  public String getSalesOrganization() {
    return salesOrganization;
  }

  public void setSalesOrganization(String salesOrganization) {
    this.salesOrganization = salesOrganization;
  }

  public APIBUSINESSPARTNERACustomerSalesAreaTextType distributionChannel(String distributionChannel) {
    this.distributionChannel = distributionChannel;
    return this;
  }

   /**
   * Get distributionChannel
   * @return distributionChannel
  **/
  public String getDistributionChannel() {
    return distributionChannel;
  }

  public void setDistributionChannel(String distributionChannel) {
    this.distributionChannel = distributionChannel;
  }

  public APIBUSINESSPARTNERACustomerSalesAreaTextType division(String division) {
    this.division = division;
    return this;
  }

   /**
   * Get division
   * @return division
  **/
  public String getDivision() {
    return division;
  }

  public void setDivision(String division) {
    this.division = division;
  }

  public APIBUSINESSPARTNERACustomerSalesAreaTextType language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Language key
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public APIBUSINESSPARTNERACustomerSalesAreaTextType longTextID(String longTextID) {
    this.longTextID = longTextID;
    return this;
  }

   /**
   * Get longTextID
   * @return longTextID
  **/
  public String getLongTextID() {
    return longTextID;
  }

  public void setLongTextID(String longTextID) {
    this.longTextID = longTextID;
  }

  public APIBUSINESSPARTNERACustomerSalesAreaTextType longText(String longText) {
    this.longText = longText;
    return this;
  }

   /**
   * Get longText
   * @return longText
  **/
  public String getLongText() {
    return longText;
  }

  public void setLongText(String longText) {
    this.longText = longText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERACustomerSalesAreaTextType apIBUSINESSPARTNERACustomerSalesAreaTextType = (APIBUSINESSPARTNERACustomerSalesAreaTextType) o;
    return Objects.equals(this.customer, apIBUSINESSPARTNERACustomerSalesAreaTextType.customer) &&
        Objects.equals(this.salesOrganization, apIBUSINESSPARTNERACustomerSalesAreaTextType.salesOrganization) &&
        Objects.equals(this.distributionChannel, apIBUSINESSPARTNERACustomerSalesAreaTextType.distributionChannel) &&
        Objects.equals(this.division, apIBUSINESSPARTNERACustomerSalesAreaTextType.division) &&
        Objects.equals(this.language, apIBUSINESSPARTNERACustomerSalesAreaTextType.language) &&
        Objects.equals(this.longTextID, apIBUSINESSPARTNERACustomerSalesAreaTextType.longTextID) &&
        Objects.equals(this.longText, apIBUSINESSPARTNERACustomerSalesAreaTextType.longText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customer, salesOrganization, distributionChannel, division, language, longTextID, longText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERACustomerSalesAreaTextType {\n");
    
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    salesOrganization: ").append(toIndentedString(salesOrganization)).append("\n");
    sb.append("    distributionChannel: ").append(toIndentedString(distributionChannel)).append("\n");
    sb.append("    division: ").append(toIndentedString(division)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    longTextID: ").append(toIndentedString(longTextID)).append("\n");
    sb.append("    longText: ").append(toIndentedString(longText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
