/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate {
  @JsonProperty("BusinessPartner")
  private String businessPartner = null;

  @JsonProperty("AddressID")
  private String addressID = null;

  @JsonProperty("Person")
  private String person = null;

  @JsonProperty("OrdinalNumber")
  private String ordinalNumber = null;

  @JsonProperty("IsDefaultPhoneNumber")
  private Boolean isDefaultPhoneNumber = null;

  @JsonProperty("MobilePhoneCountry")
  private String mobilePhoneCountry = null;

  @JsonProperty("MobilePhoneNumber")
  private String mobilePhoneNumber = null;

  @JsonProperty("PhoneNumberExtension")
  private String phoneNumberExtension = null;

  @JsonProperty("ValidityStartDate")
  private String validityStartDate = null;

  @JsonProperty("ValidityEndDate")
  private String validityEndDate = null;

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartner
  **/
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate addressID(String addressID) {
    this.addressID = addressID;
    return this;
  }

   /**
   * Get addressID
   * @return addressID
  **/
  public String getAddressID() {
    return addressID;
  }

  public void setAddressID(String addressID) {
    this.addressID = addressID;
  }

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate ordinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
    return this;
  }

   /**
   * Get ordinalNumber
   * @return ordinalNumber
  **/
  public String getOrdinalNumber() {
    return ordinalNumber;
  }

  public void setOrdinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
  }

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate isDefaultPhoneNumber(Boolean isDefaultPhoneNumber) {
    this.isDefaultPhoneNumber = isDefaultPhoneNumber;
    return this;
  }

   /**
   * Data element for domain BOOLE: TRUE (&#x3D;&#x27;X&#x27;) and FALSE (&#x3D;&#x27; &#x27;)
   * @return isDefaultPhoneNumber
  **/
  public Boolean isIsDefaultPhoneNumber() {
    return isDefaultPhoneNumber;
  }

  public void setIsDefaultPhoneNumber(Boolean isDefaultPhoneNumber) {
    this.isDefaultPhoneNumber = isDefaultPhoneNumber;
  }

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate mobilePhoneCountry(String mobilePhoneCountry) {
    this.mobilePhoneCountry = mobilePhoneCountry;
    return this;
  }

   /**
   * Country/Region for Telephone/Fax Number
   * @return mobilePhoneCountry
  **/
  public String getMobilePhoneCountry() {
    return mobilePhoneCountry;
  }

  public void setMobilePhoneCountry(String mobilePhoneCountry) {
    this.mobilePhoneCountry = mobilePhoneCountry;
  }

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate mobilePhoneNumber(String mobilePhoneNumber) {
    this.mobilePhoneNumber = mobilePhoneNumber;
    return this;
  }

   /**
   * Telephone No.: Dialing Code and Number
   * @return mobilePhoneNumber
  **/
  public String getMobilePhoneNumber() {
    return mobilePhoneNumber;
  }

  public void setMobilePhoneNumber(String mobilePhoneNumber) {
    this.mobilePhoneNumber = mobilePhoneNumber;
  }

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate phoneNumberExtension(String phoneNumberExtension) {
    this.phoneNumberExtension = phoneNumberExtension;
    return this;
  }

   /**
   * Telephone no.: Extension
   * @return phoneNumberExtension
  **/
  public String getPhoneNumberExtension() {
    return phoneNumberExtension;
  }

  public void setPhoneNumberExtension(String phoneNumberExtension) {
    this.phoneNumberExtension = phoneNumberExtension;
  }

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate validityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
    return this;
  }

   /**
   * Get validityStartDate
   * @return validityStartDate
  **/
  public String getValidityStartDate() {
    return validityStartDate;
  }

  public void setValidityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
  }

  public APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate validityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
    return this;
  }

   /**
   * Get validityEndDate
   * @return validityEndDate
  **/
  public String getValidityEndDate() {
    return validityEndDate;
  }

  public void setValidityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate = (APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.businessPartner) &&
        Objects.equals(this.addressID, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.addressID) &&
        Objects.equals(this.person, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.person) &&
        Objects.equals(this.ordinalNumber, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.ordinalNumber) &&
        Objects.equals(this.isDefaultPhoneNumber, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.isDefaultPhoneNumber) &&
        Objects.equals(this.mobilePhoneCountry, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.mobilePhoneCountry) &&
        Objects.equals(this.mobilePhoneNumber, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.mobilePhoneNumber) &&
        Objects.equals(this.phoneNumberExtension, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.phoneNumberExtension) &&
        Objects.equals(this.validityStartDate, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.validityStartDate) &&
        Objects.equals(this.validityEndDate, apIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate.validityEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, addressID, person, ordinalNumber, isDefaultPhoneNumber, mobilePhoneCountry, mobilePhoneNumber, phoneNumberExtension, validityStartDate, validityEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABPAddressIndependentMobileTypeCreate {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    addressID: ").append(toIndentedString(addressID)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    ordinalNumber: ").append(toIndentedString(ordinalNumber)).append("\n");
    sb.append("    isDefaultPhoneNumber: ").append(toIndentedString(isDefaultPhoneNumber)).append("\n");
    sb.append("    mobilePhoneCountry: ").append(toIndentedString(mobilePhoneCountry)).append("\n");
    sb.append("    mobilePhoneNumber: ").append(toIndentedString(mobilePhoneNumber)).append("\n");
    sb.append("    phoneNumberExtension: ").append(toIndentedString(phoneNumberExtension)).append("\n");
    sb.append("    validityStartDate: ").append(toIndentedString(validityStartDate)).append("\n");
    sb.append("    validityEndDate: ").append(toIndentedString(validityEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
