/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERASupplierPurchasingOrgTextType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERASupplierPurchasingOrgTextType {
  @JsonProperty("Supplier")
  private String supplier = null;

  @JsonProperty("PurchasingOrganization")
  private String purchasingOrganization = null;

  @JsonProperty("Language")
  private String language = null;

  @JsonProperty("LongTextID")
  private String longTextID = null;

  @JsonProperty("LongText")
  private String longText = null;

  public APIBUSINESSPARTNERASupplierPurchasingOrgTextType supplier(String supplier) {
    this.supplier = supplier;
    return this;
  }

   /**
   * Account Number of Supplier
   * @return supplier
  **/
  public String getSupplier() {
    return supplier;
  }

  public void setSupplier(String supplier) {
    this.supplier = supplier;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTextType purchasingOrganization(String purchasingOrganization) {
    this.purchasingOrganization = purchasingOrganization;
    return this;
  }

   /**
   * Purchasing Organization
   * @return purchasingOrganization
  **/
  public String getPurchasingOrganization() {
    return purchasingOrganization;
  }

  public void setPurchasingOrganization(String purchasingOrganization) {
    this.purchasingOrganization = purchasingOrganization;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTextType language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Language key
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTextType longTextID(String longTextID) {
    this.longTextID = longTextID;
    return this;
  }

   /**
   * Get longTextID
   * @return longTextID
  **/
  public String getLongTextID() {
    return longTextID;
  }

  public void setLongTextID(String longTextID) {
    this.longTextID = longTextID;
  }

  public APIBUSINESSPARTNERASupplierPurchasingOrgTextType longText(String longText) {
    this.longText = longText;
    return this;
  }

   /**
   * Get longText
   * @return longText
  **/
  public String getLongText() {
    return longText;
  }

  public void setLongText(String longText) {
    this.longText = longText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERASupplierPurchasingOrgTextType apIBUSINESSPARTNERASupplierPurchasingOrgTextType = (APIBUSINESSPARTNERASupplierPurchasingOrgTextType) o;
    return Objects.equals(this.supplier, apIBUSINESSPARTNERASupplierPurchasingOrgTextType.supplier) &&
        Objects.equals(this.purchasingOrganization, apIBUSINESSPARTNERASupplierPurchasingOrgTextType.purchasingOrganization) &&
        Objects.equals(this.language, apIBUSINESSPARTNERASupplierPurchasingOrgTextType.language) &&
        Objects.equals(this.longTextID, apIBUSINESSPARTNERASupplierPurchasingOrgTextType.longTextID) &&
        Objects.equals(this.longText, apIBUSINESSPARTNERASupplierPurchasingOrgTextType.longText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplier, purchasingOrganization, language, longTextID, longText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERASupplierPurchasingOrgTextType {\n");
    
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    purchasingOrganization: ").append(toIndentedString(purchasingOrganization)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    longTextID: ").append(toIndentedString(longTextID)).append("\n");
    sb.append("    longText: ").append(toIndentedString(longText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
