/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate {
  @JsonProperty("Supplier")
  private String supplier = null;

  @JsonProperty("PurchasingOrganization")
  private String purchasingOrganization = null;

  @JsonProperty("SupplierSubrange")
  private String supplierSubrange = null;

  @JsonProperty("Plant")
  private String plant = null;

  @JsonProperty("PartnerFunction")
  private String partnerFunction = null;

  @JsonProperty("PartnerCounter")
  private String partnerCounter = null;

  @JsonProperty("DefaultPartner")
  private Boolean defaultPartner = null;

  @JsonProperty("ReferenceSupplier")
  private String referenceSupplier = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate supplier(String supplier) {
    this.supplier = supplier;
    return this;
  }

   /**
   * Account Number of Supplier
   * @return supplier
  **/
  public String getSupplier() {
    return supplier;
  }

  public void setSupplier(String supplier) {
    this.supplier = supplier;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate purchasingOrganization(String purchasingOrganization) {
    this.purchasingOrganization = purchasingOrganization;
    return this;
  }

   /**
   * Purchasing Organization
   * @return purchasingOrganization
  **/
  public String getPurchasingOrganization() {
    return purchasingOrganization;
  }

  public void setPurchasingOrganization(String purchasingOrganization) {
    this.purchasingOrganization = purchasingOrganization;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate supplierSubrange(String supplierSubrange) {
    this.supplierSubrange = supplierSubrange;
    return this;
  }

   /**
   * Get supplierSubrange
   * @return supplierSubrange
  **/
  public String getSupplierSubrange() {
    return supplierSubrange;
  }

  public void setSupplierSubrange(String supplierSubrange) {
    this.supplierSubrange = supplierSubrange;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate plant(String plant) {
    this.plant = plant;
    return this;
  }

   /**
   * Get plant
   * @return plant
  **/
  public String getPlant() {
    return plant;
  }

  public void setPlant(String plant) {
    this.plant = plant;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate partnerFunction(String partnerFunction) {
    this.partnerFunction = partnerFunction;
    return this;
  }

   /**
   * Get partnerFunction
   * @return partnerFunction
  **/
  public String getPartnerFunction() {
    return partnerFunction;
  }

  public void setPartnerFunction(String partnerFunction) {
    this.partnerFunction = partnerFunction;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate partnerCounter(String partnerCounter) {
    this.partnerCounter = partnerCounter;
    return this;
  }

   /**
   * Get partnerCounter
   * @return partnerCounter
  **/
  public String getPartnerCounter() {
    return partnerCounter;
  }

  public void setPartnerCounter(String partnerCounter) {
    this.partnerCounter = partnerCounter;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate defaultPartner(Boolean defaultPartner) {
    this.defaultPartner = defaultPartner;
    return this;
  }

   /**
   * Get defaultPartner
   * @return defaultPartner
  **/
  public Boolean isDefaultPartner() {
    return defaultPartner;
  }

  public void setDefaultPartner(Boolean defaultPartner) {
    this.defaultPartner = defaultPartner;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate referenceSupplier(String referenceSupplier) {
    this.referenceSupplier = referenceSupplier;
    return this;
  }

   /**
   * Reference to other supplier
   * @return referenceSupplier
  **/
  public String getReferenceSupplier() {
    return referenceSupplier;
  }

  public void setReferenceSupplier(String referenceSupplier) {
    this.referenceSupplier = referenceSupplier;
  }

  public APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Authorization Group
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate = (APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate) o;
    return Objects.equals(this.supplier, apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate.supplier) &&
        Objects.equals(this.purchasingOrganization, apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate.purchasingOrganization) &&
        Objects.equals(this.supplierSubrange, apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate.supplierSubrange) &&
        Objects.equals(this.plant, apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate.plant) &&
        Objects.equals(this.partnerFunction, apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate.partnerFunction) &&
        Objects.equals(this.partnerCounter, apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate.partnerCounter) &&
        Objects.equals(this.defaultPartner, apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate.defaultPartner) &&
        Objects.equals(this.referenceSupplier, apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate.referenceSupplier) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERASupplierPartnerFuncTypeCreate.authorizationGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplier, purchasingOrganization, supplierSubrange, plant, partnerFunction, partnerCounter, defaultPartner, referenceSupplier, authorizationGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERASupplierPartnerFuncTypeCreate {\n");
    
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    purchasingOrganization: ").append(toIndentedString(purchasingOrganization)).append("\n");
    sb.append("    supplierSubrange: ").append(toIndentedString(supplierSubrange)).append("\n");
    sb.append("    plant: ").append(toIndentedString(plant)).append("\n");
    sb.append("    partnerFunction: ").append(toIndentedString(partnerFunction)).append("\n");
    sb.append("    partnerCounter: ").append(toIndentedString(partnerCounter)).append("\n");
    sb.append("    defaultPartner: ").append(toIndentedString(defaultPartner)).append("\n");
    sb.append("    referenceSupplier: ").append(toIndentedString(referenceSupplier)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
