/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.axon.market.s4hana.client.APIBUSINESSPARTNERABusinessPartnerAliasType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * APIBUSINESSPARTNERABusinessPartnerTypeToBusinessPartnerAlias
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABusinessPartnerTypeToBusinessPartnerAlias {
  @JsonProperty("results")
  private List<APIBUSINESSPARTNERABusinessPartnerAliasType> results = null;

  public APIBUSINESSPARTNERABusinessPartnerTypeToBusinessPartnerAlias results(List<APIBUSINESSPARTNERABusinessPartnerAliasType> results) {
    this.results = results;
    return this;
  }

  public APIBUSINESSPARTNERABusinessPartnerTypeToBusinessPartnerAlias addResultsItem(APIBUSINESSPARTNERABusinessPartnerAliasType resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  public List<APIBUSINESSPARTNERABusinessPartnerAliasType> getResults() {
    return results;
  }

  public void setResults(List<APIBUSINESSPARTNERABusinessPartnerAliasType> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerTypeToBusinessPartnerAlias apIBUSINESSPARTNERABusinessPartnerTypeToBusinessPartnerAlias = (APIBUSINESSPARTNERABusinessPartnerTypeToBusinessPartnerAlias) o;
    return Objects.equals(this.results, apIBUSINESSPARTNERABusinessPartnerTypeToBusinessPartnerAlias.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerTypeToBusinessPartnerAlias {\n");
    
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
