/*
 * Business Partner (A2X)
 *     This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axon.market.s4hana.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * APIBUSINESSPARTNERABusinessPartnerBankType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T08:45:35.933090900+07:00[Asia/Saigon]")
public class APIBUSINESSPARTNERABusinessPartnerBankType {
  @JsonProperty("BusinessPartner")
  private String businessPartner = null;

  @JsonProperty("BankIdentification")
  private String bankIdentification = null;

  @JsonProperty("BankCountryKey")
  private String bankCountryKey = null;

  @JsonProperty("BankName")
  private String bankName = null;

  @JsonProperty("BankNumber")
  private String bankNumber = null;

  @JsonProperty("SWIFTCode")
  private String swIFTCode = null;

  @JsonProperty("BankControlKey")
  private String bankControlKey = null;

  @JsonProperty("BankAccountHolderName")
  private String bankAccountHolderName = null;

  @JsonProperty("BankAccountName")
  private String bankAccountName = null;

  @JsonProperty("ValidityStartDate")
  private String validityStartDate = null;

  @JsonProperty("ValidityEndDate")
  private String validityEndDate = null;

  @JsonProperty("IBAN")
  private String IBAN = null;

  @JsonProperty("IBANValidityStartDate")
  private String ibANValidityStartDate = null;

  @JsonProperty("BankAccount")
  private String bankAccount = null;

  @JsonProperty("BankAccountReferenceText")
  private String bankAccountReferenceText = null;

  @JsonProperty("CollectionAuthInd")
  private Boolean collectionAuthInd = null;

  @JsonProperty("CityName")
  private String cityName = null;

  @JsonProperty("AuthorizationGroup")
  private String authorizationGroup = null;

  public APIBUSINESSPARTNERABusinessPartnerBankType businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number
   * @return businessPartner
  **/
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType bankIdentification(String bankIdentification) {
    this.bankIdentification = bankIdentification;
    return this;
  }

   /**
   * Get bankIdentification
   * @return bankIdentification
  **/
  public String getBankIdentification() {
    return bankIdentification;
  }

  public void setBankIdentification(String bankIdentification) {
    this.bankIdentification = bankIdentification;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType bankCountryKey(String bankCountryKey) {
    this.bankCountryKey = bankCountryKey;
    return this;
  }

   /**
   * Bank Country/Region Key
   * @return bankCountryKey
  **/
  public String getBankCountryKey() {
    return bankCountryKey;
  }

  public void setBankCountryKey(String bankCountryKey) {
    this.bankCountryKey = bankCountryKey;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Name of Financial Institution
   * @return bankName
  **/
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType bankNumber(String bankNumber) {
    this.bankNumber = bankNumber;
    return this;
  }

   /**
   * Get bankNumber
   * @return bankNumber
  **/
  public String getBankNumber() {
    return bankNumber;
  }

  public void setBankNumber(String bankNumber) {
    this.bankNumber = bankNumber;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType swIFTCode(String swIFTCode) {
    this.swIFTCode = swIFTCode;
    return this;
  }

   /**
   * SWIFT/BIC for International Payments
   * @return swIFTCode
  **/
  public String getSwIFTCode() {
    return swIFTCode;
  }

  public void setSwIFTCode(String swIFTCode) {
    this.swIFTCode = swIFTCode;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType bankControlKey(String bankControlKey) {
    this.bankControlKey = bankControlKey;
    return this;
  }

   /**
   * Get bankControlKey
   * @return bankControlKey
  **/
  public String getBankControlKey() {
    return bankControlKey;
  }

  public void setBankControlKey(String bankControlKey) {
    this.bankControlKey = bankControlKey;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType bankAccountHolderName(String bankAccountHolderName) {
    this.bankAccountHolderName = bankAccountHolderName;
    return this;
  }

   /**
   * Account Holder Name
   * @return bankAccountHolderName
  **/
  public String getBankAccountHolderName() {
    return bankAccountHolderName;
  }

  public void setBankAccountHolderName(String bankAccountHolderName) {
    this.bankAccountHolderName = bankAccountHolderName;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType bankAccountName(String bankAccountName) {
    this.bankAccountName = bankAccountName;
    return this;
  }

   /**
   * Name of Bank Account
   * @return bankAccountName
  **/
  public String getBankAccountName() {
    return bankAccountName;
  }

  public void setBankAccountName(String bankAccountName) {
    this.bankAccountName = bankAccountName;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType validityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
    return this;
  }

   /**
   * Validity Start of Business Partner Bank Details
   * @return validityStartDate
  **/
  public String getValidityStartDate() {
    return validityStartDate;
  }

  public void setValidityStartDate(String validityStartDate) {
    this.validityStartDate = validityStartDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType validityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
    return this;
  }

   /**
   * Validity End of Business Partner Bank Details
   * @return validityEndDate
  **/
  public String getValidityEndDate() {
    return validityEndDate;
  }

  public void setValidityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType IBAN(String IBAN) {
    this.IBAN = IBAN;
    return this;
  }

   /**
   * IBAN (International Bank Account Number)
   * @return IBAN
  **/
  public String getIBAN() {
    return IBAN;
  }

  public void setIBAN(String IBAN) {
    this.IBAN = IBAN;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType ibANValidityStartDate(String ibANValidityStartDate) {
    this.ibANValidityStartDate = ibANValidityStartDate;
    return this;
  }

   /**
   * Validity Start of IBAN
   * @return ibANValidityStartDate
  **/
  public String getIbANValidityStartDate() {
    return ibANValidityStartDate;
  }

  public void setIbANValidityStartDate(String ibANValidityStartDate) {
    this.ibANValidityStartDate = ibANValidityStartDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType bankAccount(String bankAccount) {
    this.bankAccount = bankAccount;
    return this;
  }

   /**
   * Bank Account Number
   * @return bankAccount
  **/
  public String getBankAccount() {
    return bankAccount;
  }

  public void setBankAccount(String bankAccount) {
    this.bankAccount = bankAccount;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType bankAccountReferenceText(String bankAccountReferenceText) {
    this.bankAccountReferenceText = bankAccountReferenceText;
    return this;
  }

   /**
   * Reference Details for Bank Details
   * @return bankAccountReferenceText
  **/
  public String getBankAccountReferenceText() {
    return bankAccountReferenceText;
  }

  public void setBankAccountReferenceText(String bankAccountReferenceText) {
    this.bankAccountReferenceText = bankAccountReferenceText;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType collectionAuthInd(Boolean collectionAuthInd) {
    this.collectionAuthInd = collectionAuthInd;
    return this;
  }

   /**
   * Indicator: Collection Authorization
   * @return collectionAuthInd
  **/
  public Boolean isCollectionAuthInd() {
    return collectionAuthInd;
  }

  public void setCollectionAuthInd(Boolean collectionAuthInd) {
    this.collectionAuthInd = collectionAuthInd;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType cityName(String cityName) {
    this.cityName = cityName;
    return this;
  }

   /**
   * Get cityName
   * @return cityName
  **/
  public String getCityName() {
    return cityName;
  }

  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  public APIBUSINESSPARTNERABusinessPartnerBankType authorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
    return this;
  }

   /**
   * Get authorizationGroup
   * @return authorizationGroup
  **/
  public String getAuthorizationGroup() {
    return authorizationGroup;
  }

  public void setAuthorizationGroup(String authorizationGroup) {
    this.authorizationGroup = authorizationGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerBankType apIBUSINESSPARTNERABusinessPartnerBankType = (APIBUSINESSPARTNERABusinessPartnerBankType) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABusinessPartnerBankType.businessPartner) &&
        Objects.equals(this.bankIdentification, apIBUSINESSPARTNERABusinessPartnerBankType.bankIdentification) &&
        Objects.equals(this.bankCountryKey, apIBUSINESSPARTNERABusinessPartnerBankType.bankCountryKey) &&
        Objects.equals(this.bankName, apIBUSINESSPARTNERABusinessPartnerBankType.bankName) &&
        Objects.equals(this.bankNumber, apIBUSINESSPARTNERABusinessPartnerBankType.bankNumber) &&
        Objects.equals(this.swIFTCode, apIBUSINESSPARTNERABusinessPartnerBankType.swIFTCode) &&
        Objects.equals(this.bankControlKey, apIBUSINESSPARTNERABusinessPartnerBankType.bankControlKey) &&
        Objects.equals(this.bankAccountHolderName, apIBUSINESSPARTNERABusinessPartnerBankType.bankAccountHolderName) &&
        Objects.equals(this.bankAccountName, apIBUSINESSPARTNERABusinessPartnerBankType.bankAccountName) &&
        Objects.equals(this.validityStartDate, apIBUSINESSPARTNERABusinessPartnerBankType.validityStartDate) &&
        Objects.equals(this.validityEndDate, apIBUSINESSPARTNERABusinessPartnerBankType.validityEndDate) &&
        Objects.equals(this.IBAN, apIBUSINESSPARTNERABusinessPartnerBankType.IBAN) &&
        Objects.equals(this.ibANValidityStartDate, apIBUSINESSPARTNERABusinessPartnerBankType.ibANValidityStartDate) &&
        Objects.equals(this.bankAccount, apIBUSINESSPARTNERABusinessPartnerBankType.bankAccount) &&
        Objects.equals(this.bankAccountReferenceText, apIBUSINESSPARTNERABusinessPartnerBankType.bankAccountReferenceText) &&
        Objects.equals(this.collectionAuthInd, apIBUSINESSPARTNERABusinessPartnerBankType.collectionAuthInd) &&
        Objects.equals(this.cityName, apIBUSINESSPARTNERABusinessPartnerBankType.cityName) &&
        Objects.equals(this.authorizationGroup, apIBUSINESSPARTNERABusinessPartnerBankType.authorizationGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, bankIdentification, bankCountryKey, bankName, bankNumber, swIFTCode, bankControlKey, bankAccountHolderName, bankAccountName, validityStartDate, validityEndDate, IBAN, ibANValidityStartDate, bankAccount, bankAccountReferenceText, collectionAuthInd, cityName, authorizationGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerBankType {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    bankIdentification: ").append(toIndentedString(bankIdentification)).append("\n");
    sb.append("    bankCountryKey: ").append(toIndentedString(bankCountryKey)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    bankNumber: ").append(toIndentedString(bankNumber)).append("\n");
    sb.append("    swIFTCode: ").append(toIndentedString(swIFTCode)).append("\n");
    sb.append("    bankControlKey: ").append(toIndentedString(bankControlKey)).append("\n");
    sb.append("    bankAccountHolderName: ").append(toIndentedString(bankAccountHolderName)).append("\n");
    sb.append("    bankAccountName: ").append(toIndentedString(bankAccountName)).append("\n");
    sb.append("    validityStartDate: ").append(toIndentedString(validityStartDate)).append("\n");
    sb.append("    validityEndDate: ").append(toIndentedString(validityEndDate)).append("\n");
    sb.append("    IBAN: ").append(toIndentedString(IBAN)).append("\n");
    sb.append("    ibANValidityStartDate: ").append(toIndentedString(ibANValidityStartDate)).append("\n");
    sb.append("    bankAccount: ").append(toIndentedString(bankAccount)).append("\n");
    sb.append("    bankAccountReferenceText: ").append(toIndentedString(bankAccountReferenceText)).append("\n");
    sb.append("    collectionAuthInd: ").append(toIndentedString(collectionAuthInd)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    authorizationGroup: ").append(toIndentedString(authorizationGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
