# == Variables ==
Variables:
  s4HanaConnector:
    # The first part of URI for Rest Service. E.g. https://${your base Url}/sap/opu/odata/SAP/API_BUSINESS_PARTNER
    baseUrl: ""
    # The username for Rest Service Authentication
    username: ""
    # The password for Rest Service Authentication
    password: ""